
insert into accommodation (Service_id, Name) values (1, 'Crystal Stay');
insert into accommodation (Service_id, Name) values (2, 'Golden Stay Golf Resort');
insert into accommodation (Service_id, Name) values (3, 'Regency Lodge');
insert into accommodation (Service_id, Name) values (4, 'Boutique Villas Bayview');
insert into accommodation (Service_id, Name) values (5, 'The Ocean Manor');
insert into accommodation (Service_id, Name) values (6, 'Plaza Stay');
insert into accommodation (Service_id, Name) values (7, 'Crystal Hideaway');
insert into accommodation (Service_id, Name) values (8, 'Golden Chalet Luxury Club');
insert into accommodation (Service_id, Name) values (9, 'Alpine Palace Spa & Wellness');
insert into accommodation (Service_id, Name) values (10, 'Radisson Resort');
insert into accommodation (Service_id, Name) values (11, 'Grand Hideaway Riverside');
insert into accommodation (Service_id, Name) values (12, 'Plaza Chalet');
insert into accommodation (Service_id, Name) values (13, 'Golden Retreat Downtown');
insert into accommodation (Service_id, Name) values (14, 'The Sunset Hideaway');
insert into accommodation (Service_id, Name) values (15, 'Plaza Chalet');
insert into accommodation (Service_id, Name) values (16, 'The Radisson Lodge');
insert into accommodation (Service_id, Name) values (17, 'The Golden Hideaway');
insert into accommodation (Service_id, Name) values (18, 'Royal Suites Riverside');
insert into accommodation (Service_id, Name) values (19, 'The Crystal Retreat');
insert into accommodation (Service_id, Name) values (20, 'Hilton Villas Mountain View');
insert into accommodation (Service_id, Name) values (21, 'The Regency Hotel');
insert into accommodation (Service_id, Name) values (22, 'Royal Gardens Luxury Club');
insert into accommodation (Service_id, Name) values (23, 'Vista Stay Spa & Wellness');
insert into accommodation (Service_id, Name) values (24, 'Urban House by the Sea');
insert into accommodation (Service_id, Name) values (25, 'Radisson Suites Mountain View');
insert into accommodation (Service_id, Name) values (26, 'The Alpine House');
insert into accommodation (Service_id, Name) values (27, 'The Alpine Lodge');
insert into accommodation (Service_id, Name) values (28, 'Crystal House');
insert into accommodation (Service_id, Name) values (29, 'Radisson Resort');
insert into accommodation (Service_id, Name) values (30, 'Serene Gardens Mountain View');
insert into accommodation (Service_id, Name) values (31, 'The Sunset Hideaway');
insert into accommodation (Service_id, Name) values (32, 'The Regency Lodge');
insert into accommodation (Service_id, Name) values (33, 'Golden House Mountain View');
insert into accommodation (Service_id, Name) values (34, 'Serene Gardens Mountain View');
insert into accommodation (Service_id, Name) values (35, 'Serene Stay');
insert into accommodation (Service_id, Name) values (36, 'Radisson Villas');
insert into accommodation (Service_id, Name) values (37, 'Golden House Mountain View');
insert into accommodation (Service_id, Name) values (38, 'Ocean Hotel');
insert into accommodation (Service_id, Name) values (39, 'Regency Suites Eco Lodge');
insert into accommodation (Service_id, Name) values (40, 'Vista Haven');
insert into accommodation (Service_id, Name) values (41, 'The Alpine House');
insert into accommodation (Service_id, Name) values (42, 'The Hilton Hideaway');
insert into accommodation (Service_id, Name) values (43, 'The Urban Gardens');
insert into accommodation (Service_id, Name) values (44, 'The Regency Inn');
insert into accommodation (Service_id, Name) values (45, 'The Serene Chalet');
insert into accommodation (Service_id, Name) values (46, 'Ocean Retreat Downtown');
insert into accommodation (Service_id, Name) values (47, 'Crystal Hotel Golf Resort');
insert into accommodation (Service_id, Name) values (48, 'Alpine Palace Spa & Wellness');
insert into accommodation (Service_id, Name) values (49, 'Alpine Haven');
insert into accommodation (Service_id, Name) values (50, 'The Regency Hotel');
insert into accommodation (Service_id, Name) values (51, 'The Golden Stay');
insert into accommodation (Service_id, Name) values (52, 'Grand Gardens');
insert into accommodation (Service_id, Name) values (53, 'Golden Inn Spa & Wellness');
insert into accommodation (Service_id, Name) values (54, 'Ocean Inn Beachfront');
insert into accommodation (Service_id, Name) values (55, 'The Vista Suites');
insert into accommodation (Service_id, Name) values (56, 'Boutique Suites');
insert into accommodation (Service_id, Name) values (57, 'Radisson Retreat Bayview');
insert into accommodation (Service_id, Name) values (58, 'Golden House Mountain View');
insert into accommodation (Service_id, Name) values (59, 'Serene Oasis');
insert into accommodation (Service_id, Name) values (60, 'Golden Inn Spa & Wellness');
insert into accommodation (Service_id, Name) values (61, 'Heritage Stay Luxury Club');
insert into accommodation (Service_id, Name) values (62, 'Golden Gardens');
insert into accommodation (Service_id, Name) values (63, 'Heritage Hotel Golf Resort');
insert into accommodation (Service_id, Name) values (64, 'Boutique Chalet');
insert into accommodation (Service_id, Name) values (65, 'Ocean Hotel');
insert into accommodation (Service_id, Name) values (66, 'Alpine Haven');
insert into accommodation (Service_id, Name) values (67, 'Radisson Resort');
insert into accommodation (Service_id, Name) values (68, 'Golden Manor Luxury Club');
insert into accommodation (Service_id, Name) values (69, 'Regency Lodge');
insert into accommodation (Service_id, Name) values (70, 'Ocean Inn Beachfront');
insert into accommodation (Service_id, Name) values (71, 'Alpine Suites');
insert into accommodation (Service_id, Name) values (72, 'Radisson Retreat Bayview');
insert into accommodation (Service_id, Name) values (73, 'Crystal Stay');
insert into accommodation (Service_id, Name) values (74, 'The Regency Hotel');
insert into accommodation (Service_id, Name) values (75, 'Crystal House');
insert into accommodation (Service_id, Name) values (76, 'The Alpine House');
insert into accommodation (Service_id, Name) values (77, 'Royal Suites Riverside');
insert into accommodation (Service_id, Name) values (78, 'Ocean Inn Beachfront');
insert into accommodation (Service_id, Name) values (79, 'The Crystal Retreat');
insert into accommodation (Service_id, Name) values (80, 'The Alpine House');
insert into accommodation (Service_id, Name) values (81, 'The Alpine Oasis');
insert into accommodation (Service_id, Name) values (82, 'Grand Hideaway Riverside');
insert into accommodation (Service_id, Name) values (83, 'Regency Retreat');
insert into accommodation (Service_id, Name) values (84, 'Golden House Mountain View');
insert into accommodation (Service_id, Name) values (85, 'Golden Stay Golf Resort');
insert into accommodation (Service_id, Name) values (86, 'Heritage Lodge');
insert into accommodation (Service_id, Name) values (87, 'The Urban Gardens');
insert into accommodation (Service_id, Name) values (88, 'Urban House by the Sea');
insert into accommodation (Service_id, Name) values (89, 'Heritage Villas');
insert into accommodation (Service_id, Name) values (90, 'Radisson Resort');
insert into accommodation (Service_id, Name) values (91, 'Urban House by the Sea');
insert into accommodation (Service_id, Name) values (92, 'Ocean Hotel');
insert into accommodation (Service_id, Name) values (93, 'Urban House by the Sea');
insert into accommodation (Service_id, Name) values (94, 'Serene Stay');
insert into accommodation (Service_id, Name) values (95, 'Urban Lodge by the Sea');
insert into accommodation (Service_id, Name) values (96, 'Crystal Hideaway');
insert into accommodation (Service_id, Name) values (97, 'Alpine Haven');
insert into accommodation (Service_id, Name) values (98, 'The Regency Inn');
insert into accommodation (Service_id, Name) values (99, 'Golden Manor');
insert into accommodation (Service_id, Name) values (100, 'Regency Oasis Beachfront');
insert into accommodation (Service_id, Name) values (101, 'Alpine Palace Spa & Wellness');
insert into accommodation (Service_id, Name) values (102, 'Urban House by the Sea');
insert into accommodation (Service_id, Name) values (103, 'The Crystal Hideaway');
insert into accommodation (Service_id, Name) values (104, 'Alpine Suites');
insert into accommodation (Service_id, Name) values (105, 'Boutique Stay');
insert into accommodation (Service_id, Name) values (106, 'The Urban Oasis');
insert into accommodation (Service_id, Name) values (107, 'Golden Retreat Downtown');
insert into accommodation (Service_id, Name) values (108, 'Boutique Lodge Downtown');
insert into accommodation (Service_id, Name) values (109, 'Serene Oasis');
insert into accommodation (Service_id, Name) values (110, 'The Ocean Manor');
insert into accommodation (Service_id, Name) values (111, 'Grand Gardens');
insert into accommodation (Service_id, Name) values (112, 'The Alpine Hideaway');
insert into accommodation (Service_id, Name) values (113, 'The Royal Oasis');
insert into accommodation (Service_id, Name) values (114, 'Crystal Suites Spa & Wellness');
insert into accommodation (Service_id, Name) values (115, 'Ocean Oasis');
insert into accommodation (Service_id, Name) values (116, 'Golden Chalet Luxury Club');
insert into accommodation (Service_id, Name) values (117, 'Ocean Hotel');
insert into accommodation (Service_id, Name) values (118, 'The Boutique Hideaway');
insert into accommodation (Service_id, Name) values (119, 'Vista Stay Spa & Wellness');
insert into accommodation (Service_id, Name) values (120, 'Sunset Retreat Downtown');
insert into accommodation (Service_id, Name) values (121, 'Crystal House');
insert into accommodation (Service_id, Name) values (122, 'Heritage Stay Luxury Club');
insert into accommodation (Service_id, Name) values (123, 'Sunset Oasis Downtown');
insert into accommodation (Service_id, Name) values (124, 'Boutique Chalet');
insert into accommodation (Service_id, Name) values (125, 'Serene Stay');
insert into accommodation (Service_id, Name) values (126, 'Ocean Hotel');
insert into accommodation (Service_id, Name) values (127, 'The Alpine Hideaway');
insert into accommodation (Service_id, Name) values (128, 'The Alpine Lodge');
insert into accommodation (Service_id, Name) values (129, 'The Crystal Hideaway');
insert into accommodation (Service_id, Name) values (130, 'Golden Stay Golf Resort');
insert into accommodation (Service_id, Name) values (131, 'The Serene Hideaway');
insert into accommodation (Service_id, Name) values (132, 'The Alpine Hideaway');
insert into accommodation (Service_id, Name) values (133, 'Royal Suites Riverside');
insert into accommodation (Service_id, Name) values (134, 'Boutique Inn');
insert into accommodation (Service_id, Name) values (135, 'Hilton Villas Mountain View');
insert into accommodation (Service_id, Name) values (136, 'The Serene Hideaway');
insert into accommodation (Service_id, Name) values (137, 'Royal Gardens Luxury Club');
insert into accommodation (Service_id, Name) values (138, 'Radisson Suites Mountain View');
insert into accommodation (Service_id, Name) values (139, 'Boutique Retreat');
insert into accommodation (Service_id, Name) values (140, 'The Alpine Haven');
insert into accommodation (Service_id, Name) values (141, 'Heritage Villas');
insert into accommodation (Service_id, Name) values (142, 'Plaza Chalet');
insert into accommodation (Service_id, Name) values (143, 'The Ocean Manor');
insert into accommodation (Service_id, Name) values (144, 'Alpine Haven');
insert into accommodation (Service_id, Name) values (145, 'Radisson Stay');
insert into accommodation (Service_id, Name) values (146, 'Heritage Hotel Golf Resort');
insert into accommodation (Service_id, Name) values (147, 'The Regency Inn');
insert into accommodation (Service_id, Name) values (148, 'Ocean Inn Beachfront');
insert into accommodation (Service_id, Name) values (149, 'Crystal Hideaway');
insert into accommodation (Service_id, Name) values (150, 'Sunset Oasis Downtown');
insert into accommodation (Service_id, Name) values (151, 'The Serene Chalet');
insert into accommodation (Service_id, Name) values (152, 'The Royal Oasis');
insert into accommodation (Service_id, Name) values (153, 'The Boutique Hideaway');
insert into accommodation (Service_id, Name) values (154, 'Sunset Hideaway Spa & Wellness');
insert into accommodation (Service_id, Name) values (155, 'The Heritage House');
insert into accommodation (Service_id, Name) values (156, 'Regency House Mountain View');
insert into accommodation (Service_id, Name) values (157, 'Grand Retreat');
insert into accommodation (Service_id, Name) values (158, 'Grand Resort');
insert into accommodation (Service_id, Name) values (159, 'Grand Retreat');
insert into accommodation (Service_id, Name) values (160, 'Crystal Stay');
insert into accommodation (Service_id, Name) values (161, 'Grand Chalet');
insert into accommodation (Service_id, Name) values (162, 'The Vista Suites');
insert into accommodation (Service_id, Name) values (163, 'Plaza Stay');
insert into accommodation (Service_id, Name) values (164, 'The Alpine Oasis');
insert into accommodation (Service_id, Name) values (165, 'Urban Haven Beachfront');
insert into accommodation (Service_id, Name) values (166, 'The Plaza Palace');
insert into accommodation (Service_id, Name) values (167, 'The Crystal Retreat');
insert into accommodation (Service_id, Name) values (168, 'Heritage Lodge');
insert into accommodation (Service_id, Name) values (169, 'The Alpine Oasis');
insert into accommodation (Service_id, Name) values (170, 'Radisson Resort');
insert into accommodation (Service_id, Name) values (171, 'The Regency Inn');
insert into accommodation (Service_id, Name) values (172, 'The Vista Suites');
insert into accommodation (Service_id, Name) values (173, 'Boutique Villas Bayview');
insert into accommodation (Service_id, Name) values (174, 'Boutique Chalet');
insert into accommodation (Service_id, Name) values (175, 'Royal Suites Riverside');
insert into accommodation (Service_id, Name) values (176, 'The Alpine Hideaway');
insert into accommodation (Service_id, Name) values (177, 'Golden Gardens');
insert into accommodation (Service_id, Name) values (178, 'Regency Suites Eco Lodge');
insert into accommodation (Service_id, Name) values (179, 'Heritage Villas');
insert into accommodation (Service_id, Name) values (180, 'The Hilton Hideaway');
insert into accommodation (Service_id, Name) values (181, 'Boutique Villas Bayview');
insert into accommodation (Service_id, Name) values (182, 'Boutique Stay');
insert into accommodation (Service_id, Name) values (183, 'Heritage Hotel Golf Resort');
insert into accommodation (Service_id, Name) values (184, 'Alpine Suites');
insert into accommodation (Service_id, Name) values (185, 'Heritage Villas');
insert into accommodation (Service_id, Name) values (186, 'Golden Retreat Downtown');
insert into accommodation (Service_id, Name) values (187, 'Serene Stay');
insert into accommodation (Service_id, Name) values (188, 'Ocean Retreat Downtown');
insert into accommodation (Service_id, Name) values (189, 'The Radisson Lodge');
insert into accommodation (Service_id, Name) values (190, 'The Plaza Palace');
insert into accommodation (Service_id, Name) values (191, 'Radisson Resort');
insert into accommodation (Service_id, Name) values (192, 'The Hilton House');
insert into accommodation (Service_id, Name) values (193, 'Golden Retreat Downtown');
insert into accommodation (Service_id, Name) values (194, 'The Regency Inn');
insert into accommodation (Service_id, Name) values (195, 'Radisson Resort');
insert into accommodation (Service_id, Name) values (196, 'The Sunset Oasis');
insert into accommodation (Service_id, Name) values (197, 'Serene Stay');
insert into accommodation (Service_id, Name) values (198, 'Boutique Inn');
insert into accommodation (Service_id, Name) values (199, 'Alpine Palace Spa & Wellness');
insert into accommodation (Service_id, Name) values (200, 'Heritage Hotel by the Sea');
insert into accommodation (Service_id, Name) values (201, 'Boutique Inn');
insert into accommodation (Service_id, Name) values (202, 'Serene Oasis');
insert into accommodation (Service_id, Name) values (203, 'Vista Haven');
insert into accommodation (Service_id, Name) values (204, 'Sunset Oasis Downtown');
insert into accommodation (Service_id, Name) values (205, 'Radisson Villas');
insert into accommodation (Service_id, Name) values (206, 'The Alpine Lodge');
insert into accommodation (Service_id, Name) values (207, 'The Crystal Hideaway');
insert into accommodation (Service_id, Name) values (208, 'Grand Retreat');
insert into accommodation (Service_id, Name) values (209, 'Plaza Chalet');
insert into accommodation (Service_id, Name) values (210, 'Golden Manor Luxury Club');
insert into accommodation (Service_id, Name) values (211, 'The Crystal Retreat');
insert into accommodation (Service_id, Name) values (212, 'The Vista Manor');
insert into accommodation (Service_id, Name) values (213, 'The Serene Chalet');
insert into accommodation (Service_id, Name) values (214, 'Urban Haven Beachfront');
insert into accommodation (Service_id, Name) values (215, 'Heritage Villas');
insert into accommodation (Service_id, Name) values (216, 'The Golden Stay');
insert into accommodation (Service_id, Name) values (217, 'Heritage Hotel Golf Resort');
insert into accommodation (Service_id, Name) values (218, 'Heritage Hotel Golf Resort');
insert into accommodation (Service_id, Name) values (219, 'The Alpine Lodge');
insert into accommodation (Service_id, Name) values (220, 'Golden Gardens');
insert into accommodation (Service_id, Name) values (221, 'Regency Lodge');
insert into accommodation (Service_id, Name) values (222, 'The Golden Stay');
insert into accommodation (Service_id, Name) values (223, 'The Boutique Hideaway');
insert into accommodation (Service_id, Name) values (224, 'Royal Suites Riverside');
insert into accommodation (Service_id, Name) values (225, 'Golden Stay Golf Resort');
insert into accommodation (Service_id, Name) values (226, 'Regency Retreat');
insert into accommodation (Service_id, Name) values (227, 'Urban Retreat');
insert into accommodation (Service_id, Name) values (228, 'Urban Manor Eco Lodge');
insert into accommodation (Service_id, Name) values (229, 'Crystal Stay');
insert into accommodation (Service_id, Name) values (230, 'Regency Lodge');
insert into accommodation (Service_id, Name) values (231, 'Radisson Resort');
insert into accommodation (Service_id, Name) values (232, 'Ocean Oasis');
insert into accommodation (Service_id, Name) values (233, 'Ocean Inn Beachfront');
insert into accommodation (Service_id, Name) values (234, 'Urban Haven Beachfront');
insert into accommodation (Service_id, Name) values (235, 'The Radisson Lodge');
insert into accommodation (Service_id, Name) values (236, 'Heritage Stay Luxury Club');
insert into accommodation (Service_id, Name) values (237, 'Radisson Manor');
insert into accommodation (Service_id, Name) values (238, 'Golden Gardens');
insert into accommodation (Service_id, Name) values (239, 'Boutique Stay');
insert into accommodation (Service_id, Name) values (240, 'The Urban Oasis');
insert into accommodation (Service_id, Name) values (241, 'The Hilton House');
insert into accommodation (Service_id, Name) values (242, 'The Urban Gardens');
insert into accommodation (Service_id, Name) values (243, 'Crystal Hotel Golf Resort');
insert into accommodation (Service_id, Name) values (244, 'Plaza Stay');
insert into accommodation (Service_id, Name) values (245, 'Heritage Lodge');
insert into accommodation (Service_id, Name) values (246, 'The Alpine Oasis');
insert into accommodation (Service_id, Name) values (247, 'Grand Hideaway Riverside');
insert into accommodation (Service_id, Name) values (248, 'Urban Lodge by the Sea');
insert into accommodation (Service_id, Name) values (249, 'Golden Gardens');
insert into accommodation (Service_id, Name) values (250, 'The Urban Oasis');
insert into accommodation (Service_id, Name) values (251, 'Grand Chalet');
insert into accommodation (Service_id, Name) values (252, 'Radisson Suites Mountain View');
insert into accommodation (Service_id, Name) values (253, 'The Urban Gardens');
insert into accommodation (Service_id, Name) values (254, 'The Alpine Lodge');
insert into accommodation (Service_id, Name) values (255, 'Crystal Stay');
insert into accommodation (Service_id, Name) values (256, 'The Sunset Oasis');
insert into accommodation (Service_id, Name) values (257, 'The Ocean Manor');
insert into accommodation (Service_id, Name) values (258, 'The Hilton Hideaway');
insert into accommodation (Service_id, Name) values (259, 'Ocean Hotel');
insert into accommodation (Service_id, Name) values (260, 'Crystal Hideaway');
insert into accommodation (Service_id, Name) values (261, 'The Hilton House');
insert into accommodation (Service_id, Name) values (262, 'The Vista Manor');
insert into accommodation (Service_id, Name) values (263, 'The Hilton House');
insert into accommodation (Service_id, Name) values (264, 'The Vista Suites');
insert into accommodation (Service_id, Name) values (265, 'Sunset Hideaway Spa & Wellness');
insert into accommodation (Service_id, Name) values (266, 'Golden Manor');
insert into accommodation (Service_id, Name) values (267, 'The Sunset Oasis');
insert into accommodation (Service_id, Name) values (268, 'Boutique Villas Bayview');
insert into accommodation (Service_id, Name) values (269, 'The Vista Manor');
insert into accommodation (Service_id, Name) values (270, 'Crystal House Beachfront');
insert into accommodation (Service_id, Name) values (271, 'Radisson Manor');
insert into accommodation (Service_id, Name) values (272, 'Crystal House Beachfront');
insert into accommodation (Service_id, Name) values (273, 'Urban House by the Sea');
insert into accommodation (Service_id, Name) values (274, 'Urban Haven Beachfront');
insert into accommodation (Service_id, Name) values (275, 'Sunset Retreat Downtown');
insert into accommodation (Service_id, Name) values (276, 'The Alpine Haven');
insert into accommodation (Service_id, Name) values (277, 'The Plaza Palace');
insert into accommodation (Service_id, Name) values (278, 'Crystal Hideaway');
insert into accommodation (Service_id, Name) values (279, 'Golden Manor Luxury Club');
insert into accommodation (Service_id, Name) values (280, 'Boutique Retreat');
insert into accommodation (Service_id, Name) values (281, 'Grand Resort');
insert into accommodation (Service_id, Name) values (282, 'Golden Retreat');
insert into accommodation (Service_id, Name) values (283, 'Crystal Hotel Golf Resort');
insert into accommodation (Service_id, Name) values (284, 'Serene Gardens Mountain View');
insert into accommodation (Service_id, Name) values (285, 'Urban House by the Sea');
insert into accommodation (Service_id, Name) values (286, 'Radisson Stay');
insert into accommodation (Service_id, Name) values (287, 'Heritage Stay Luxury Club');
insert into accommodation (Service_id, Name) values (288, 'Urban Lodge by the Sea');
insert into accommodation (Service_id, Name) values (289, 'Regency Retreat');
insert into accommodation (Service_id, Name) values (290, 'Heritage Stay Luxury Club');
insert into accommodation (Service_id, Name) values (291, 'Heritage Villas');
insert into accommodation (Service_id, Name) values (292, 'Grand Chalet');
insert into accommodation (Service_id, Name) values (293, 'Golden Stay Golf Resort');
insert into accommodation (Service_id, Name) values (294, 'The Ocean Manor');
insert into accommodation (Service_id, Name) values (295, 'Plaza Chalet');
insert into accommodation (Service_id, Name) values (296, 'The Hilton House');
insert into accommodation (Service_id, Name) values (297, 'Boutique Suites');
insert into accommodation (Service_id, Name) values (298, 'Golden Stay Golf Resort');
insert into accommodation (Service_id, Name) values (299, 'Boutique Villas Bayview');
insert into accommodation (Service_id, Name) values (300, 'Sunset Retreat Downtown');
insert into accommodation (Service_id, Name) values (301, 'Boutique Suites');
insert into accommodation (Service_id, Name) values (302, 'The Ocean Manor');
insert into accommodation (Service_id, Name) values (303, 'The Crystal Hideaway');
insert into accommodation (Service_id, Name) values (304, 'Sunset Oasis Downtown');
insert into accommodation (Service_id, Name) values (305, 'The Regency Inn');
insert into accommodation (Service_id, Name) values (306, 'Urban Manor Eco Lodge');
insert into accommodation (Service_id, Name) values (307, 'Serene Gardens Mountain View');
insert into accommodation (Service_id, Name) values (308, 'The Alpine Oasis');
insert into accommodation (Service_id, Name) values (309, 'Ocean Retreat Downtown');
insert into accommodation (Service_id, Name) values (310, 'Urban Manor Eco Lodge');
insert into accommodation (Service_id, Name) values (311, 'The Golden Stay');
insert into accommodation (Service_id, Name) values (312, 'Ocean Hotel');
insert into accommodation (Service_id, Name) values (313, 'Urban Retreat');
insert into accommodation (Service_id, Name) values (314, 'The Crystal Retreat');
insert into accommodation (Service_id, Name) values (315, 'Sunset Hideaway Spa & Wellness');
insert into accommodation (Service_id, Name) values (316, 'Golden Gardens');
insert into accommodation (Service_id, Name) values (317, 'Golden Manor Luxury Club');
insert into accommodation (Service_id, Name) values (318, 'Hilton Villas Mountain View');
insert into accommodation (Service_id, Name) values (319, 'Grand Hideaway Riverside');
insert into accommodation (Service_id, Name) values (320, 'Boutique Villas Bayview');
insert into accommodation (Service_id, Name) values (321, 'Grand Resort');
insert into accommodation (Service_id, Name) values (322, 'The Radisson Lodge');
insert into accommodation (Service_id, Name) values (323, 'Sunset Hideaway Spa & Wellness');
insert into accommodation (Service_id, Name) values (324, 'Urban Haven Beachfront');
insert into accommodation (Service_id, Name) values (325, 'Ocean Oasis');
insert into accommodation (Service_id, Name) values (326, 'The Alpine House');
insert into accommodation (Service_id, Name) values (327, 'The Alpine Oasis');
insert into accommodation (Service_id, Name) values (328, 'The Alpine Haven');
insert into accommodation (Service_id, Name) values (329, 'Radisson Stay');
insert into accommodation (Service_id, Name) values (330, 'Alpine Palace Spa & Wellness');
insert into accommodation (Service_id, Name) values (331, 'Sunset Retreat Downtown');
insert into accommodation (Service_id, Name) values (332, 'The Regency Lodge');
insert into accommodation (Service_id, Name) values (333, 'Radisson Suites Mountain View');
insert into accommodation (Service_id, Name) values (334, 'Boutique Retreat');
insert into accommodation (Service_id, Name) values (335, 'Golden Gardens');
insert into accommodation (Service_id, Name) values (336, 'The Ocean Manor');
insert into accommodation (Service_id, Name) values (337, 'Regency Retreat');
insert into accommodation (Service_id, Name) values (338, 'Boutique Chalet');
insert into accommodation (Service_id, Name) values (339, 'The Boutique Hideaway');
insert into accommodation (Service_id, Name) values (340, 'Golden Manor');
insert into accommodation (Service_id, Name) values (341, 'Golden Retreat Downtown');
insert into accommodation (Service_id, Name) values (342, 'Vista Stay Spa & Wellness');
insert into accommodation (Service_id, Name) values (343, 'The Serene Chalet');
insert into accommodation (Service_id, Name) values (344, 'Crystal Stay');
insert into accommodation (Service_id, Name) values (345, 'Grand Hideaway Riverside');
insert into accommodation (Service_id, Name) values (346, 'Radisson Retreat Bayview');
insert into accommodation (Service_id, Name) values (347, 'Regency Suites Eco Lodge');
insert into accommodation (Service_id, Name) values (348, 'Regency Retreat');
insert into accommodation (Service_id, Name) values (349, 'The Sunset Oasis');
insert into accommodation (Service_id, Name) values (350, 'Boutique Gardens Eco Lodge');
insert into accommodation (Service_id, Name) values (351, 'The Alpine Hideaway');
insert into accommodation (Service_id, Name) values (352, 'Grand Hideaway Riverside');
insert into accommodation (Service_id, Name) values (353, 'The Ocean Manor');
insert into accommodation (Service_id, Name) values (354, 'Sunset Hideaway Spa & Wellness');
insert into accommodation (Service_id, Name) values (355, 'The Regency Hotel');
insert into accommodation (Service_id, Name) values (356, 'Boutique Gardens Eco Lodge');
insert into accommodation (Service_id, Name) values (357, 'Crystal Hideaway');
insert into accommodation (Service_id, Name) values (358, 'Crystal House');
insert into accommodation (Service_id, Name) values (359, 'Grand Gardens');
insert into accommodation (Service_id, Name) values (360, 'The Serene Chalet');
insert into accommodation (Service_id, Name) values (361, 'Urban Lodge by the Sea');
insert into accommodation (Service_id, Name) values (362, 'Golden Stay Golf Resort');
insert into accommodation (Service_id, Name) values (363, 'Grand Hideaway Riverside');
insert into accommodation (Service_id, Name) values (364, 'Ocean Oasis');
insert into accommodation (Service_id, Name) values (365, 'Heritage Hotel Golf Resort');
insert into accommodation (Service_id, Name) values (366, 'Golden Gardens');
insert into accommodation (Service_id, Name) values (367, 'Heritage Villas');
insert into accommodation (Service_id, Name) values (368, 'Regency Oasis Beachfront');
insert into accommodation (Service_id, Name) values (369, 'Heritage Hotel by the Sea');
insert into accommodation (Service_id, Name) values (370, 'The Royal Oasis');
insert into accommodation (Service_id, Name) values (371, 'Alpine Palace Spa & Wellness');
insert into accommodation (Service_id, Name) values (372, 'Vista Haven');
insert into accommodation (Service_id, Name) values (373, 'Sunset Oasis Downtown');
insert into accommodation (Service_id, Name) values (374, 'Urban Haven Beachfront');
insert into accommodation (Service_id, Name) values (375, 'Grand Resort');
insert into accommodation (Service_id, Name) values (376, 'Sunset Oasis Downtown');
insert into accommodation (Service_id, Name) values (377, 'Plaza Stay');
insert into accommodation (Service_id, Name) values (378, 'The Crystal Retreat');
insert into accommodation (Service_id, Name) values (379, 'The Vista Manor');
insert into accommodation (Service_id, Name) values (380, 'Sunset Oasis Downtown');
insert into accommodation (Service_id, Name) values (381, 'Boutique Chalet');
insert into accommodation (Service_id, Name) values (382, 'The Radisson Lodge');
insert into accommodation (Service_id, Name) values (383, 'Heritage Villas');
insert into accommodation (Service_id, Name) values (384, 'Plaza Villas');
insert into accommodation (Service_id, Name) values (385, 'The Alpine Lodge');
insert into accommodation (Service_id, Name) values (386, 'Plaza Stay');
insert into accommodation (Service_id, Name) values (387, 'The Alpine Lodge');
insert into accommodation (Service_id, Name) values (388, 'The Regency Hotel');
insert into accommodation (Service_id, Name) values (389, 'Alpine Haven');
insert into accommodation (Service_id, Name) values (390, 'Boutique Lodge Downtown');
insert into accommodation (Service_id, Name) values (391, 'The Vista Manor');
insert into accommodation (Service_id, Name) values (392, 'Golden Retreat Downtown');
insert into accommodation (Service_id, Name) values (393, 'Grand Gardens');
insert into accommodation (Service_id, Name) values (394, 'Heritage Villas');
insert into accommodation (Service_id, Name) values (395, 'Radisson Resort');
insert into accommodation (Service_id, Name) values (396, 'Boutique Resort Spa & Wellness');
insert into accommodation (Service_id, Name) values (397, 'The Sunset Hideaway');
insert into accommodation (Service_id, Name) values (398, 'Sunset Retreat Downtown');
insert into accommodation (Service_id, Name) values (399, 'Ocean Inn Beachfront');
insert into accommodation (Service_id, Name) values (400, 'Grand Chalet');
insert into accommodation (Service_id, Name) values (401, 'The Sunset Oasis');
insert into accommodation (Service_id, Name) values (402, 'Ocean Retreat Downtown');
insert into accommodation (Service_id, Name) values (403, 'Crystal Stay');
insert into accommodation (Service_id, Name) values (404, 'Ocean Hotel');
insert into accommodation (Service_id, Name) values (405, 'The Regency Inn');
insert into accommodation (Service_id, Name) values (406, 'Grand Resort');
insert into accommodation (Service_id, Name) values (407, 'Radisson Manor');
insert into accommodation (Service_id, Name) values (408, 'Grand Resort');
insert into accommodation (Service_id, Name) values (409, 'The Serene Hideaway');
insert into accommodation (Service_id, Name) values (410, 'The Plaza Palace');
insert into accommodation (Service_id, Name) values (411, 'The Hilton Hideaway');
insert into accommodation (Service_id, Name) values (412, 'Ocean Hotel');
insert into accommodation (Service_id, Name) values (413, 'Crystal Hideaway');
insert into accommodation (Service_id, Name) values (414, 'Urban House by the Sea');
insert into accommodation (Service_id, Name) values (415, 'Hilton Villas Mountain View');
insert into accommodation (Service_id, Name) values (416, 'The Sunset Hideaway');
insert into accommodation (Service_id, Name) values (417, 'The Serene Hideaway');
insert into accommodation (Service_id, Name) values (418, 'Vista Haven');
insert into accommodation (Service_id, Name) values (419, 'The Urban Gardens');
insert into accommodation (Service_id, Name) values (420, 'Regency Oasis Beachfront');
insert into accommodation (Service_id, Name) values (421, 'Sunset Retreat Downtown');
insert into accommodation (Service_id, Name) values (422, 'The Sunset Hideaway');
insert into accommodation (Service_id, Name) values (423, 'Boutique Inn');
insert into accommodation (Service_id, Name) values (424, 'Regency House Mountain View');
insert into accommodation (Service_id, Name) values (425, 'Vista Stay Spa & Wellness');
insert into accommodation (Service_id, Name) values (426, 'Alpine Suites');
insert into accommodation (Service_id, Name) values (427, 'Boutique Resort Spa & Wellness');
insert into accommodation (Service_id, Name) values (428, 'Heritage Lodge');
insert into accommodation (Service_id, Name) values (429, 'Urban Retreat');
insert into accommodation (Service_id, Name) values (430, 'The Alpine Haven');
insert into accommodation (Service_id, Name) values (431, 'Golden Retreat');
insert into accommodation (Service_id, Name) values (432, 'The Alpine House');
insert into accommodation (Service_id, Name) values (433, 'Alpine Suites');
insert into accommodation (Service_id, Name) values (434, 'Grand Resort');
insert into accommodation (Service_id, Name) values (435, 'The Alpine House');
insert into accommodation (Service_id, Name) values (436, 'The Crystal Retreat');
insert into accommodation (Service_id, Name) values (437, 'Crystal Stay');
insert into accommodation (Service_id, Name) values (438, 'Grand Chalet');
insert into accommodation (Service_id, Name) values (439, 'Grand Retreat');
insert into accommodation (Service_id, Name) values (440, 'Sunset Oasis Downtown');
insert into accommodation (Service_id, Name) values (441, 'Alpine Haven');
insert into accommodation (Service_id, Name) values (442, 'Golden House Mountain View');
insert into accommodation (Service_id, Name) values (443, 'Radisson Retreat Bayview');
insert into accommodation (Service_id, Name) values (444, 'Sunset Oasis Downtown');
insert into accommodation (Service_id, Name) values (445, 'Golden Chalet Luxury Club');
insert into accommodation (Service_id, Name) values (446, 'Golden Retreat');
insert into accommodation (Service_id, Name) values (447, 'Regency House Mountain View');
insert into accommodation (Service_id, Name) values (448, 'Ocean Inn Beachfront');
insert into accommodation (Service_id, Name) values (449, 'The Sunset Oasis');
insert into accommodation (Service_id, Name) values (450, 'Heritage Hotel by the Sea');
insert into accommodation (Service_id, Name) values (451, 'Crystal House');
insert into accommodation (Service_id, Name) values (452, 'Radisson Manor');
insert into accommodation (Service_id, Name) values (453, 'Regency Oasis Beachfront');
insert into accommodation (Service_id, Name) values (454, 'Plaza Villas');
insert into accommodation (Service_id, Name) values (455, 'The Serene Chalet');
insert into accommodation (Service_id, Name) values (456, 'Grand Retreat');
insert into accommodation (Service_id, Name) values (457, 'Grand Resort');
insert into accommodation (Service_id, Name) values (458, 'Sunset Retreat Downtown');
insert into accommodation (Service_id, Name) values (459, 'The Alpine Haven');
insert into accommodation (Service_id, Name) values (460, 'Heritage Villas');
insert into accommodation (Service_id, Name) values (461, 'The Alpine Haven');
insert into accommodation (Service_id, Name) values (462, 'Boutique Inn');
insert into accommodation (Service_id, Name) values (463, 'Plaza Villas');
insert into accommodation (Service_id, Name) values (464, 'Ocean Hotel');
insert into accommodation (Service_id, Name) values (465, 'Boutique Stay');
insert into accommodation (Service_id, Name) values (466, 'The Sunset Hideaway');
insert into accommodation (Service_id, Name) values (467, 'The Sunset Oasis');
insert into accommodation (Service_id, Name) values (468, 'Ocean Oasis');
insert into accommodation (Service_id, Name) values (469, 'Regency Suites Eco Lodge');
insert into accommodation (Service_id, Name) values (470, 'Golden Retreat Downtown');
insert into accommodation (Service_id, Name) values (471, 'Sunset Hideaway Spa & Wellness');
insert into accommodation (Service_id, Name) values (472, 'Grand Chalet');
insert into accommodation (Service_id, Name) values (473, 'Crystal House');
insert into accommodation (Service_id, Name) values (474, 'Sunset Hideaway Spa & Wellness');
insert into accommodation (Service_id, Name) values (475, 'Heritage Hotel by the Sea');
insert into accommodation (Service_id, Name) values (476, 'Alpine Palace Spa & Wellness');
insert into accommodation (Service_id, Name) values (477, 'The Alpine Hideaway');
insert into accommodation (Service_id, Name) values (478, 'Radisson Suites Mountain View');
insert into accommodation (Service_id, Name) values (479, 'The Regency Hotel');
insert into accommodation (Service_id, Name) values (480, 'Vista Stay Spa & Wellness');
insert into accommodation (Service_id, Name) values (481, 'Grand Resort');
insert into accommodation (Service_id, Name) values (482, 'Regency Retreat');
insert into accommodation (Service_id, Name) values (483, 'The Alpine House');
insert into accommodation (Service_id, Name) values (484, 'The Urban Gardens');
insert into accommodation (Service_id, Name) values (485, 'The Sunset Hideaway');
insert into accommodation (Service_id, Name) values (486, 'The Boutique Hideaway');
insert into accommodation (Service_id, Name) values (487, 'Urban Retreat');
insert into accommodation (Service_id, Name) values (488, 'Serene Oasis');
insert into accommodation (Service_id, Name) values (489, 'Boutique Chalet');
insert into accommodation (Service_id, Name) values (490, 'Grand Gardens');
insert into accommodation (Service_id, Name) values (491, 'Ocean Hotel');
insert into accommodation (Service_id, Name) values (492, 'Boutique Suites');
insert into accommodation (Service_id, Name) values (493, 'Heritage Villas');
insert into accommodation (Service_id, Name) values (494, 'The Golden Stay');
insert into accommodation (Service_id, Name) values (495, 'Boutique Villas Bayview');
insert into accommodation (Service_id, Name) values (496, 'Golden Stay Golf Resort');
insert into accommodation (Service_id, Name) values (497, 'Golden Retreat');
insert into accommodation (Service_id, Name) values (498, 'Plaza Chalet');
insert into accommodation (Service_id, Name) values (499, 'Regency Oasis Beachfront');
insert into accommodation (Service_id, Name) values (500, 'Serene Gardens Mountain View');
insert into accommodation (Service_id, Name) values (501, 'Boutique Chalet');
insert into accommodation (Service_id, Name) values (502, 'The Alpine Haven');
insert into accommodation (Service_id, Name) values (503, 'Boutique Resort Spa & Wellness');
insert into accommodation (Service_id, Name) values (504, 'Sunset Oasis Downtown');
insert into accommodation (Service_id, Name) values (505, 'The Golden Hideaway');
insert into accommodation (Service_id, Name) values (506, 'Plaza Stay');
insert into accommodation (Service_id, Name) values (507, 'The Radisson Lodge');
insert into accommodation (Service_id, Name) values (508, 'The Radisson Lodge');
insert into accommodation (Service_id, Name) values (509, 'The Heritage House');
insert into accommodation (Service_id, Name) values (510, 'The Regency Lodge');
insert into accommodation (Service_id, Name) values (511, 'The Alpine Haven');
insert into accommodation (Service_id, Name) values (512, 'Regency Oasis Beachfront');
insert into accommodation (Service_id, Name) values (513, 'Radisson Villas');
insert into accommodation (Service_id, Name) values (514, 'Boutique Suites');
insert into accommodation (Service_id, Name) values (515, 'The Vista Manor');
insert into accommodation (Service_id, Name) values (516, 'Alpine Haven');
insert into accommodation (Service_id, Name) values (517, 'The Urban Oasis');
insert into accommodation (Service_id, Name) values (518, 'The Alpine Oasis');
insert into accommodation (Service_id, Name) values (519, 'Golden House Mountain View');
insert into accommodation (Service_id, Name) values (520, 'Hilton Villas Mountain View');
insert into accommodation (Service_id, Name) values (521, 'Urban Retreat');
insert into accommodation (Service_id, Name) values (522, 'Golden Stay Golf Resort');
insert into accommodation (Service_id, Name) values (523, 'Ocean Retreat Downtown');
insert into accommodation (Service_id, Name) values (524, 'Plaza Stay');
insert into accommodation (Service_id, Name) values (525, 'The Heritage Villas');
insert into accommodation (Service_id, Name) values (526, 'Grand Chalet');
insert into accommodation (Service_id, Name) values (527, 'Regency Lodge');
insert into accommodation (Service_id, Name) values (528, 'Boutique Gardens Eco Lodge');
insert into accommodation (Service_id, Name) values (529, 'Crystal Suites Spa & Wellness');
insert into accommodation (Service_id, Name) values (530, 'Regency Retreat');
insert into accommodation (Service_id, Name) values (531, 'Ocean Oasis');
insert into accommodation (Service_id, Name) values (532, 'Regency Retreat');
insert into accommodation (Service_id, Name) values (533, 'The Hilton House');
insert into accommodation (Service_id, Name) values (534, 'Ocean Oasis');
insert into accommodation (Service_id, Name) values (535, 'The Boutique Hideaway');
insert into accommodation (Service_id, Name) values (536, 'The Royal Oasis');
insert into accommodation (Service_id, Name) values (537, 'Alpine Haven');
insert into accommodation (Service_id, Name) values (538, 'Vista Stay Spa & Wellness');
insert into accommodation (Service_id, Name) values (539, 'Golden Retreat Downtown');
insert into accommodation (Service_id, Name) values (540, 'Urban Manor Eco Lodge');
insert into accommodation (Service_id, Name) values (541, 'The Alpine Haven');
insert into accommodation (Service_id, Name) values (542, 'The Vista Manor');
insert into accommodation (Service_id, Name) values (543, 'The Alpine Haven');
insert into accommodation (Service_id, Name) values (544, 'The Serene Chalet');
insert into accommodation (Service_id, Name) values (545, 'Boutique Chalet');
insert into accommodation (Service_id, Name) values (546, 'Ocean Hotel');
insert into accommodation (Service_id, Name) values (547, 'The Sunset Oasis');
insert into accommodation (Service_id, Name) values (548, 'Regency Suites Eco Lodge');
insert into accommodation (Service_id, Name) values (549, 'The Hilton House');
insert into accommodation (Service_id, Name) values (550, 'The Alpine Haven');
insert into accommodation (Service_id, Name) values (551, 'Boutique Suites');
insert into accommodation (Service_id, Name) values (552, 'Boutique Resort Spa & Wellness');
insert into accommodation (Service_id, Name) values (553, 'Grand Retreat');
insert into accommodation (Service_id, Name) values (554, 'The Crystal Hideaway');
insert into accommodation (Service_id, Name) values (555, 'Regency House Mountain View');
insert into accommodation (Service_id, Name) values (556, 'Serene Oasis');
insert into accommodation (Service_id, Name) values (557, 'Boutique Gardens Eco Lodge');
insert into accommodation (Service_id, Name) values (558, 'The Serene Hideaway');
insert into accommodation (Service_id, Name) values (559, 'Ocean Hotel');
insert into accommodation (Service_id, Name) values (560, 'The Alpine House');
insert into accommodation (Service_id, Name) values (561, 'The Golden Stay');
insert into accommodation (Service_id, Name) values (562, 'The Ocean Manor');
insert into accommodation (Service_id, Name) values (563, 'Serene Oasis');
insert into accommodation (Service_id, Name) values (564, 'Regency House Mountain View');
insert into accommodation (Service_id, Name) values (565, 'Boutique Resort Spa & Wellness');
insert into accommodation (Service_id, Name) values (566, 'Ocean Oasis');
insert into accommodation (Service_id, Name) values (567, 'Urban Lodge by the Sea');
insert into accommodation (Service_id, Name) values (568, 'Regency Suites Eco Lodge');
insert into accommodation (Service_id, Name) values (569, 'The Hilton House');
insert into accommodation (Service_id, Name) values (570, 'Radisson Resort');
insert into accommodation (Service_id, Name) values (571, 'Boutique Suites');
insert into accommodation (Service_id, Name) values (572, 'Golden Manor');
insert into accommodation (Service_id, Name) values (573, 'The Vista Suites');
insert into accommodation (Service_id, Name) values (574, 'Serene Stay');
insert into accommodation (Service_id, Name) values (575, 'Boutique Resort Spa & Wellness');
insert into accommodation (Service_id, Name) values (576, 'Boutique Resort Spa & Wellness');
insert into accommodation (Service_id, Name) values (577, 'Ocean Inn Beachfront');
insert into accommodation (Service_id, Name) values (578, 'Golden Manor Luxury Club');
insert into accommodation (Service_id, Name) values (579, 'The Serene Chalet');
insert into accommodation (Service_id, Name) values (580, 'Sunset Hideaway Spa & Wellness');
insert into accommodation (Service_id, Name) values (581, 'The Heritage Villas');
insert into accommodation (Service_id, Name) values (582, 'Boutique Gardens Eco Lodge');
insert into accommodation (Service_id, Name) values (583, 'Golden Stay Golf Resort');
insert into accommodation (Service_id, Name) values (584, 'Alpine Suites');
insert into accommodation (Service_id, Name) values (585, 'The Heritage House');
insert into accommodation (Service_id, Name) values (586, 'Crystal Stay');
insert into accommodation (Service_id, Name) values (587, 'Royal Suites Riverside');
insert into accommodation (Service_id, Name) values (588, 'Regency House Mountain View');
insert into accommodation (Service_id, Name) values (589, 'Urban Retreat');
insert into accommodation (Service_id, Name) values (590, 'The Regency Inn');
insert into accommodation (Service_id, Name) values (591, 'The Alpine Haven');
insert into accommodation (Service_id, Name) values (592, 'Grand Resort');
insert into accommodation (Service_id, Name) values (593, 'Urban Manor Eco Lodge');
insert into accommodation (Service_id, Name) values (594, 'The Alpine Oasis');
insert into accommodation (Service_id, Name) values (595, 'Ocean Oasis');
insert into accommodation (Service_id, Name) values (596, 'The Alpine Lodge');
insert into accommodation (Service_id, Name) values (597, 'Grand Resort');
insert into accommodation (Service_id, Name) values (598, 'Ocean Retreat Downtown');
insert into accommodation (Service_id, Name) values (599, 'Serene Stay');
insert into accommodation (Service_id, Name) values (600, 'The Hilton House');
insert into accommodation (Service_id, Name) values (601, 'Crystal Stay');
insert into accommodation (Service_id, Name) values (602, 'Serene Gardens Mountain View');
insert into accommodation (Service_id, Name) values (603, 'Serene Oasis');
insert into accommodation (Service_id, Name) values (604, 'The Vista Suites');
insert into accommodation (Service_id, Name) values (605, 'Urban House by the Sea');
insert into accommodation (Service_id, Name) values (606, 'The Crystal Hideaway');
insert into accommodation (Service_id, Name) values (607, 'Crystal Hideaway');
insert into accommodation (Service_id, Name) values (608, 'Sunset Retreat Downtown');
insert into accommodation (Service_id, Name) values (609, 'The Alpine Haven');
insert into accommodation (Service_id, Name) values (610, 'Boutique Villas Bayview');
insert into accommodation (Service_id, Name) values (611, 'The Crystal Retreat');
insert into accommodation (Service_id, Name) values (612, 'Golden Manor Luxury Club');
insert into accommodation (Service_id, Name) values (613, 'The Urban Oasis');
insert into accommodation (Service_id, Name) values (614, 'Golden Manor Luxury Club');
insert into accommodation (Service_id, Name) values (615, 'Golden Chalet Luxury Club');
insert into accommodation (Service_id, Name) values (616, 'Crystal Hotel Golf Resort');
insert into accommodation (Service_id, Name) values (617, 'Grand Resort');
insert into accommodation (Service_id, Name) values (618, 'Vista Haven');
insert into accommodation (Service_id, Name) values (619, 'Alpine Suites');
insert into accommodation (Service_id, Name) values (620, 'The Alpine Haven');
insert into accommodation (Service_id, Name) values (621, 'Ocean Retreat Downtown');
insert into accommodation (Service_id, Name) values (622, 'Crystal House');
insert into accommodation (Service_id, Name) values (623, 'Heritage Stay Luxury Club');
insert into accommodation (Service_id, Name) values (624, 'The Alpine Haven');
insert into accommodation (Service_id, Name) values (625, 'Sunset Hideaway Spa & Wellness');
insert into accommodation (Service_id, Name) values (626, 'The Serene Chalet');
insert into accommodation (Service_id, Name) values (627, 'Heritage Villas');
insert into accommodation (Service_id, Name) values (628, 'Grand Resort');
insert into accommodation (Service_id, Name) values (629, 'The Regency Inn');
insert into accommodation (Service_id, Name) values (630, 'Royal Suites Riverside');
insert into accommodation (Service_id, Name) values (631, 'The Boutique Hideaway');
insert into accommodation (Service_id, Name) values (632, 'Alpine Palace Spa & Wellness');
insert into accommodation (Service_id, Name) values (633, 'Ocean Hotel');
insert into accommodation (Service_id, Name) values (634, 'Crystal House Beachfront');
insert into accommodation (Service_id, Name) values (635, 'Serene Stay');
insert into accommodation (Service_id, Name) values (636, 'The Urban Gardens');
insert into accommodation (Service_id, Name) values (637, 'Heritage Hotel Golf Resort');
insert into accommodation (Service_id, Name) values (638, 'The Ocean Manor');
insert into accommodation (Service_id, Name) values (639, 'Regency Oasis Beachfront');
insert into accommodation (Service_id, Name) values (640, 'The Regency Lodge');
insert into accommodation (Service_id, Name) values (641, 'Boutique Retreat');
insert into accommodation (Service_id, Name) values (642, 'The Vista Manor');
insert into accommodation (Service_id, Name) values (643, 'Urban Haven Beachfront');
insert into accommodation (Service_id, Name) values (644, 'Boutique Villas Bayview');
insert into accommodation (Service_id, Name) values (645, 'Heritage Stay Luxury Club');
insert into accommodation (Service_id, Name) values (646, 'Plaza Villas');
insert into accommodation (Service_id, Name) values (647, 'Golden Gardens');
insert into accommodation (Service_id, Name) values (648, 'Grand Chalet');
insert into accommodation (Service_id, Name) values (649, 'Boutique Suites');
insert into accommodation (Service_id, Name) values (650, 'Golden Chalet Luxury Club');
insert into accommodation (Service_id, Name) values (651, 'Golden Retreat');
insert into accommodation (Service_id, Name) values (652, 'Sunset Retreat Downtown');
insert into accommodation (Service_id, Name) values (653, 'The Ocean Manor');
insert into accommodation (Service_id, Name) values (654, 'Radisson Suites Mountain View');
insert into accommodation (Service_id, Name) values (655, 'The Crystal Hideaway');
insert into accommodation (Service_id, Name) values (656, 'The Regency Inn');
insert into accommodation (Service_id, Name) values (657, 'Sunset Oasis Downtown');
insert into accommodation (Service_id, Name) values (658, 'Serene Gardens Mountain View');
insert into accommodation (Service_id, Name) values (659, 'Crystal House Beachfront');
insert into accommodation (Service_id, Name) values (660, 'Ocean Oasis');
insert into accommodation (Service_id, Name) values (661, 'Sunset Hideaway Spa & Wellness');
insert into accommodation (Service_id, Name) values (662, 'Sunset Retreat Downtown');
insert into accommodation (Service_id, Name) values (663, 'Urban Haven Beachfront');
insert into accommodation (Service_id, Name) values (664, 'Royal Gardens Luxury Club');
insert into accommodation (Service_id, Name) values (665, 'Crystal House Beachfront');
insert into accommodation (Service_id, Name) values (666, 'Grand Chalet');
insert into accommodation (Service_id, Name) values (667, 'The Alpine House');
insert into accommodation (Service_id, Name) values (668, 'The Urban Gardens');
insert into accommodation (Service_id, Name) values (669, 'The Heritage House');
insert into accommodation (Service_id, Name) values (670, 'Serene Oasis');
insert into accommodation (Service_id, Name) values (671, 'Golden Retreat Downtown');
insert into accommodation (Service_id, Name) values (672, 'The Boutique Hideaway');
insert into accommodation (Service_id, Name) values (673, 'Radisson Stay');
insert into accommodation (Service_id, Name) values (674, 'Radisson Stay');
insert into accommodation (Service_id, Name) values (675, 'The Crystal Hideaway');
insert into accommodation (Service_id, Name) values (676, 'The Vista Suites');
insert into accommodation (Service_id, Name) values (677, 'Plaza Chalet');
insert into accommodation (Service_id, Name) values (678, 'The Crystal Retreat');
insert into accommodation (Service_id, Name) values (679, 'The Sunset Hideaway');
insert into accommodation (Service_id, Name) values (680, 'Regency Suites Eco Lodge');
insert into accommodation (Service_id, Name) values (681, 'Radisson Manor');
insert into accommodation (Service_id, Name) values (682, 'Sunset Retreat Downtown');
insert into accommodation (Service_id, Name) values (683, 'The Urban Oasis');
insert into accommodation (Service_id, Name) values (684, 'Ocean Inn Beachfront');
insert into accommodation (Service_id, Name) values (685, 'The Plaza Palace');
insert into accommodation (Service_id, Name) values (686, 'Serene Oasis');
insert into accommodation (Service_id, Name) values (687, 'Serene Oasis');
insert into accommodation (Service_id, Name) values (688, 'Golden Stay Golf Resort');
insert into accommodation (Service_id, Name) values (689, 'Regency House Mountain View');
insert into accommodation (Service_id, Name) values (690, 'Plaza Stay');
insert into accommodation (Service_id, Name) values (691, 'Grand Resort');
insert into accommodation (Service_id, Name) values (692, 'Crystal Hotel Golf Resort');
insert into accommodation (Service_id, Name) values (693, 'Heritage Lodge');
insert into accommodation (Service_id, Name) values (694, 'Golden Stay Golf Resort');
insert into accommodation (Service_id, Name) values (695, 'Urban Manor Eco Lodge');
insert into accommodation (Service_id, Name) values (696, 'Urban Lodge by the Sea');
insert into accommodation (Service_id, Name) values (697, 'The Regency Hotel');
insert into accommodation (Service_id, Name) values (698, 'Heritage Lodge');
insert into accommodation (Service_id, Name) values (699, 'Plaza Villas');
insert into accommodation (Service_id, Name) values (700, 'Boutique Villas Bayview');
insert into accommodation (Service_id, Name) values (701, 'The Golden Hideaway');
insert into accommodation (Service_id, Name) values (702, 'Crystal House');
insert into accommodation (Service_id, Name) values (703, 'Golden Gardens');
insert into accommodation (Service_id, Name) values (704, 'Plaza Villas');
insert into accommodation (Service_id, Name) values (705, 'The Vista Manor');
insert into accommodation (Service_id, Name) values (706, 'The Hilton Hideaway');
insert into accommodation (Service_id, Name) values (707, 'Heritage Hotel by the Sea');
insert into accommodation (Service_id, Name) values (708, 'Grand Retreat');
insert into accommodation (Service_id, Name) values (709, 'The Heritage House');
insert into accommodation (Service_id, Name) values (710, 'Radisson Suites Mountain View');
insert into accommodation (Service_id, Name) values (711, 'The Hilton House');
insert into accommodation (Service_id, Name) values (712, 'Boutique Inn');
insert into accommodation (Service_id, Name) values (713, 'Boutique Villas Bayview');
insert into accommodation (Service_id, Name) values (714, 'Radisson Manor');
insert into accommodation (Service_id, Name) values (715, 'Grand Chalet');
insert into accommodation (Service_id, Name) values (716, 'Boutique Retreat');
insert into accommodation (Service_id, Name) values (717, 'Crystal House');
insert into accommodation (Service_id, Name) values (718, 'Regency Retreat');
insert into accommodation (Service_id, Name) values (719, 'Grand Retreat');
insert into accommodation (Service_id, Name) values (720, 'Urban Retreat');
insert into accommodation (Service_id, Name) values (721, 'The Heritage House');
insert into accommodation (Service_id, Name) values (722, 'Heritage Stay Luxury Club');
insert into accommodation (Service_id, Name) values (723, 'The Alpine Oasis');
insert into accommodation (Service_id, Name) values (724, 'Grand Resort');
insert into accommodation (Service_id, Name) values (725, 'Regency House Mountain View');
insert into accommodation (Service_id, Name) values (726, 'The Vista Suites');
insert into accommodation (Service_id, Name) values (727, 'Regency Oasis Beachfront');
insert into accommodation (Service_id, Name) values (728, 'Golden Stay Golf Resort');
insert into accommodation (Service_id, Name) values (729, 'Regency Retreat');
insert into accommodation (Service_id, Name) values (730, 'Radisson Suites Mountain View');
insert into accommodation (Service_id, Name) values (731, 'The Serene Chalet');
insert into accommodation (Service_id, Name) values (732, 'Boutique Resort Spa & Wellness');
insert into accommodation (Service_id, Name) values (733, 'Radisson Retreat Bayview');
insert into accommodation (Service_id, Name) values (734, 'Boutique Villas Bayview');
insert into accommodation (Service_id, Name) values (735, 'Serene Gardens Mountain View');
insert into accommodation (Service_id, Name) values (736, 'Urban Lodge by the Sea');
insert into accommodation (Service_id, Name) values (737, 'The Golden Hideaway');
insert into accommodation (Service_id, Name) values (738, 'Boutique Suites');
insert into accommodation (Service_id, Name) values (739, 'The Alpine Hideaway');
insert into accommodation (Service_id, Name) values (740, 'Regency Suites Eco Lodge');
insert into accommodation (Service_id, Name) values (741, 'Grand Hideaway Riverside');
insert into accommodation (Service_id, Name) values (742, 'Regency Oasis Beachfront');
insert into accommodation (Service_id, Name) values (743, 'The Regency Inn');
insert into accommodation (Service_id, Name) values (744, 'Heritage Villas');
insert into accommodation (Service_id, Name) values (745, 'The Serene Hideaway');
insert into accommodation (Service_id, Name) values (746, 'Serene Gardens Mountain View');
insert into accommodation (Service_id, Name) values (747, 'The Regency Inn');
insert into accommodation (Service_id, Name) values (748, 'Boutique Inn');
insert into accommodation (Service_id, Name) values (749, 'Heritage Stay Luxury Club');
insert into accommodation (Service_id, Name) values (750, 'Urban Lodge by the Sea');
insert into accommodation (Service_id, Name) values (751, 'Radisson Suites Mountain View');
insert into accommodation (Service_id, Name) values (752, 'Heritage Hotel Golf Resort');
insert into accommodation (Service_id, Name) values (753, 'Alpine Haven');
insert into accommodation (Service_id, Name) values (754, 'The Alpine Hideaway');
insert into accommodation (Service_id, Name) values (755, 'Radisson Resort');
insert into accommodation (Service_id, Name) values (756, 'Grand Retreat');
insert into accommodation (Service_id, Name) values (757, 'Royal Gardens Luxury Club');
insert into accommodation (Service_id, Name) values (758, 'Royal Suites Riverside');
insert into accommodation (Service_id, Name) values (759, 'The Sunset Oasis');
insert into accommodation (Service_id, Name) values (760, 'The Heritage House');
insert into accommodation (Service_id, Name) values (761, 'Plaza Stay');
insert into accommodation (Service_id, Name) values (762, 'Alpine Palace Spa & Wellness');
insert into accommodation (Service_id, Name) values (763, 'Boutique Inn');
insert into accommodation (Service_id, Name) values (764, 'Alpine Palace Spa & Wellness');
insert into accommodation (Service_id, Name) values (765, 'Golden Inn Spa & Wellness');
insert into accommodation (Service_id, Name) values (766, 'Boutique Retreat');
insert into accommodation (Service_id, Name) values (767, 'Boutique Suites');
insert into accommodation (Service_id, Name) values (768, 'Boutique Villas Bayview');
insert into accommodation (Service_id, Name) values (769, 'The Crystal Retreat');
insert into accommodation (Service_id, Name) values (770, 'Golden Manor Luxury Club');
insert into accommodation (Service_id, Name) values (771, 'The Sunset Hideaway');
insert into accommodation (Service_id, Name) values (772, 'Radisson Resort');
insert into accommodation (Service_id, Name) values (773, 'Urban Manor Eco Lodge');
insert into accommodation (Service_id, Name) values (774, 'Golden Inn Spa & Wellness');
insert into accommodation (Service_id, Name) values (775, 'The Alpine Oasis');
insert into accommodation (Service_id, Name) values (776, 'Urban Haven Beachfront');
insert into accommodation (Service_id, Name) values (777, 'Royal Gardens Luxury Club');
insert into accommodation (Service_id, Name) values (778, 'The Crystal Hideaway');
insert into accommodation (Service_id, Name) values (779, 'Urban Haven Beachfront');
insert into accommodation (Service_id, Name) values (780, 'The Urban Gardens');
insert into accommodation (Service_id, Name) values (781, 'The Heritage House');
insert into accommodation (Service_id, Name) values (782, 'Heritage Stay Luxury Club');
insert into accommodation (Service_id, Name) values (783, 'Crystal House Beachfront');
insert into accommodation (Service_id, Name) values (784, 'Crystal House');
insert into accommodation (Service_id, Name) values (785, 'Ocean Oasis');
insert into accommodation (Service_id, Name) values (786, 'Ocean Oasis');
insert into accommodation (Service_id, Name) values (787, 'Radisson Retreat Bayview');
insert into accommodation (Service_id, Name) values (788, 'Boutique Stay');
insert into accommodation (Service_id, Name) values (789, 'Grand Hideaway Riverside');
insert into accommodation (Service_id, Name) values (790, 'Boutique Gardens Eco Lodge');
insert into accommodation (Service_id, Name) values (791, 'Grand Chalet');
insert into accommodation (Service_id, Name) values (792, 'Crystal Stay');
insert into accommodation (Service_id, Name) values (793, 'Serene Stay');
insert into accommodation (Service_id, Name) values (794, 'The Boutique Hideaway');
insert into accommodation (Service_id, Name) values (795, 'Crystal House Beachfront');
insert into accommodation (Service_id, Name) values (796, 'The Golden Hideaway');
insert into accommodation (Service_id, Name) values (797, 'The Alpine Hideaway');
insert into accommodation (Service_id, Name) values (798, 'Plaza Stay');
insert into accommodation (Service_id, Name) values (799, 'Boutique Lodge Downtown');
insert into accommodation (Service_id, Name) values (800, 'Vista Haven');
insert into accommodation (Service_id, Name) values (801, 'Radisson Resort');
insert into accommodation (Service_id, Name) values (802, 'Golden House Mountain View');
insert into accommodation (Service_id, Name) values (803, 'Alpine Palace Spa & Wellness');
insert into accommodation (Service_id, Name) values (804, 'Hilton Villas Mountain View');
insert into accommodation (Service_id, Name) values (805, 'The Royal Oasis');
insert into accommodation (Service_id, Name) values (806, 'The Boutique Hideaway');
insert into accommodation (Service_id, Name) values (807, 'Regency Oasis Beachfront');
insert into accommodation (Service_id, Name) values (808, 'The Hilton House');
insert into accommodation (Service_id, Name) values (809, 'Boutique Resort Spa & Wellness');
insert into accommodation (Service_id, Name) values (810, 'The Regency Hotel');
insert into accommodation (Service_id, Name) values (811, 'Golden Gardens');
insert into accommodation (Service_id, Name) values (812, 'Urban House by the Sea');
insert into accommodation (Service_id, Name) values (813, 'Royal Suites Riverside');
insert into accommodation (Service_id, Name) values (814, 'Alpine Haven');
insert into accommodation (Service_id, Name) values (815, 'The Hilton Hideaway');
insert into accommodation (Service_id, Name) values (816, 'Boutique Chalet');
insert into accommodation (Service_id, Name) values (817, 'Vista Stay Spa & Wellness');
insert into accommodation (Service_id, Name) values (818, 'The Sunset Oasis');
insert into accommodation (Service_id, Name) values (819, 'Golden Manor');
insert into accommodation (Service_id, Name) values (820, 'Grand Retreat');
insert into accommodation (Service_id, Name) values (821, 'The Hilton House');
insert into accommodation (Service_id, Name) values (822, 'The Crystal Hideaway');
insert into accommodation (Service_id, Name) values (823, 'Ocean Hotel');
insert into accommodation (Service_id, Name) values (824, 'The Radisson Lodge');
insert into accommodation (Service_id, Name) values (825, 'Regency Suites Eco Lodge');
insert into accommodation (Service_id, Name) values (826, 'The Golden Hideaway');
insert into accommodation (Service_id, Name) values (827, 'Sunset Oasis Downtown');
insert into accommodation (Service_id, Name) values (828, 'Grand Gardens');
insert into accommodation (Service_id, Name) values (829, 'The Boutique Hideaway');
insert into accommodation (Service_id, Name) values (830, 'Sunset Retreat Downtown');
insert into accommodation (Service_id, Name) values (831, 'The Crystal Hideaway');
insert into accommodation (Service_id, Name) values (832, 'Golden Chalet Luxury Club');
insert into accommodation (Service_id, Name) values (833, 'Heritage Lodge');
insert into accommodation (Service_id, Name) values (834, 'Crystal Stay');
insert into accommodation (Service_id, Name) values (835, 'Heritage Villas');
insert into accommodation (Service_id, Name) values (836, 'The Hilton House');
insert into accommodation (Service_id, Name) values (837, 'The Heritage Villas');
insert into accommodation (Service_id, Name) values (838, 'Radisson Retreat Bayview');
insert into accommodation (Service_id, Name) values (839, 'Regency Retreat');
insert into accommodation (Service_id, Name) values (840, 'Crystal Hideaway');
insert into accommodation (Service_id, Name) values (841, 'Crystal House');
insert into accommodation (Service_id, Name) values (842, 'Boutique Villas Bayview');
insert into accommodation (Service_id, Name) values (843, 'Regency Retreat');
insert into accommodation (Service_id, Name) values (844, 'Serene Gardens Mountain View');
insert into accommodation (Service_id, Name) values (845, 'Golden Retreat');
insert into accommodation (Service_id, Name) values (846, 'Heritage Stay Luxury Club');
insert into accommodation (Service_id, Name) values (847, 'The Heritage House');
insert into accommodation (Service_id, Name) values (848, 'Heritage Hotel by the Sea');
insert into accommodation (Service_id, Name) values (849, 'Boutique Suites');
insert into accommodation (Service_id, Name) values (850, 'The Ocean Manor');
insert into accommodation (Service_id, Name) values (851, 'Sunset Oasis Downtown');
insert into accommodation (Service_id, Name) values (852, 'Boutique Villas Bayview');
insert into accommodation (Service_id, Name) values (853, 'The Heritage Villas');
insert into accommodation (Service_id, Name) values (854, 'Boutique Inn');
insert into accommodation (Service_id, Name) values (855, 'The Ocean Manor');
insert into accommodation (Service_id, Name) values (856, 'Hilton Villas Mountain View');
insert into accommodation (Service_id, Name) values (857, 'Grand Retreat');
insert into accommodation (Service_id, Name) values (858, 'Alpine Haven');
insert into accommodation (Service_id, Name) values (859, 'Ocean Hotel');
insert into accommodation (Service_id, Name) values (860, 'Vista Haven');
insert into accommodation (Service_id, Name) values (861, 'Sunset Retreat Downtown');
insert into accommodation (Service_id, Name) values (862, 'The Heritage Villas');
insert into accommodation (Service_id, Name) values (863, 'The Serene Hideaway');
insert into accommodation (Service_id, Name) values (864, 'Golden House Mountain View');
insert into accommodation (Service_id, Name) values (865, 'The Alpine Hideaway');
insert into accommodation (Service_id, Name) values (866, 'Crystal House');
insert into accommodation (Service_id, Name) values (867, 'Grand Retreat');
insert into accommodation (Service_id, Name) values (868, 'Heritage Villas');
insert into accommodation (Service_id, Name) values (869, 'Grand Hideaway Riverside');
insert into accommodation (Service_id, Name) values (870, 'The Alpine Haven');
insert into accommodation (Service_id, Name) values (871, 'Vista Stay Spa & Wellness');
insert into accommodation (Service_id, Name) values (872, 'Ocean Inn Beachfront');
insert into accommodation (Service_id, Name) values (873, 'Boutique Chalet');
insert into accommodation (Service_id, Name) values (874, 'Urban Haven Beachfront');
insert into accommodation (Service_id, Name) values (875, 'Serene Gardens Mountain View');
insert into accommodation (Service_id, Name) values (876, 'The Alpine House');
insert into accommodation (Service_id, Name) values (877, 'Heritage Hotel by the Sea');
insert into accommodation (Service_id, Name) values (878, 'Ocean Hotel');
insert into accommodation (Service_id, Name) values (879, 'Grand Chalet');
insert into accommodation (Service_id, Name) values (880, 'Alpine Suites');
insert into accommodation (Service_id, Name) values (881, 'Grand Retreat');
insert into accommodation (Service_id, Name) values (882, 'Boutique Retreat');
insert into accommodation (Service_id, Name) values (883, 'The Serene Chalet');
insert into accommodation (Service_id, Name) values (884, 'Urban House by the Sea');
insert into accommodation (Service_id, Name) values (885, 'Regency Oasis Beachfront');
insert into accommodation (Service_id, Name) values (886, 'Urban Retreat');
insert into accommodation (Service_id, Name) values (887, 'The Crystal Hideaway');
insert into accommodation (Service_id, Name) values (888, 'Radisson Resort');
insert into accommodation (Service_id, Name) values (889, 'The Crystal Retreat');
insert into accommodation (Service_id, Name) values (890, 'Boutique Chalet');
insert into accommodation (Service_id, Name) values (891, 'Royal Gardens Luxury Club');
insert into accommodation (Service_id, Name) values (892, 'The Alpine Oasis');
insert into accommodation (Service_id, Name) values (893, 'The Urban Gardens');
insert into accommodation (Service_id, Name) values (894, 'Boutique Inn');
insert into accommodation (Service_id, Name) values (895, 'Golden Inn Spa & Wellness');
insert into accommodation (Service_id, Name) values (896, 'Crystal House');
insert into accommodation (Service_id, Name) values (897, 'The Sunset Oasis');
insert into accommodation (Service_id, Name) values (898, 'Urban Manor Eco Lodge');
insert into accommodation (Service_id, Name) values (899, 'Sunset Hideaway Spa & Wellness');
insert into accommodation (Service_id, Name) values (900, 'The Crystal Hideaway');
insert into accommodation (Service_id, Name) values (901, 'Ocean Hotel');
insert into accommodation (Service_id, Name) values (902, 'Boutique Retreat');
insert into accommodation (Service_id, Name) values (903, 'The Urban Oasis');
insert into accommodation (Service_id, Name) values (904, 'Grand Hideaway Riverside');
insert into accommodation (Service_id, Name) values (905, 'Sunset Oasis Downtown');
insert into accommodation (Service_id, Name) values (906, 'The Serene Chalet');
insert into accommodation (Service_id, Name) values (907, 'Golden Retreat Downtown');
insert into accommodation (Service_id, Name) values (908, 'The Sunset Oasis');
insert into accommodation (Service_id, Name) values (909, 'The Ocean Manor');
insert into accommodation (Service_id, Name) values (910, 'The Sunset Hideaway');
insert into accommodation (Service_id, Name) values (911, 'Vista Stay Spa & Wellness');
insert into accommodation (Service_id, Name) values (912, 'Radisson Stay');
insert into accommodation (Service_id, Name) values (913, 'Ocean Oasis');
insert into accommodation (Service_id, Name) values (914, 'Radisson Suites Mountain View');
insert into accommodation (Service_id, Name) values (915, 'The Urban Gardens');
insert into accommodation (Service_id, Name) values (916, 'Urban Lodge by the Sea');
insert into accommodation (Service_id, Name) values (917, 'Grand Chalet');
insert into accommodation (Service_id, Name) values (918, 'Regency Retreat');
insert into accommodation (Service_id, Name) values (919, 'The Serene Chalet');
insert into accommodation (Service_id, Name) values (920, 'Ocean Hotel');
insert into accommodation (Service_id, Name) values (921, 'Boutique Suites');
insert into accommodation (Service_id, Name) values (922, 'Regency Retreat');
insert into accommodation (Service_id, Name) values (923, 'Serene Gardens Mountain View');
insert into accommodation (Service_id, Name) values (924, 'Golden Manor Luxury Club');
insert into accommodation (Service_id, Name) values (925, 'Golden Retreat Downtown');
insert into accommodation (Service_id, Name) values (926, 'Urban Manor Eco Lodge');
insert into accommodation (Service_id, Name) values (927, 'Heritage Stay Luxury Club');
insert into accommodation (Service_id, Name) values (928, 'Crystal House');
insert into accommodation (Service_id, Name) values (929, 'Plaza Villas');
insert into accommodation (Service_id, Name) values (930, 'Ocean Retreat Downtown');
insert into accommodation (Service_id, Name) values (931, 'Heritage Stay Luxury Club');
insert into accommodation (Service_id, Name) values (932, 'The Alpine Oasis');
insert into accommodation (Service_id, Name) values (933, 'Boutique Suites');
insert into accommodation (Service_id, Name) values (934, 'Boutique Chalet');
insert into accommodation (Service_id, Name) values (935, 'Hilton Villas Mountain View');
insert into accommodation (Service_id, Name) values (936, 'The Radisson Lodge');
insert into accommodation (Service_id, Name) values (937, 'Golden Stay Golf Resort');
insert into accommodation (Service_id, Name) values (938, 'Urban House by the Sea');
insert into accommodation (Service_id, Name) values (939, 'Heritage Hotel Golf Resort');
insert into accommodation (Service_id, Name) values (940, 'Regency Suites Eco Lodge');
insert into accommodation (Service_id, Name) values (941, 'Urban Lodge by the Sea');
insert into accommodation (Service_id, Name) values (942, 'The Sunset Hideaway');
insert into accommodation (Service_id, Name) values (943, 'Boutique Villas Bayview');
insert into accommodation (Service_id, Name) values (944, 'Ocean Inn Beachfront');
insert into accommodation (Service_id, Name) values (945, 'Alpine Haven');
insert into accommodation (Service_id, Name) values (946, 'Heritage Hotel Golf Resort');
insert into accommodation (Service_id, Name) values (947, 'Sunset Retreat Downtown');
insert into accommodation (Service_id, Name) values (948, 'The Crystal Hideaway');
insert into accommodation (Service_id, Name) values (949, 'Alpine Palace Spa & Wellness');
insert into accommodation (Service_id, Name) values (950, 'The Golden Stay');
insert into accommodation (Service_id, Name) values (951, 'Radisson Stay');
insert into accommodation (Service_id, Name) values (952, 'The Sunset Oasis');
insert into accommodation (Service_id, Name) values (953, 'Serene Oasis');
insert into accommodation (Service_id, Name) values (954, 'Heritage Hotel by the Sea');
insert into accommodation (Service_id, Name) values (955, 'Heritage Hotel Golf Resort');
insert into accommodation (Service_id, Name) values (956, 'The Urban Gardens');
insert into accommodation (Service_id, Name) values (957, 'The Hilton Hideaway');
insert into accommodation (Service_id, Name) values (958, 'Plaza Villas');
insert into accommodation (Service_id, Name) values (959, 'Vista Haven');
insert into accommodation (Service_id, Name) values (960, 'Boutique Suites');
insert into accommodation (Service_id, Name) values (961, 'Serene Gardens Mountain View');
insert into accommodation (Service_id, Name) values (962, 'Plaza Chalet');
insert into accommodation (Service_id, Name) values (963, 'Boutique Retreat');
insert into accommodation (Service_id, Name) values (964, 'The Hilton Hideaway');
insert into accommodation (Service_id, Name) values (965, 'Vista Stay Spa & Wellness');
insert into accommodation (Service_id, Name) values (966, 'Radisson Stay');
insert into accommodation (Service_id, Name) values (967, 'Boutique Retreat');
insert into accommodation (Service_id, Name) values (968, 'Boutique Stay');
insert into accommodation (Service_id, Name) values (969, 'Urban Haven Beachfront');
insert into accommodation (Service_id, Name) values (970, 'Urban Lodge by the Sea');
insert into accommodation (Service_id, Name) values (971, 'Heritage Lodge');
insert into accommodation (Service_id, Name) values (972, 'The Sunset Oasis');
insert into accommodation (Service_id, Name) values (973, 'Boutique Resort Spa & Wellness');
insert into accommodation (Service_id, Name) values (974, 'Ocean Retreat Downtown');
insert into accommodation (Service_id, Name) values (975, 'Golden House Mountain View');
insert into accommodation (Service_id, Name) values (976, 'The Urban Oasis');
insert into accommodation (Service_id, Name) values (977, 'The Radisson Lodge');
insert into accommodation (Service_id, Name) values (978, 'Grand Gardens');
insert into accommodation (Service_id, Name) values (979, 'The Golden Stay');
insert into accommodation (Service_id, Name) values (980, 'Ocean Oasis');
insert into accommodation (Service_id, Name) values (981, 'Heritage Hotel by the Sea');
insert into accommodation (Service_id, Name) values (982, 'The Radisson Lodge');
insert into accommodation (Service_id, Name) values (983, 'Heritage Villas');
insert into accommodation (Service_id, Name) values (984, 'Heritage Hotel Golf Resort');
insert into accommodation (Service_id, Name) values (985, 'The Heritage Villas');
insert into accommodation (Service_id, Name) values (986, 'Radisson Stay');
insert into accommodation (Service_id, Name) values (987, 'The Sunset Oasis');
insert into accommodation (Service_id, Name) values (988, 'Boutique Inn');
insert into accommodation (Service_id, Name) values (989, 'Golden House Mountain View');
insert into accommodation (Service_id, Name) values (990, 'Alpine Suites');
insert into accommodation (Service_id, Name) values (991, 'The Serene Chalet');
insert into accommodation (Service_id, Name) values (992, 'Alpine Suites');
insert into accommodation (Service_id, Name) values (993, 'Serene Gardens Mountain View');
insert into accommodation (Service_id, Name) values (994, 'The Serene Hideaway');
insert into accommodation (Service_id, Name) values (995, 'The Regency Inn');
insert into accommodation (Service_id, Name) values (996, 'Boutique Resort Spa & Wellness');
insert into accommodation (Service_id, Name) values (997, 'Grand Resort');
insert into accommodation (Service_id, Name) values (998, 'The Urban Oasis');
insert into accommodation (Service_id, Name) values (999, 'Radisson Retreat Bayview');
insert into accommodation (Service_id, Name) values (1000, 'Vista Stay Spa & Wellness');
