insert into attraction (Service_id, Name) values (3, 'Universal Studios Hollywood');
insert into attraction (Service_id, Name) values (4, 'Hong Kong Disneyland');
insert into attraction (Service_id, Name) values (8, 'Kinkaku-ji (Golden Pavilion)');
insert into attraction (Service_id, Name) values (13, 'Forbidden City');
insert into attraction (Service_id, Name) values (26, 'Gyeongbokgung Palace');
insert into attraction (Service_id, Name) values (27, 'Guell Park');
insert into attraction (Service_id, Name) values (28, 'Sheikh Zayed Grand Mosque');
insert into attraction (Service_id, Name) values (31, 'Colosseum');
insert into attraction (Service_id, Name) values (38, 'Blue Lagoon Iceland');
insert into attraction (Service_id, Name) values (40, 'Forbidden City');
insert into attraction (Service_id, Name) values (45, 'Petra');
insert into attraction (Service_id, Name) values (52, 'Sydney Opera House');
insert into attraction (Service_id, Name) values (53, 'Ibiza Beaches');
insert into attraction (Service_id, Name) values (63, 'Wadi Rum Desert');
insert into attraction (Service_id, Name) values (64, 'Christ the Redeemer');
insert into attraction (Service_id, Name) values (65, 'Sugarloaf Mountain');
insert into attraction (Service_id, Name) values (69, 'Machu Picchu');
insert into attraction (Service_id, Name) values (90, 'Notre-Dame Cathedral');
insert into attraction (Service_id, Name) values (95, 'Teotihuacan Pyramids');
insert into attraction (Service_id, Name) values (105, 'Ha Long Bay');
insert into attraction (Service_id, Name) values (107, 'Chichen Itza');
insert into attraction (Service_id, Name) values (109, 'Kruger National Park');
insert into attraction (Service_id, Name) values (110, 'Tulum Ruins');
insert into attraction (Service_id, Name) values (112, 'Santorini Caldera');
insert into attraction (Service_id, Name) values (118, 'Ibiza Beaches');
insert into attraction (Service_id, Name) values (119, 'Yellowstone National Park');
insert into attraction (Service_id, Name) values (126, 'St. Peter''s Basilica');
insert into attraction (Service_id, Name) values (141, 'Berlin Wall Memorial');
insert into attraction (Service_id, Name) values (143, 'Space Needle');
insert into attraction (Service_id, Name) values (145, 'Sagrada Familia');
insert into attraction (Service_id, Name) values (146, 'Sydney Opera House');
insert into attraction (Service_id, Name) values (179, 'Petra Treasury');
insert into attraction (Service_id, Name) values (182, 'Wadi Rum Desert');
insert into attraction (Service_id, Name) values (195, 'Iguazu Falls');
insert into attraction (Service_id, Name) values (196, 'Mount Kilimanjaro');
insert into attraction (Service_id, Name) values (201, 'Ha Long Bay');
insert into attraction (Service_id, Name) values (206, 'Van Gogh Museum');
insert into attraction (Service_id, Name) values (207, 'Notre-Dame Cathedral');
insert into attraction (Service_id, Name) values (209, 'Times Square');
insert into attraction (Service_id, Name) values (214, 'Keukenhof Gardens');
insert into attraction (Service_id, Name) values (227, 'Ha Long Bay');
insert into attraction (Service_id, Name) values (230, 'Big Ben');
insert into attraction (Service_id, Name) values (232, 'Jeita Grotto');
insert into attraction (Service_id, Name) values (235, 'Sagrada Familia');
insert into attraction (Service_id, Name) values (236, 'Victoria Falls');
insert into attraction (Service_id, Name) values (242, 'Vatican Museums');
insert into attraction (Service_id, Name) values (244, 'Taj Mahal');
insert into attraction (Service_id, Name) values (249, 'Brandenburg Gate');
insert into attraction (Service_id, Name) values (252, 'Taj Mahal');
insert into attraction (Service_id, Name) values (256, 'Petra');
insert into attraction (Service_id, Name) values (271, 'Burj Al Arab');
insert into attraction (Service_id, Name) values (282, 'Loch Ness');
insert into attraction (Service_id, Name) values (287, 'Great Wall of China');
insert into attraction (Service_id, Name) values (288, 'Hobbiton Movie Set');
insert into attraction (Service_id, Name) values (291, 'Space Needle');
insert into attraction (Service_id, Name) values (293, 'Sheikh Zayed Grand Mosque');
insert into attraction (Service_id, Name) values (294, 'Space Needle');
insert into attraction (Service_id, Name) values (298, 'Western Wall');
insert into attraction (Service_id, Name) values (300, 'Havana Viejo');
insert into attraction (Service_id, Name) values (304, 'Golden Gate Bridge');
insert into attraction (Service_id, Name) values (308, 'Trevi Fountain');
insert into attraction (Service_id, Name) values (310, 'Bora Bora Lagoon');
insert into attraction (Service_id, Name) values (314, 'Amalfi Coast');
insert into attraction (Service_id, Name) values (317, 'Space Needle');
insert into attraction (Service_id, Name) values (318, 'Kruger National Park');
insert into attraction (Service_id, Name) values (324, 'Dead Sea');
insert into attraction (Service_id, Name) values (330, 'Vatican Museums');
insert into attraction (Service_id, Name) values (348, 'Louvre Museum');
insert into attraction (Service_id, Name) values (349, 'Yosemite Valley');
insert into attraction (Service_id, Name) values (359, 'Eiffel Tower');
insert into attraction (Service_id, Name) values (366, 'Mount Kilimanjaro');
insert into attraction (Service_id, Name) values (374, 'Angkor Wat');
insert into attraction (Service_id, Name) values (375, 'Blue Lagoon Iceland');
insert into attraction (Service_id, Name) values (381, 'Gyeongbokgung Palace');
insert into attraction (Service_id, Name) values (385, 'Petra');
insert into attraction (Service_id, Name) values (386, 'Golden Gate Bridge');
insert into attraction (Service_id, Name) values (390, 'Sagrada Familia');
insert into attraction (Service_id, Name) values (392, 'Ha Long Bay');
insert into attraction (Service_id, Name) values (406, 'Acropolis of Athens');
insert into attraction (Service_id, Name) values (407, 'Sagrada Familia');
insert into attraction (Service_id, Name) values (408, 'Ha Long Bay');
insert into attraction (Service_id, Name) values (412, 'Sugarloaf Mountain');
insert into attraction (Service_id, Name) values (414, 'Ha Long Bay');
insert into attraction (Service_id, Name) values (415, 'Rijksmuseum');
insert into attraction (Service_id, Name) values (417, 'Amalfi Coast');
insert into attraction (Service_id, Name) values (426, 'Universal Studios Hollywood');
insert into attraction (Service_id, Name) values (427, 'Santorini Caldera');
insert into attraction (Service_id, Name) values (428, 'Acropolis of Athens');
insert into attraction (Service_id, Name) values (432, 'Cliffs of Moher');
insert into attraction (Service_id, Name) values (437, 'Teotihuacan Pyramids');
insert into attraction (Service_id, Name) values (456, 'Petra');
insert into attraction (Service_id, Name) values (464, 'Pamukkale Thermal Pools');
insert into attraction (Service_id, Name) values (469, 'Forbidden City');
insert into attraction (Service_id, Name) values (476, 'Tulum Ruins');
insert into attraction (Service_id, Name) values (483, 'Dead Sea');
insert into attraction (Service_id, Name) values (485, 'Santorini Caldera');
insert into attraction (Service_id, Name) values (486, 'Loch Ness');
insert into attraction (Service_id, Name) values (495, 'Petra Treasury');
insert into attraction (Service_id, Name) values (499, 'Capadocia Fairy Chimneys');
insert into attraction (Service_id, Name) values (501, 'The Bund');
insert into attraction (Service_id, Name) values (506, 'Kruger National Park');
insert into attraction (Service_id, Name) values (519, 'Teotihuacan Pyramids');
insert into attraction (Service_id, Name) values (530, 'Neuschwanstein Castle');
insert into attraction (Service_id, Name) values (531, 'Sheikh Zayed Grand Mosque');
insert into attraction (Service_id, Name) values (534, 'The Bund');
insert into attraction (Service_id, Name) values (541, 'Gyeongbokgung Palace');
insert into attraction (Service_id, Name) values (543, 'Disneyland Park');
insert into attraction (Service_id, Name) values (550, 'Golden Gate Bridge');
insert into attraction (Service_id, Name) values (559, 'Bora Bora Lagoon');
insert into attraction (Service_id, Name) values (561, 'Vatican Museums');
insert into attraction (Service_id, Name) values (566, 'Petra Treasury');
insert into attraction (Service_id, Name) values (568, 'Blue Lagoon Iceland');
insert into attraction (Service_id, Name) values (572, 'Colosseum');
insert into attraction (Service_id, Name) values (583, 'Yosemite Valley');
insert into attraction (Service_id, Name) values (591, 'Louvre Museum');
insert into attraction (Service_id, Name) values (593, 'Hobbiton Movie Set');
insert into attraction (Service_id, Name) values (598, 'Gardens by the Bay');
insert into attraction (Service_id, Name) values (599, 'Golden Gate Bridge');
insert into attraction (Service_id, Name) values (602, 'St. Basil''s Cathedral');
insert into attraction (Service_id, Name) values (610, 'St. Peter''s Basilica');
insert into attraction (Service_id, Name) values (617, 'Blue Lagoon Iceland');
insert into attraction (Service_id, Name) values (618, 'St. Basil''s Cathedral');
insert into attraction (Service_id, Name) values (621, 'Hong Kong Disneyland');
insert into attraction (Service_id, Name) values (622, 'The Bund');
insert into attraction (Service_id, Name) values (634, 'Yellowstone National Park');
insert into attraction (Service_id, Name) values (636, 'CN Tower');
insert into attraction (Service_id, Name) values (639, 'Galapagos Islands');
insert into attraction (Service_id, Name) values (642, 'Tower of London');
insert into attraction (Service_id, Name) values (645, 'The Bund');
insert into attraction (Service_id, Name) values (650, 'Times Square');
insert into attraction (Service_id, Name) values (653, 'Keukenhof Gardens');
insert into attraction (Service_id, Name) values (666, 'Berlin Wall Memorial');
insert into attraction (Service_id, Name) values (679, 'Salar de Uyuni');
insert into attraction (Service_id, Name) values (680, 'Ha Long Bay');
insert into attraction (Service_id, Name) values (685, 'Santorini Caldera');
insert into attraction (Service_id, Name) values (695, 'Universal Studios Hollywood');
insert into attraction (Service_id, Name) values (696, 'Dead Sea');
insert into attraction (Service_id, Name) values (697, 'Berlin Wall Memorial');
insert into attraction (Service_id, Name) values (702, 'Sydney Opera House');
insert into attraction (Service_id, Name) values (706, 'Golden Gate Bridge');
insert into attraction (Service_id, Name) values (707, 'Jeita Grotto');
insert into attraction (Service_id, Name) values (709, 'Taj Mahal');
insert into attraction (Service_id, Name) values (713, 'Eiffel Tower');
insert into attraction (Service_id, Name) values (719, 'Salar de Uyuni');
insert into attraction (Service_id, Name) values (723, 'Gyeongbokgung Palace');
insert into attraction (Service_id, Name) values (724, 'Van Gogh Museum');
insert into attraction (Service_id, Name) values (734, 'Burj Khalifa');
insert into attraction (Service_id, Name) values (735, 'Sydney Opera House');
insert into attraction (Service_id, Name) values (738, 'Acropolis of Athens');
insert into attraction (Service_id, Name) values (753, 'Ha Long Bay');
insert into attraction (Service_id, Name) values (758, 'Statue of Liberty');
insert into attraction (Service_id, Name) values (760, 'Alhambra');
insert into attraction (Service_id, Name) values (767, 'Angkor Wat');
insert into attraction (Service_id, Name) values (773, 'Museum of Tomorrow');
insert into attraction (Service_id, Name) values (782, 'Grand Canyon');
insert into attraction (Service_id, Name) values (792, 'Rijksmuseum');
insert into attraction (Service_id, Name) values (795, 'Loch Ness');
insert into attraction (Service_id, Name) values (798, 'The Bund');
insert into attraction (Service_id, Name) values (803, 'Havana Viejo');
insert into attraction (Service_id, Name) values (812, 'Blue Lagoon Iceland');
insert into attraction (Service_id, Name) values (815, 'Brandenburg Gate');
insert into attraction (Service_id, Name) values (817, 'Serengeti National Park');
insert into attraction (Service_id, Name) values (821, 'Bora Bora Lagoon');
insert into attraction (Service_id, Name) values (826, 'Table Mountain');
insert into attraction (Service_id, Name) values (827, 'Prado Museum');
insert into attraction (Service_id, Name) values (831, 'Taj Mahal');
insert into attraction (Service_id, Name) values (834, 'Gyeongbokgung Palace');
insert into attraction (Service_id, Name) values (841, 'Marina Bay Sands');
insert into attraction (Service_id, Name) values (845, 'Petra Treasury');
insert into attraction (Service_id, Name) values (846, 'Trevi Fountain');
insert into attraction (Service_id, Name) values (849, 'Fushimi Inari Taisha');
insert into attraction (Service_id, Name) values (850, 'Alhambra');
insert into attraction (Service_id, Name) values (855, 'Machu Picchu');
insert into attraction (Service_id, Name) values (858, 'Ha Long Bay');
insert into attraction (Service_id, Name) values (859, 'Serengeti National Park');
insert into attraction (Service_id, Name) values (860, 'Acropolis of Athens');
insert into attraction (Service_id, Name) values (862, 'Corcovado Mountain');
insert into attraction (Service_id, Name) values (864, 'Havana Viejo');
insert into attraction (Service_id, Name) values (879, 'Grand-Place Brussels');
insert into attraction (Service_id, Name) values (885, 'Colosseum');
insert into attraction (Service_id, Name) values (899, 'Alhambra');
insert into attraction (Service_id, Name) values (916, 'Acropolis of Athens');
insert into attraction (Service_id, Name) values (927, 'Amalfi Coast');
insert into attraction (Service_id, Name) values (940, 'Angkor Wat');
insert into attraction (Service_id, Name) values (942, 'Fushimi Inari Taisha');
insert into attraction (Service_id, Name) values (950, 'Prado Museum');
insert into attraction (Service_id, Name) values (953, 'CN Tower');
insert into attraction (Service_id, Name) values (957, 'Van Gogh Museum');
insert into attraction (Service_id, Name) values (967, 'Gardens by the Bay');
insert into attraction (Service_id, Name) values (968, 'Universal Studios Hollywood');
insert into attraction (Service_id, Name) values (972, 'Mecca Great Mosque');
insert into attraction (Service_id, Name) values (981, 'Grand Canyon');
insert into attraction (Service_id, Name) values (982, 'CN Tower');
insert into attraction (Service_id, Name) values (988, 'Pamukkale Thermal Pools');
insert into attraction (Service_id, Name) values (989, 'Bora Bora Lagoon');
insert into attraction (Service_id, Name) values (992, 'Bora Bora Lagoon');
insert into attraction (Service_id, Name) values (996, 'Angkor Wat');
