
insert into promo_code (Code_id, Discount_percentage, Code_name) values (1, 0.77, 'Realigned');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (2, 0.37, 'success');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (3, 0.0, 'needs-based');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (4, 0.97, 'Polarised');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (5, 0.49, 'frame');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (6, 0.32, 'Virtual');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (7, 0.72, 'hardware');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (8, 0.11, 'Profit-focused');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (9, 0.41, 'functionalities');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (10, 0.1, 'Quality-focused');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (11, 0.8, 'Automated');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (12, 0.15, 'extranet');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (13, 0.13, 'hybrid');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (14, 0.43, 'Quality-focused');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (15, 0.4, 'Implemented');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (16, 0.1, 'asymmetric');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (17, 0.77, 'collaboration');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (18, 0.21, 'encompassing');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (19, 0.47, 'secured line');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (20, 0.73, 'attitude-oriented');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (21, 0.29, 'Innovative');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (22, 0.87, 'Multi-tiered');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (23, 0.02, 'process improvement');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (24, 0.89, 'responsive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (25, 0.11, 'pricing structure');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (26, 0.74, 'motivating');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (27, 0.88, 'secured line');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (28, 0.94, 'task-force');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (29, 0.76, 'directional');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (30, 0.86, 'attitude');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (31, 0.85, 'open system');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (32, 0.98, 'tangible');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (33, 0.31, 'leverage');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (34, 0.43, 'Managed');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (35, 0.72, 'time-frame');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (36, 0.88, 'Organic');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (37, 0.07, 'tangible');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (38, 0.13, 'Exclusive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (39, 0.44, 'Persevering');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (40, 0.97, 'Streamlined');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (41, 0.38, 'Persevering');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (42, 0.3, 'modular');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (43, 0.02, 'monitoring');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (44, 0.29, 'intranet');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (45, 0.29, 'open system');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (46, 0.68, 'Customizable');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (47, 0.67, 'optimal');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (48, 0.48, 'Graphic Interface');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (49, 0.55, 'Diverse');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (50, 0.62, 'functionalities');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (51, 0.36, 'Decentralized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (52, 0.78, 'policy');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (53, 0.99, 'methodology');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (54, 0.5, 'contingency');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (55, 0.99, 'hybrid');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (56, 0.95, 'functionalities');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (57, 0.36, 'motivating');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (58, 0.61, 'Automated');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (59, 0.15, 'incremental');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (60, 0.91, 'Organic');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (61, 0.42, 'strategy');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (62, 0.22, 'installation');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (63, 0.25, 'executive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (64, 0.95, 'secured line');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (65, 0.5, '24 hour');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (66, 0.02, 'Synchronised');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (67, 0.84, 'Operative');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (68, 0.94, 'budgetary management');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (69, 0.22, 'methodology');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (70, 0.89, 'Secured');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (71, 0.33, 'moderator');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (72, 0.6, 'secured line');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (73, 0.19, 'data-warehouse');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (74, 0.61, 'Enhanced');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (75, 0.66, 'tertiary');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (76, 0.55, 'focus group');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (77, 0.01, 'explicit');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (78, 0.97, 'encryption');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (79, 0.34, 'Stand-alone');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (80, 0.55, 'software');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (81, 0.11, 'Configurable');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (82, 0.56, 'well-modulated');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (83, 0.31, 'Multi-tiered');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (84, 0.52, 'next generation');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (85, 0.33, 'knowledge user');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (86, 0.34, 'client-server');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (87, 0.27, 'local');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (88, 0.09, 'stable');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (89, 0.33, 'User-friendly');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (90, 0.24, 'heuristic');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (91, 0.9, 'actuating');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (92, 0.04, 'transitional');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (93, 0.37, 'zero tolerance');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (94, 0.6, 'leading edge');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (95, 0.23, 'radical');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (96, 0.92, 'Programmable');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (97, 0.72, 'Quality-focused');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (98, 0.24, 'Fundamental');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (99, 0.7, 'Profit-focused');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (100, 0.37, 'holistic');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (101, 0.89, 'Up-sized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (102, 0.6, 'Expanded');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (103, 0.06, 'Fundamental');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (104, 0.03, 'Focused');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (105, 0.57, 'Profound');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (106, 0.1, 'Open-source');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (107, 0.11, 'pricing structure');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (108, 0.53, 'process improvement');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (109, 0.86, 'foreground');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (110, 0.06, 'homogeneous');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (111, 0.6, 'Front-line');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (112, 0.13, 'Graphical User Interface');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (113, 0.55, 'model');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (114, 0.29, 'productivity');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (115, 0.73, 'artificial intelligence');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (116, 0.46, 'Open-architected');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (117, 0.2, 'Innovative');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (118, 0.53, 'Synchronised');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (119, 0.99, 'capacity');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (120, 0.98, 'Polarised');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (121, 0.23, 'monitoring');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (122, 0.34, 'high-level');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (123, 0.29, 'uniform');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (124, 0.61, 'methodical');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (125, 0.55, 'logistical');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (126, 0.86, 'system engine');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (127, 0.51, 'policy');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (128, 0.05, 'tertiary');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (129, 0.29, 'human-resource');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (130, 0.63, 'Persevering');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (131, 0.36, '5th generation');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (132, 0.85, 'Ergonomic');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (133, 0.44, 'Right-sized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (134, 0.65, 'composite');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (135, 0.35, 'Reduced');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (136, 0.91, 'Assimilated');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (137, 0.88, 'Seamless');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (138, 0.6, 'complexity');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (139, 0.57, 'secondary');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (140, 0.17, 'reciprocal');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (141, 0.54, '3rd generation');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (142, 0.77, 'Cross-group');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (143, 0.39, 'attitude-oriented');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (144, 0.18, 'capacity');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (145, 0.54, 'systematic');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (146, 0.02, 'protocol');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (147, 0.52, 'multimedia');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (148, 0.49, 'Open-architected');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (149, 0.06, 'non-volatile');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (150, 0.93, 'framework');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (151, 0.89, 'application');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (152, 0.06, 'Phased');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (153, 0.63, 'tertiary');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (154, 0.42, 'Synchronised');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (155, 0.2, 'emulation');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (156, 0.77, 'solution-oriented');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (157, 0.91, 'Open-architected');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (158, 0.2, 'Front-line');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (159, 0.75, 'Front-line');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (160, 0.68, '24/7');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (161, 0.79, 'hardware');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (162, 0.05, 'Team-oriented');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (163, 0.84, 'policy');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (164, 0.01, 'heuristic');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (165, 0.3, 'Horizontal');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (166, 0.75, 'discrete');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (167, 0.32, 'non-volatile');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (168, 0.4, 'knowledge user');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (169, 0.15, 'flexibility');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (170, 0.16, 'heuristic');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (171, 0.42, 'coherent');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (172, 0.04, 'mission-critical');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (173, 0.95, 'database');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (174, 0.68, 'Cross-platform');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (175, 0.55, 'disintermediate');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (176, 0.37, 'multi-state');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (177, 0.32, 'reciprocal');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (178, 0.18, 'help-desk');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (179, 0.99, 'core');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (180, 0.13, 'regional');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (181, 0.74, 'asymmetric');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (182, 0.81, 'composite');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (183, 0.67, 'model');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (184, 0.95, 'policy');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (185, 0.82, 'Advanced');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (186, 0.86, 'foreground');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (187, 0.99, 'heuristic');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (188, 0.31, 'Re-engineered');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (189, 0.79, 'knowledge user');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (190, 0.57, 'secondary');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (191, 0.81, 'Innovative');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (192, 0.13, 'Front-line');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (193, 0.85, 'static');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (194, 0.77, 'Public-key');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (195, 0.45, 'analyzer');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (196, 0.1, 'discrete');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (197, 0.06, 'time-frame');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (198, 0.64, 'Advanced');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (199, 0.69, 'Realigned');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (200, 0.16, 'algorithm');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (201, 0.73, 'secondary');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (202, 0.47, 'Cross-platform');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (203, 0.99, 'Multi-tiered');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (204, 0.18, 'coherent');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (205, 0.33, 'architecture');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (206, 0.5, 'focus group');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (207, 0.33, 'algorithm');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (208, 0.71, 'bifurcated');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (209, 0.31, 'zero administration');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (210, 0.03, '6th generation');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (211, 0.53, 'Object-based');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (212, 0.49, 'Multi-channelled');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (213, 0.08, 'Digitized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (214, 0.38, 'Right-sized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (215, 0.7, 'customer loyalty');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (216, 0.63, 'radical');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (217, 0.37, 'hub');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (218, 0.48, 'interface');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (219, 0.03, 'fault-tolerant');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (220, 0.37, 'needs-based');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (221, 0.73, 'Vision-oriented');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (222, 0.78, 'moderator');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (223, 0.15, 'Horizontal');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (224, 0.48, 'upward-trending');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (225, 0.9, 'impactful');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (226, 0.25, 'instruction set');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (227, 0.94, 'Advanced');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (228, 0.02, 'Profound');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (229, 0.82, 'Ergonomic');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (230, 0.99, 'Function-based');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (231, 0.78, 'help-desk');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (232, 0.5, 'help-desk');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (233, 0.1, 'uniform');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (234, 0.09, 'Intuitive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (235, 0.65, 'open architecture');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (236, 0.05, 'website');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (237, 0.63, 'Cloned');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (238, 0.87, 'Profit-focused');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (239, 0.19, 'Pre-emptive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (240, 0.83, 'homogeneous');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (241, 0.14, 'encompassing');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (242, 0.12, 'attitude-oriented');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (243, 0.92, 'solution');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (244, 0.17, 'heuristic');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (245, 0.36, 'methodical');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (246, 0.02, 'Open-architected');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (247, 0.66, 'moratorium');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (248, 0.97, 'project');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (249, 0.77, 'Public-key');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (250, 0.74, 'solution-oriented');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (251, 0.44, 'Virtual');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (252, 0.65, 'Optional');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (253, 0.45, 'interactive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (254, 0.38, 'secured line');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (255, 0.52, 'heuristic');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (256, 0.12, 'approach');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (257, 0.31, 'object-oriented');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (258, 0.9, 'Object-based');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (259, 0.67, 'radical');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (260, 0.11, 'implementation');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (261, 0.95, 'stable');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (262, 0.15, 'web-enabled');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (263, 0.28, 'full-range');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (264, 0.11, 'parallelism');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (265, 0.89, 'intranet');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (266, 0.13, 'well-modulated');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (267, 0.78, 'user-facing');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (268, 0.16, 'value-added');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (269, 0.34, 'Fundamental');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (270, 0.31, 'monitoring');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (271, 0.04, 'flexibility');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (272, 0.41, 'User-friendly');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (273, 0.1, 'structure');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (274, 0.2, 'Organic');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (275, 0.88, 'client-driven');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (276, 0.16, 'zero administration');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (277, 0.05, 'radical');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (278, 0.98, 'responsive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (279, 0.69, 'Realigned');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (280, 0.72, 'knowledge user');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (281, 0.37, 'workforce');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (282, 0.11, 'encompassing');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (283, 0.53, 'Graphic Interface');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (284, 0.13, 'Decentralized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (285, 0.52, 'dynamic');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (286, 0.68, 'Managed');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (287, 0.09, 'Extended');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (288, 0.6, 'Customizable');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (289, 0.56, 'Ameliorated');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (290, 0.42, 'Virtual');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (291, 0.74, 'national');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (292, 0.09, 'moratorium');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (293, 0.42, 'Face to face');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (294, 0.34, 'analyzing');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (295, 0.37, 'context-sensitive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (296, 0.94, 'algorithm');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (297, 0.63, 'challenge');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (298, 0.69, 'User-centric');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (299, 0.93, 'help-desk');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (300, 0.3, 'motivating');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (301, 0.09, 'encompassing');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (302, 0.14, 'product');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (303, 0.44, 'Business-focused');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (304, 0.05, 'motivating');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (305, 0.81, 'fault-tolerant');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (306, 0.43, 'Proactive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (307, 0.16, 'moderator');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (308, 0.21, 'Organized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (309, 0.4, 'concept');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (310, 0.16, 'coherent');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (311, 0.19, 'Streamlined');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (312, 0.63, 'leading edge');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (313, 0.68, 'Versatile');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (314, 0.55, 'process improvement');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (315, 0.33, 'heuristic');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (316, 0.61, 'composite');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (317, 0.39, 'hybrid');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (318, 0.07, 'Cross-platform');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (319, 0.43, 'database');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (320, 0.06, 'Innovative');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (321, 0.58, 'forecast');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (322, 1.0, 'Multi-channelled');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (323, 0.37, 'Proactive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (324, 0.43, 'Synchronised');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (325, 0.64, 'incremental');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (326, 0.1, 'monitoring');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (327, 0.63, 'Distributed');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (328, 0.14, 'Mandatory');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (329, 0.25, 'static');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (330, 0.64, 'global');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (331, 0.58, 'Up-sized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (332, 0.18, 'bi-directional');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (333, 0.06, 'database');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (334, 0.19, 'standardization');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (335, 0.74, 'interface');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (336, 0.78, 'application');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (337, 0.79, 'Realigned');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (338, 0.45, 'complexity');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (339, 0.66, 'mobile');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (340, 0.07, 'Up-sized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (341, 0.97, 'Distributed');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (342, 0.22, 'Multi-tiered');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (343, 0.21, 'high-level');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (344, 0.73, 'Networked');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (345, 0.89, 'hardware');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (346, 0.41, 'Future-proofed');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (347, 0.62, 'toolset');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (348, 0.89, 'maximized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (349, 0.45, 'object-oriented');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (350, 0.13, 'website');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (351, 0.33, 'interactive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (352, 0.35, 'database');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (353, 0.45, 'protocol');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (354, 0.11, 'Expanded');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (355, 0.24, 'Right-sized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (356, 0.33, 'Cloned');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (357, 0.05, 'impactful');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (358, 0.79, 'value-added');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (359, 0.23, 'Customer-focused');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (360, 0.97, 'Visionary');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (361, 0.92, 'maximized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (362, 0.25, 'object-oriented');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (363, 0.7, 'incremental');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (364, 0.76, 'exuding');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (365, 0.59, 'framework');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (366, 0.0, 'open system');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (367, 0.67, 'Organized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (368, 0.19, 'utilisation');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (369, 0.96, 'responsive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (370, 0.61, 'next generation');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (371, 0.52, 'concept');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (372, 0.18, 'Graphical User Interface');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (373, 0.65, 'upward-trending');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (374, 0.42, 'migration');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (375, 0.48, 'Universal');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (376, 0.27, 'maximized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (377, 0.57, 'hierarchy');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (378, 0.61, 'frame');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (379, 0.95, 'Team-oriented');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (380, 0.95, '3rd generation');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (381, 0.55, 'Assimilated');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (382, 0.62, 'Optional');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (383, 0.33, 'approach');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (384, 0.93, 'Compatible');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (385, 0.84, 'Enterprise-wide');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (386, 0.58, 'Adaptive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (387, 0.4, 'multi-tasking');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (388, 0.65, 'adapter');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (389, 0.12, 'capacity');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (390, 0.56, '24/7');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (391, 0.66, 'system engine');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (392, 0.59, 'Reduced');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (393, 0.92, 'structure');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (394, 0.4, 'methodology');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (395, 0.05, 'Monitored');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (396, 0.28, 'intangible');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (397, 0.97, 'Quality-focused');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (398, 0.46, 'heuristic');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (399, 0.2, 'bottom-line');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (400, 0.19, 'value-added');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (401, 0.46, 'Optimized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (402, 0.64, 'database');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (403, 0.28, 'Horizontal');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (404, 0.64, 'functionalities');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (405, 0.33, 'non-volatile');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (406, 0.86, 'real-time');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (407, 0.32, 'local area network');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (408, 0.72, 'Persevering');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (409, 0.27, 'Versatile');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (410, 0.6, 'migration');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (411, 0.01, 'holistic');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (412, 0.89, 'projection');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (413, 0.11, 'interactive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (414, 0.15, 'moratorium');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (415, 0.77, 'zero tolerance');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (416, 0.4, 'forecast');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (417, 0.28, 'firmware');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (418, 0.55, 'Multi-layered');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (419, 0.97, 'synergy');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (420, 0.42, 'context-sensitive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (421, 0.93, 'Fundamental');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (422, 0.55, 'Triple-buffered');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (423, 0.38, 'local area network');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (424, 0.14, 'Stand-alone');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (425, 0.12, '6th generation');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (426, 0.58, 'system engine');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (427, 0.51, 'Versatile');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (428, 0.66, 'synergy');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (429, 0.26, 'functionalities');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (430, 0.56, 'Triple-buffered');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (431, 0.67, 'Organic');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (432, 0.3, 'open system');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (433, 0.26, 'application');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (434, 0.35, 'Intuitive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (435, 0.05, 'Monitored');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (436, 0.53, 'algorithm');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (437, 0.15, 'homogeneous');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (438, 0.57, 'Optimized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (439, 0.86, 'installation');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (440, 0.59, 'Adaptive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (441, 0.19, 'migration');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (442, 0.11, 'intranet');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (443, 0.56, 'composite');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (444, 0.86, 'global');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (445, 0.79, 'info-mediaries');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (446, 0.75, 'Business-focused');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (447, 0.01, 'client-server');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (448, 0.13, 'asynchronous');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (449, 0.89, 'Versatile');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (450, 0.41, 'analyzer');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (451, 0.47, 'function');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (452, 0.24, 'hub');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (453, 0.74, 'success');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (454, 0.66, 'throughput');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (455, 0.33, 'internet solution');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (456, 0.22, 'contingency');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (457, 0.88, 'Future-proofed');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (458, 0.87, 'Graphical User Interface');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (459, 0.83, 'asymmetric');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (460, 0.76, 'Diverse');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (461, 0.71, 'workforce');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (462, 0.63, 'disintermediate');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (463, 0.61, 'reciprocal');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (464, 0.26, 'Down-sized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (465, 0.31, 'emulation');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (466, 0.03, 'leading edge');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (467, 0.47, 'Managed');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (468, 0.69, 'high-level');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (469, 0.2, 'frame');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (470, 0.57, 'Automated');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (471, 0.07, 'instruction set');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (472, 0.32, 'encoding');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (473, 0.3, 'installation');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (474, 0.15, 'open system');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (475, 0.93, 'Mandatory');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (476, 0.95, 'empowering');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (477, 0.9, 'local area network');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (478, 0.48, 'secondary');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (479, 0.29, 'portal');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (480, 0.72, 'logistical');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (481, 0.95, 'Diverse');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (482, 0.25, 'Advanced');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (483, 0.24, 'intranet');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (484, 0.44, 'adapter');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (485, 0.33, 'Assimilated');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (486, 0.28, 'Customer-focused');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (487, 0.68, '5th generation');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (488, 0.09, 'User-centric');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (489, 0.03, 'upward-trending');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (490, 0.11, 'contingency');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (491, 0.42, 'synergy');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (492, 0.41, 'Vision-oriented');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (493, 0.07, 'model');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (494, 0.02, 'challenge');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (495, 0.93, 'bottom-line');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (496, 0.23, 'budgetary management');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (497, 0.78, 'Persevering');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (498, 0.93, 'incremental');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (499, 0.56, 'methodology');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (500, 0.63, 'Re-engineered');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (501, 0.72, 'Multi-tiered');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (502, 0.1, 'Implemented');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (503, 0.5, 'national');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (504, 0.88, 'Multi-channelled');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (505, 0.09, 'challenge');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (506, 0.1, 'conglomeration');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (507, 0.75, 'knowledge base');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (508, 0.14, 'Mandatory');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (509, 0.56, 'methodical');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (510, 0.84, 'leverage');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (511, 0.58, 'utilisation');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (512, 0.51, 'hub');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (513, 0.85, 'contingency');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (514, 0.01, 'zero administration');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (515, 0.37, 'radical');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (516, 0.66, 'directional');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (517, 0.11, 'framework');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (518, 0.3, 'Enterprise-wide');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (519, 0.65, 'monitoring');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (520, 0.75, 'Customizable');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (521, 0.78, 'human-resource');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (522, 0.24, 'hardware');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (523, 0.0, 'functionalities');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (524, 0.46, 'Managed');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (525, 0.76, 'capacity');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (526, 0.96, 'Assimilated');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (527, 0.05, 'neural-net');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (528, 0.71, 'asynchronous');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (529, 0.88, 'tangible');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (530, 0.68, 'Exclusive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (531, 0.91, 'Seamless');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (532, 0.17, 'application');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (533, 0.79, 'Adaptive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (534, 0.46, 'Multi-channelled');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (535, 0.8, 'solution-oriented');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (536, 0.53, 'hierarchy');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (537, 0.4, 'hierarchy');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (538, 0.68, 'portal');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (539, 0.88, 'Synergistic');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (540, 0.43, 'Pre-emptive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (541, 0.68, 'alliance');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (542, 0.57, 'Integrated');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (543, 0.3, 'Organized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (544, 0.59, 'Extended');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (545, 0.56, 'Centralized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (546, 0.54, '24/7');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (547, 0.3, 'interactive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (548, 0.77, 'upward-trending');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (549, 0.54, 'model');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (550, 0.9, '6th generation');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (551, 0.66, '4th generation');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (552, 0.04, 'Self-enabling');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (553, 0.02, 'projection');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (554, 0.92, 'knowledge base');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (555, 0.17, 'eco-centric');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (556, 0.82, 'multimedia');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (557, 0.55, 'parallelism');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (558, 0.64, '4th generation');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (559, 0.52, 'Proactive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (560, 0.28, 'Configurable');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (561, 0.3, 'cohesive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (562, 0.16, 'Centralized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (563, 0.77, 'moderator');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (564, 0.52, 'info-mediaries');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (565, 0.49, 'Persistent');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (566, 0.85, 'service-desk');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (567, 0.99, 'discrete');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (568, 0.1, 'forecast');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (569, 0.69, 'next generation');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (570, 0.46, 'empowering');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (571, 0.19, 'open system');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (572, 0.4, 'Reactive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (573, 0.8, 'Function-based');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (574, 0.78, 'contextually-based');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (575, 0.22, 'forecast');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (576, 0.78, 'context-sensitive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (577, 0.48, 'secondary');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (578, 0.31, 'responsive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (579, 0.78, 'challenge');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (580, 0.7, 'firmware');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (581, 0.67, 'functionalities');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (582, 0.25, 'Ameliorated');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (583, 0.21, 'client-driven');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (584, 0.11, 'structure');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (585, 0.9, 'intranet');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (586, 0.51, 'Advanced');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (587, 0.79, 'policy');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (588, 0.12, 'Centralized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (589, 0.97, 'encryption');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (590, 0.54, 'initiative');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (591, 0.16, 'protocol');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (592, 0.21, 'adapter');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (593, 0.63, 'definition');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (594, 0.09, 'Organized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (595, 0.29, 'artificial intelligence');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (596, 0.67, 'pricing structure');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (597, 0.66, 'Extended');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (598, 0.53, 'Integrated');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (599, 0.18, 'Function-based');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (600, 0.19, 'approach');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (601, 0.77, 'open architecture');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (602, 0.8, 'User-centric');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (603, 0.73, 'modular');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (604, 0.5, 'Centralized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (605, 0.23, 'Multi-layered');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (606, 0.22, 'methodology');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (607, 0.29, 'regional');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (608, 0.17, 'Quality-focused');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (609, 0.52, 'array');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (610, 0.22, 'cohesive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (611, 0.62, 'Programmable');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (612, 0.79, 'Up-sized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (613, 0.48, 'non-volatile');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (614, 0.44, 'Secured');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (615, 0.91, 'leverage');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (616, 0.07, 'ability');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (617, 0.3, 'leverage');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (618, 0.09, 'artificial intelligence');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (619, 0.45, 'Stand-alone');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (620, 0.8, 'De-engineered');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (621, 0.8, 'Organic');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (622, 0.54, 'Reverse-engineered');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (623, 0.53, 'eco-centric');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (624, 0.7, 'moderator');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (625, 0.79, 'incremental');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (626, 0.33, 'user-facing');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (627, 0.69, 'parallelism');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (628, 0.56, 'uniform');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (629, 0.4, 'knowledge base');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (630, 0.98, 'interactive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (631, 0.66, 'benchmark');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (632, 0.29, 'Realigned');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (633, 0.42, 'multi-state');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (634, 0.32, 'neutral');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (635, 0.94, 'framework');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (636, 0.9, 'Distributed');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (637, 0.64, 'logistical');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (638, 0.2, 'Reactive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (639, 0.59, 'Cloned');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (640, 0.69, '3rd generation');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (641, 0.1, 'Adaptive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (642, 0.4, 'Realigned');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (643, 0.45, 'actuating');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (644, 0.81, 'zero tolerance');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (645, 0.92, 'regional');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (646, 0.34, 'support');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (647, 0.64, 'application');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (648, 0.37, 'holistic');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (649, 0.18, 'groupware');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (650, 0.45, 'toolset');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (651, 0.32, 'even-keeled');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (652, 0.36, 'Universal');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (653, 0.39, 'context-sensitive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (654, 0.51, 'disintermediate');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (655, 0.09, 'core');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (656, 0.3, 'collaboration');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (657, 0.58, 'Virtual');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (658, 0.44, 'Exclusive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (659, 0.06, 'Reactive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (660, 0.43, 'migration');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (661, 0.22, 'grid-enabled');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (662, 0.41, 'Cross-platform');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (663, 0.09, 'model');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (664, 0.53, 'tangible');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (665, 0.14, 'stable');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (666, 0.35, 'Self-enabling');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (667, 0.97, 'User-centric');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (668, 0.54, 'artificial intelligence');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (669, 0.13, 'implementation');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (670, 0.7, 'clear-thinking');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (671, 0.27, 'static');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (672, 0.24, 'encryption');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (673, 0.78, 'bandwidth-monitored');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (674, 0.19, 'strategy');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (675, 0.94, 'Persistent');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (676, 0.05, 'User-friendly');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (677, 0.69, 'model');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (678, 0.09, 'Customizable');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (679, 0.62, 'Future-proofed');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (680, 0.33, 'value-added');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (681, 0.87, 'Diverse');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (682, 0.05, 'Innovative');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (683, 0.49, 'Realigned');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (684, 0.06, 'real-time');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (685, 0.13, 'hub');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (686, 0.22, 'De-engineered');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (687, 0.33, 'Balanced');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (688, 0.24, 'methodical');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (689, 0.8, 'fault-tolerant');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (690, 0.19, 'throughput');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (691, 0.28, 'functionalities');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (692, 0.73, 'multi-state');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (693, 0.7, 'attitude');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (694, 0.28, 'Self-enabling');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (695, 0.42, 'Automated');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (696, 0.49, 'Seamless');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (697, 0.98, 'infrastructure');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (698, 0.99, 'portal');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (699, 0.15, 'tertiary');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (700, 0.82, 'functionalities');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (701, 0.73, 'archive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (702, 0.01, 'Multi-lateral');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (703, 0.79, 'non-volatile');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (704, 0.52, 'Decentralized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (705, 0.52, 'info-mediaries');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (706, 0.61, 'Switchable');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (707, 0.42, 'fault-tolerant');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (708, 0.74, 'tangible');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (709, 0.55, 'toolset');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (710, 0.8, 'system engine');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (711, 0.62, '24 hour');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (712, 0.89, 'Automated');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (713, 0.17, 'zero defect');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (714, 0.82, 'intranet');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (715, 0.15, 'heuristic');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (716, 0.89, 'contingency');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (717, 0.88, 'orchestration');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (718, 0.98, 'Ameliorated');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (719, 0.77, 'emulation');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (720, 0.86, 'Vision-oriented');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (721, 0.99, 'Optimized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (722, 0.83, 'Organized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (723, 0.41, '24 hour');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (724, 0.46, 'Ergonomic');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (725, 0.89, 'archive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (726, 0.19, 'Multi-channelled');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (727, 0.48, 'global');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (728, 0.6, 'circuit');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (729, 0.67, 'Multi-channelled');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (730, 0.3, 'Versatile');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (731, 0.39, 'success');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (732, 0.89, 'conglomeration');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (733, 0.12, 'heuristic');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (734, 0.46, 'Ergonomic');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (735, 0.64, 'background');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (736, 0.69, 'groupware');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (737, 0.28, 'executive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (738, 0.67, 'zero administration');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (739, 0.97, 'Down-sized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (740, 0.77, 'installation');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (741, 0.39, 'Fundamental');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (742, 0.23, 'bifurcated');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (743, 0.85, 'frame');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (744, 0.57, 'productivity');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (745, 0.11, 'Multi-channelled');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (746, 0.21, 'algorithm');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (747, 0.37, 'Digitized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (748, 0.02, 'Reverse-engineered');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (749, 0.63, 'budgetary management');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (750, 0.17, 'global');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (751, 0.19, 'Enterprise-wide');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (752, 0.06, 'synergy');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (753, 0.79, 'Programmable');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (754, 0.05, 'data-warehouse');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (755, 0.47, 'stable');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (756, 0.35, 'methodical');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (757, 0.18, 'conglomeration');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (758, 0.03, 'Implemented');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (759, 0.03, 'system engine');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (760, 0.08, 'moderator');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (761, 0.32, 'data-warehouse');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (762, 0.75, 'infrastructure');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (763, 0.96, 'paradigm');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (764, 0.09, 'incremental');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (765, 0.13, 'budgetary management');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (766, 0.04, 'demand-driven');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (767, 0.34, 'Proactive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (768, 0.93, 'Exclusive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (769, 0.12, 'complexity');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (770, 0.29, 'Ameliorated');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (771, 0.8, 'Inverse');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (772, 0.23, 'Function-based');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (773, 0.26, 'algorithm');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (774, 0.34, 'solution-oriented');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (775, 0.71, 'Progressive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (776, 0.67, 'Programmable');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (777, 0.89, 'next generation');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (778, 0.41, '5th generation');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (779, 0.33, 'global');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (780, 0.89, 'monitoring');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (781, 0.54, 'local');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (782, 0.99, 'moratorium');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (783, 0.33, 'actuating');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (784, 0.53, 'info-mediaries');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (785, 0.56, 'Quality-focused');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (786, 0.25, 'approach');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (787, 0.84, 'Managed');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (788, 0.37, 'productivity');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (789, 0.61, 'Inverse');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (790, 0.81, 'open architecture');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (791, 0.65, 'Up-sized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (792, 0.9, 'Robust');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (793, 0.5, 'dedicated');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (794, 0.3, 'standardization');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (795, 0.71, 'protocol');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (796, 0.44, 'Programmable');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (797, 0.58, 'static');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (798, 0.96, 'directional');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (799, 0.3, 'website');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (800, 0.72, 'methodical');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (801, 0.95, 'productivity');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (802, 0.15, 'even-keeled');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (803, 0.64, 'data-warehouse');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (804, 0.56, 'interface');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (805, 0.97, 'multi-tasking');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (806, 0.77, 'alliance');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (807, 0.98, 'Pre-emptive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (808, 0.77, 'hub');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (809, 0.14, 'Stand-alone');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (810, 0.89, 'Mandatory');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (811, 0.61, 'knowledge base');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (812, 0.19, 'pricing structure');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (813, 0.6, 'neural-net');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (814, 0.27, 'Streamlined');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (815, 0.29, 'explicit');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (816, 0.01, 'Self-enabling');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (817, 1.0, 'Ameliorated');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (818, 0.34, 'Open-architected');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (819, 0.01, 'clear-thinking');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (820, 0.83, 'executive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (821, 0.15, 'productivity');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (822, 0.36, 'Organized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (823, 0.66, '6th generation');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (824, 0.72, 'Right-sized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (825, 0.3, 'Mandatory');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (826, 0.7, 'Grass-roots');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (827, 0.72, 'high-level');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (828, 0.69, 'De-engineered');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (829, 0.77, 'secured line');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (830, 0.28, '6th generation');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (831, 0.36, 'global');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (832, 0.09, 'monitoring');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (833, 0.14, 'user-facing');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (834, 0.55, 'real-time');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (835, 0.19, 'tangible');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (836, 0.63, 'transitional');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (837, 0.98, 'attitude-oriented');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (838, 0.04, 'User-centric');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (839, 0.96, 'system-worthy');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (840, 0.49, 'optimal');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (841, 0.38, 'strategy');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (842, 0.39, 'Cloned');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (843, 0.91, 'Implemented');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (844, 0.71, 'Configurable');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (845, 0.81, 'Realigned');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (846, 0.71, 'grid-enabled');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (847, 0.47, 'policy');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (848, 0.0, 'needs-based');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (849, 0.81, 'motivating');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (850, 0.45, 'Advanced');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (851, 0.0, 'policy');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (852, 0.23, 'adapter');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (853, 0.47, 'maximized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (854, 0.93, 'Reverse-engineered');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (855, 0.47, 'Stand-alone');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (856, 0.46, 'protocol');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (857, 0.33, 'matrices');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (858, 0.82, 'tangible');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (859, 0.03, 'demand-driven');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (860, 0.5, 'algorithm');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (861, 0.64, 'Diverse');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (862, 0.63, 'Persevering');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (863, 0.39, 'neutral');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (864, 0.73, 'open architecture');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (865, 0.29, 'Seamless');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (866, 0.06, 'implementation');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (867, 0.56, 'protocol');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (868, 0.94, 'Enterprise-wide');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (869, 0.54, 'encryption');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (870, 0.24, 'Reduced');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (871, 0.34, 'Proactive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (872, 0.16, 'client-driven');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (873, 0.95, 'contextually-based');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (874, 0.41, 'initiative');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (875, 0.1, 'Re-engineered');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (876, 0.01, 'asynchronous');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (877, 0.81, 'Programmable');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (878, 0.71, 'Exclusive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (879, 0.56, 'heuristic');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (880, 0.57, 'full-range');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (881, 0.68, 'bifurcated');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (882, 0.96, 'methodology');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (883, 0.25, 'matrices');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (884, 0.23, 'system-worthy');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (885, 0.95, 'interactive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (886, 0.4, 'local');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (887, 0.23, 'Compatible');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (888, 0.85, 'Compatible');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (889, 0.65, 'Open-source');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (890, 0.21, '24 hour');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (891, 0.59, 'Multi-layered');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (892, 0.14, 'even-keeled');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (893, 0.41, 'customer loyalty');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (894, 0.54, 'leverage');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (895, 0.38, 'uniform');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (896, 0.02, 'Multi-channelled');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (897, 0.06, 'Sharable');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (898, 0.24, '24 hour');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (899, 0.41, 'optimizing');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (900, 0.0, 'task-force');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (901, 0.49, 'Fundamental');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (902, 0.63, 'moratorium');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (903, 0.75, 'customer loyalty');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (904, 0.53, 'hub');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (905, 0.77, 'logistical');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (906, 0.47, 'Digitized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (907, 0.54, 'access');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (908, 0.18, 'real-time');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (909, 0.54, 'success');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (910, 0.93, 'functionalities');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (911, 0.9, 'multi-tasking');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (912, 0.88, 'system engine');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (913, 1.0, 'bi-directional');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (914, 0.7, 'Seamless');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (915, 0.62, 'even-keeled');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (916, 0.45, 'analyzer');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (917, 0.97, 'mission-critical');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (918, 0.85, 'portal');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (919, 0.18, 'next generation');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (920, 0.4, 'Robust');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (921, 0.09, 'national');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (922, 0.86, 'Reverse-engineered');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (923, 0.93, 'incremental');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (924, 0.81, 'migration');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (925, 0.43, 'Realigned');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (926, 0.29, 'encoding');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (927, 0.86, 'knowledge base');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (928, 0.41, '24 hour');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (929, 0.89, 'challenge');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (930, 0.52, 'Reverse-engineered');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (931, 0.27, 'leading edge');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (932, 0.42, 'Operative');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (933, 0.94, 'Secured');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (934, 0.53, 'monitoring');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (935, 0.1, 'user-facing');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (936, 0.93, 'workforce');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (937, 0.58, 'Fully-configurable');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (938, 0.18, 'zero defect');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (939, 0.31, 'Customizable');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (940, 0.68, 'secondary');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (941, 0.64, 'toolset');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (942, 0.43, 'foreground');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (943, 0.5, 'Team-oriented');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (944, 0.25, 'Synergized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (945, 0.89, 'function');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (946, 0.99, 'Universal');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (947, 0.77, 'synergy');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (948, 0.08, 'Devolved');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (949, 0.65, 'maximized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (950, 0.94, 'help-desk');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (951, 0.17, 'contingency');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (952, 0.47, 'definition');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (953, 0.97, 'Universal');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (954, 0.82, 'infrastructure');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (955, 0.32, 'Synergistic');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (956, 0.62, 'foreground');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (957, 0.28, 'frame');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (958, 0.32, 'middleware');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (959, 0.14, 'superstructure');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (960, 0.61, 'leading edge');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (961, 0.94, 'capability');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (962, 0.88, 'hybrid');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (963, 0.18, 'local');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (964, 0.88, 'secured line');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (965, 0.75, 'Customizable');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (966, 0.91, 'Focused');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (967, 0.75, 'interactive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (968, 0.43, 'website');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (969, 0.6, 'success');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (970, 0.05, 'holistic');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (971, 0.21, 'Exclusive');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (972, 0.25, 'hybrid');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (973, 0.34, 'frame');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (974, 0.27, 'clear-thinking');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (975, 0.44, 'systematic');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (976, 0.14, 'Decentralized');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (977, 0.79, 'instruction set');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (978, 0.15, 'workforce');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (979, 0.23, 'intangible');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (980, 0.38, 'project');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (981, 0.9, 'Distributed');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (982, 0.34, 'Self-enabling');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (983, 0.55, 'tangible');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (984, 0.49, 'Public-key');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (985, 0.72, 'superstructure');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (986, 0.22, 'Total');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (987, 0.33, 'radical');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (988, 0.61, 'dedicated');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (989, 0.95, 'flexibility');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (990, 0.33, 'Programmable');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (991, 0.26, 'Function-based');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (992, 0.22, 'success');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (993, 0.89, 'artificial intelligence');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (994, 0.31, 'empowering');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (995, 0.28, 'Triple-buffered');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (996, 0.66, 'attitude-oriented');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (997, 0.09, 'Quality-focused');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (998, 0.92, 'intermediate');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (999, 0.24, 'zero defect');
insert into promo_code (Code_id, Discount_percentage, Code_name) values (1000, 0.66, 'time-frame');
