
insert into restaurant (Service_id, Name) values ('1', 'The Saffron Fennel');
insert into restaurant (Service_id, Name) values ('2', 'The Azure Oregano');
insert into restaurant (Service_id, Name) values ('3', 'The Teal Ginger');
insert into restaurant (Service_id, Name) values ('4', 'The Scarlet Thyme');
insert into restaurant (Service_id, Name) values ('5', 'The Maroon Oregano');
insert into restaurant (Service_id, Name) values ('6', 'Gislason''s Kitchen');
insert into restaurant (Service_id, Name) values ('7', 'New York Bistro');
insert into restaurant (Service_id, Name) values ('8', 'Bayer''s Kitchen');
insert into restaurant (Service_id, Name) values ('9', 'The Saffron Fennel');
insert into restaurant (Service_id, Name) values ('10', 'The Amber Rosemary');
insert into restaurant (Service_id, Name) values ('11', 'New York Bistro');
insert into restaurant (Service_id, Name) values ('12', 'Williamson''s Kitchen');
insert into restaurant (Service_id, Name) values ('13', 'The Jade Mint');
insert into restaurant (Service_id, Name) values ('14', 'The Copper Tarragon');
insert into restaurant (Service_id, Name) values ('15', 'The Copper Tarragon');
insert into restaurant (Service_id, Name) values ('16', 'The Indigo Ginger');
insert into restaurant (Service_id, Name) values ('17', 'The Scarlet Saffron');
insert into restaurant (Service_id, Name) values ('18', 'The Ruby Thyme');
insert into restaurant (Service_id, Name) values ('19', 'The Indigo Oregano');
insert into restaurant (Service_id, Name) values ('20', 'The Golden Fennel');
insert into restaurant (Service_id, Name) values ('21', 'Barcelona Bistro');
insert into restaurant (Service_id, Name) values ('22', 'The Cobalt Basil');
insert into restaurant (Service_id, Name) values ('23', 'The Ruby Clove');
insert into restaurant (Service_id, Name) values ('24', 'Boston Bistro');
insert into restaurant (Service_id, Name) values ('25', 'The Scarlet Thyme');
insert into restaurant (Service_id, Name) values ('26', 'The Jade Tarragon');
insert into restaurant (Service_id, Name) values ('27', 'Glover''s Kitchen');
insert into restaurant (Service_id, Name) values ('28', 'Kyoto Bistro');
insert into restaurant (Service_id, Name) values ('29', 'The Amber Ginger');
insert into restaurant (Service_id, Name) values ('30', 'The Maroon Oregano');
insert into restaurant (Service_id, Name) values ('31', 'O''Keefe''s Kitchen');
insert into restaurant (Service_id, Name) values ('32', 'Murray''s Kitchen');
insert into restaurant (Service_id, Name) values ('33', 'The Copper Basil');
insert into restaurant (Service_id, Name) values ('34', 'Murray''s Kitchen');
insert into restaurant (Service_id, Name) values ('35', 'The Cobalt Saffron');
insert into restaurant (Service_id, Name) values ('36', 'Kyoto Bistro');
insert into restaurant (Service_id, Name) values ('37', 'Sydney Bistro');
insert into restaurant (Service_id, Name) values ('38', 'Dach''s Kitchen');
insert into restaurant (Service_id, Name) values ('39', 'Rogahn''s Kitchen');
insert into restaurant (Service_id, Name) values ('40', 'The Azure Oregano');
insert into restaurant (Service_id, Name) values ('41', 'The Emerald Clove');
insert into restaurant (Service_id, Name) values ('42', 'Williamson''s Kitchen');
insert into restaurant (Service_id, Name) values ('43', 'Heller''s Kitchen');
insert into restaurant (Service_id, Name) values ('44', 'London Bistro');
insert into restaurant (Service_id, Name) values ('45', 'The Teal Ginger');
insert into restaurant (Service_id, Name) values ('46', 'The Crimson Saffron');
insert into restaurant (Service_id, Name) values ('47', 'The Copper Chive');
insert into restaurant (Service_id, Name) values ('48', 'Wilkinson''s Kitchen');
insert into restaurant (Service_id, Name) values ('49', 'The Indigo Oregano');
insert into restaurant (Service_id, Name) values ('50', 'The Azure Oregano');
insert into restaurant (Service_id, Name) values ('51', 'The Jade Tarragon');
insert into restaurant (Service_id, Name) values ('52', 'The Onyx Fennel');
insert into restaurant (Service_id, Name) values ('53', 'The Ruby Chive');
insert into restaurant (Service_id, Name) values ('54', 'The Ivory Basil');
insert into restaurant (Service_id, Name) values ('55', 'Roma Bistro');
insert into restaurant (Service_id, Name) values ('56', 'The Golden Basil');
insert into restaurant (Service_id, Name) values ('57', 'Schmeler''s Kitchen');
insert into restaurant (Service_id, Name) values ('58', 'The Crimson Saffron');
insert into restaurant (Service_id, Name) values ('59', 'The Maroon Fennel');
insert into restaurant (Service_id, Name) values ('60', 'The Ruby Chive');
insert into restaurant (Service_id, Name) values ('61', 'The Ivory Basil');
insert into restaurant (Service_id, Name) values ('62', 'Paris Bistro');
insert into restaurant (Service_id, Name) values ('63', 'Glover''s Kitchen');
insert into restaurant (Service_id, Name) values ('64', 'The Indigo Ginger');
insert into restaurant (Service_id, Name) values ('65', 'The Cobalt Oregano');
insert into restaurant (Service_id, Name) values ('66', 'Vienna Bistro');
insert into restaurant (Service_id, Name) values ('67', 'The Copper Dill');
insert into restaurant (Service_id, Name) values ('68', 'The Copper Thyme');
insert into restaurant (Service_id, Name) values ('69', 'The Ivory Mint');
insert into restaurant (Service_id, Name) values ('70', 'Cummerata''s Kitchen');
insert into restaurant (Service_id, Name) values ('71', 'The Jade Fennel');
insert into restaurant (Service_id, Name) values ('72', 'The Teal Mint');
insert into restaurant (Service_id, Name) values ('73', 'The Maroon Oregano');
insert into restaurant (Service_id, Name) values ('74', 'The Scarlet Dill');
insert into restaurant (Service_id, Name) values ('75', 'Gislason''s Kitchen');
insert into restaurant (Service_id, Name) values ('76', 'The Indigo Lavender');
insert into restaurant (Service_id, Name) values ('77', 'The Cobalt Basil');
insert into restaurant (Service_id, Name) values ('78', 'Casper''s Kitchen');
insert into restaurant (Service_id, Name) values ('79', 'Stroman''s Kitchen');
insert into restaurant (Service_id, Name) values ('80', 'The Scarlet Saffron');
insert into restaurant (Service_id, Name) values ('81', 'The Saffron Clove');
insert into restaurant (Service_id, Name) values ('82', 'Chicago Bistro');
insert into restaurant (Service_id, Name) values ('83', 'Kyoto Bistro');
insert into restaurant (Service_id, Name) values ('84', 'The Amber Ginger');
insert into restaurant (Service_id, Name) values ('85', 'The Copper Tarragon');
insert into restaurant (Service_id, Name) values ('86', 'Denver Bistro');
insert into restaurant (Service_id, Name) values ('87', 'The Copper Fennel');
insert into restaurant (Service_id, Name) values ('88', 'Johnston''s Kitchen');
insert into restaurant (Service_id, Name) values ('89', 'Wilkinson''s Kitchen');
insert into restaurant (Service_id, Name) values ('90', 'Miller''s Kitchen');
insert into restaurant (Service_id, Name) values ('91', 'Tokyo Bistro');
insert into restaurant (Service_id, Name) values ('92', 'The Copper Fennel');
insert into restaurant (Service_id, Name) values ('93', 'The Copper Ginger');
insert into restaurant (Service_id, Name) values ('94', 'The Cobalt Mint');
insert into restaurant (Service_id, Name) values ('95', 'The Ivory Basil');
insert into restaurant (Service_id, Name) values ('96', 'The Copper Dill');
insert into restaurant (Service_id, Name) values ('97', 'The Teal Ginger');
insert into restaurant (Service_id, Name) values ('98', 'The Golden Chive');
insert into restaurant (Service_id, Name) values ('99', 'Padberg''s Kitchen');
insert into restaurant (Service_id, Name) values ('100', 'The Teal Ginger');
insert into restaurant (Service_id, Name) values ('101', 'The Cobalt Basil');
insert into restaurant (Service_id, Name) values ('102', 'Miami Bistro');
insert into restaurant (Service_id, Name) values ('103', 'London Bistro');
insert into restaurant (Service_id, Name) values ('104', 'The Emerald Thyme');
insert into restaurant (Service_id, Name) values ('105', 'The Saffron Clove');
insert into restaurant (Service_id, Name) values ('106', 'The Maroon Oregano');
insert into restaurant (Service_id, Name) values ('107', 'The Azure Rosemary');
insert into restaurant (Service_id, Name) values ('108', 'The Saffron Thyme');
insert into restaurant (Service_id, Name) values ('109', 'Heller''s Kitchen');
insert into restaurant (Service_id, Name) values ('110', 'The Cobalt Basil');
insert into restaurant (Service_id, Name) values ('111', 'Heller''s Kitchen');
insert into restaurant (Service_id, Name) values ('112', 'The Azure Rosemary');
insert into restaurant (Service_id, Name) values ('113', 'Stroman''s Kitchen');
insert into restaurant (Service_id, Name) values ('114', 'The Copper Tarragon');
insert into restaurant (Service_id, Name) values ('115', 'The Indigo Lavender');
insert into restaurant (Service_id, Name) values ('116', 'Murray''s Kitchen');
insert into restaurant (Service_id, Name) values ('117', 'The Crimson Thyme');
insert into restaurant (Service_id, Name) values ('118', 'The Indigo Oregano');
insert into restaurant (Service_id, Name) values ('119', 'Rogahn''s Kitchen');
insert into restaurant (Service_id, Name) values ('120', 'The Copper Basil');
insert into restaurant (Service_id, Name) values ('121', 'Boston Bistro');
insert into restaurant (Service_id, Name) values ('122', 'The Golden Tarragon');
insert into restaurant (Service_id, Name) values ('123', 'Barcelona Bistro');
insert into restaurant (Service_id, Name) values ('124', 'Halvorson''s Kitchen');
insert into restaurant (Service_id, Name) values ('125', 'The Amber Rosemary');
insert into restaurant (Service_id, Name) values ('126', 'Schmeler''s Kitchen');
insert into restaurant (Service_id, Name) values ('127', 'The Saffron Thyme');
insert into restaurant (Service_id, Name) values ('128', 'The Crimson Basil');
insert into restaurant (Service_id, Name) values ('129', 'Vienna Bistro');
insert into restaurant (Service_id, Name) values ('130', 'The Copper Tarragon');
insert into restaurant (Service_id, Name) values ('131', 'Boston Bistro');
insert into restaurant (Service_id, Name) values ('132', 'The Scarlet Saffron');
insert into restaurant (Service_id, Name) values ('133', 'Chicago Bistro');
insert into restaurant (Service_id, Name) values ('134', 'The Crimson Saffron');
insert into restaurant (Service_id, Name) values ('135', 'The Azure Oregano');
insert into restaurant (Service_id, Name) values ('136', 'Schmeler''s Kitchen');
insert into restaurant (Service_id, Name) values ('137', 'The Saffron Fennel');
insert into restaurant (Service_id, Name) values ('138', 'The Copper Fennel');
insert into restaurant (Service_id, Name) values ('139', 'The Amber Rosemary');
insert into restaurant (Service_id, Name) values ('140', 'The Ruby Clove');
insert into restaurant (Service_id, Name) values ('141', 'The Copper Fennel');
insert into restaurant (Service_id, Name) values ('142', 'Boston Bistro');
insert into restaurant (Service_id, Name) values ('143', 'The Saffron Clove');
insert into restaurant (Service_id, Name) values ('144', 'The Indigo Oregano');
insert into restaurant (Service_id, Name) values ('145', 'Milan Bistro');
insert into restaurant (Service_id, Name) values ('146', 'The Emerald Clove');
insert into restaurant (Service_id, Name) values ('147', 'The Ruby Thyme');
insert into restaurant (Service_id, Name) values ('148', 'The Saffron Clove');
insert into restaurant (Service_id, Name) values ('149', 'The Jade Fennel');
insert into restaurant (Service_id, Name) values ('150', 'Cole''s Kitchen');
insert into restaurant (Service_id, Name) values ('151', 'Boston Bistro');
insert into restaurant (Service_id, Name) values ('152', 'Roma Bistro');
insert into restaurant (Service_id, Name) values ('153', 'The Crimson Basil');
insert into restaurant (Service_id, Name) values ('154', 'The Cobalt Basil');
insert into restaurant (Service_id, Name) values ('155', 'The Indigo Lavender');
insert into restaurant (Service_id, Name) values ('156', 'The Jade Chive');
insert into restaurant (Service_id, Name) values ('157', 'The Amber Rosemary');
insert into restaurant (Service_id, Name) values ('158', 'The Crimson Basil');
insert into restaurant (Service_id, Name) values ('159', 'The Ruby Mint');
insert into restaurant (Service_id, Name) values ('160', 'The Copper Thyme');
insert into restaurant (Service_id, Name) values ('161', 'The Saffron Fennel');
insert into restaurant (Service_id, Name) values ('162', 'Schmeler''s Kitchen');
insert into restaurant (Service_id, Name) values ('163', 'The Jade Fennel');
insert into restaurant (Service_id, Name) values ('164', 'The Jade Mint');
insert into restaurant (Service_id, Name) values ('165', 'The Ruby Tarragon');
insert into restaurant (Service_id, Name) values ('166', 'The Teal Mint');
insert into restaurant (Service_id, Name) values ('167', 'Blick''s Kitchen');
insert into restaurant (Service_id, Name) values ('168', 'The Saffron Fennel');
insert into restaurant (Service_id, Name) values ('169', 'Stroman''s Kitchen');
insert into restaurant (Service_id, Name) values ('170', 'Murray''s Kitchen');
insert into restaurant (Service_id, Name) values ('171', 'The Cobalt Mint');
insert into restaurant (Service_id, Name) values ('172', 'The Teal Mint');
insert into restaurant (Service_id, Name) values ('173', 'The Crimson Saffron');
insert into restaurant (Service_id, Name) values ('174', 'Miller''s Kitchen');
insert into restaurant (Service_id, Name) values ('175', 'Vienna Bistro');
insert into restaurant (Service_id, Name) values ('176', 'The Copper Tarragon');
insert into restaurant (Service_id, Name) values ('177', 'Rogahn''s Kitchen');
insert into restaurant (Service_id, Name) values ('178', 'The Scarlet Dill');
insert into restaurant (Service_id, Name) values ('179', 'The Jade Mint');
insert into restaurant (Service_id, Name) values ('180', 'The Ruby Thyme');
insert into restaurant (Service_id, Name) values ('181', 'The Indigo Lavender');
insert into restaurant (Service_id, Name) values ('182', 'New York Bistro');
insert into restaurant (Service_id, Name) values ('183', 'The Emerald Thyme');
insert into restaurant (Service_id, Name) values ('184', 'The Teal Mint');
insert into restaurant (Service_id, Name) values ('185', 'Halvorson''s Kitchen');
insert into restaurant (Service_id, Name) values ('186', 'The Azure Oregano');
insert into restaurant (Service_id, Name) values ('187', 'Bayer''s Kitchen');
insert into restaurant (Service_id, Name) values ('188', 'Blick''s Kitchen');
insert into restaurant (Service_id, Name) values ('189', 'The Copper Chive');
insert into restaurant (Service_id, Name) values ('190', 'Beier''s Kitchen');
insert into restaurant (Service_id, Name) values ('191', 'The Copper Tarragon');
insert into restaurant (Service_id, Name) values ('192', 'The Scarlet Saffron');
insert into restaurant (Service_id, Name) values ('193', 'The Scarlet Saffron');
insert into restaurant (Service_id, Name) values ('194', 'The Ivory Mint');
insert into restaurant (Service_id, Name) values ('195', 'Huel''s Kitchen');
insert into restaurant (Service_id, Name) values ('196', 'The Azure Rosemary');
insert into restaurant (Service_id, Name) values ('197', 'The Emerald Tarragon');
insert into restaurant (Service_id, Name) values ('198', 'Denver Bistro');
insert into restaurant (Service_id, Name) values ('199', 'The Ruby Clove');
insert into restaurant (Service_id, Name) values ('200', 'The Teal Ginger');
insert into restaurant (Service_id, Name) values ('201', 'The Jade Tarragon');
insert into restaurant (Service_id, Name) values ('202', 'The Ivory Basil');
insert into restaurant (Service_id, Name) values ('203', 'The Scarlet Saffron');
insert into restaurant (Service_id, Name) values ('204', 'The Teal Ginger');
insert into restaurant (Service_id, Name) values ('205', 'The Emerald Thyme');
insert into restaurant (Service_id, Name) values ('206', 'The Saffron Thyme');
insert into restaurant (Service_id, Name) values ('207', 'The Crimson Thyme');
insert into restaurant (Service_id, Name) values ('208', 'Wilkinson''s Kitchen');
insert into restaurant (Service_id, Name) values ('209', 'The Crimson Saffron');
insert into restaurant (Service_id, Name) values ('210', 'The Maroon Clove');
insert into restaurant (Service_id, Name) values ('211', 'Blick''s Kitchen');
insert into restaurant (Service_id, Name) values ('212', 'Kyoto Bistro');
insert into restaurant (Service_id, Name) values ('213', 'Dach''s Kitchen');
insert into restaurant (Service_id, Name) values ('214', 'Dickens''s Kitchen');
insert into restaurant (Service_id, Name) values ('215', 'Breitenberg''s Kitchen');
insert into restaurant (Service_id, Name) values ('216', 'Paris Bistro');
insert into restaurant (Service_id, Name) values ('217', 'The Teal Saffron');
insert into restaurant (Service_id, Name) values ('218', 'Chicago Bistro');
insert into restaurant (Service_id, Name) values ('219', 'The Saffron Mint');
insert into restaurant (Service_id, Name) values ('220', 'Zulauf''s Kitchen');
insert into restaurant (Service_id, Name) values ('221', 'The Copper Thyme');
insert into restaurant (Service_id, Name) values ('222', 'Breitenberg''s Kitchen');
insert into restaurant (Service_id, Name) values ('223', 'Rogahn''s Kitchen');
insert into restaurant (Service_id, Name) values ('224', 'Austin Bistro');
insert into restaurant (Service_id, Name) values ('225', 'Vienna Bistro');
insert into restaurant (Service_id, Name) values ('226', 'Glover''s Kitchen');
insert into restaurant (Service_id, Name) values ('227', 'The Indigo Oregano');
insert into restaurant (Service_id, Name) values ('228', 'Wilkinson''s Kitchen');
insert into restaurant (Service_id, Name) values ('229', 'The Maroon Fennel');
insert into restaurant (Service_id, Name) values ('230', 'The Azure Oregano');
insert into restaurant (Service_id, Name) values ('231', 'The Emerald Tarragon');
insert into restaurant (Service_id, Name) values ('232', 'O''Keefe''s Kitchen');
insert into restaurant (Service_id, Name) values ('233', 'The Golden Fennel');
insert into restaurant (Service_id, Name) values ('234', 'Casper''s Kitchen');
insert into restaurant (Service_id, Name) values ('235', 'The Crimson Saffron');
insert into restaurant (Service_id, Name) values ('236', 'Denver Bistro');
insert into restaurant (Service_id, Name) values ('237', 'Zulauf''s Kitchen');
insert into restaurant (Service_id, Name) values ('238', 'The Emerald Thyme');
insert into restaurant (Service_id, Name) values ('239', 'Glover''s Kitchen');
insert into restaurant (Service_id, Name) values ('240', 'Zulauf''s Kitchen');
insert into restaurant (Service_id, Name) values ('241', 'Dach''s Kitchen');
insert into restaurant (Service_id, Name) values ('242', 'Lesch''s Kitchen');
insert into restaurant (Service_id, Name) values ('243', 'The Golden Fennel');
insert into restaurant (Service_id, Name) values ('244', 'The Copper Fennel');
insert into restaurant (Service_id, Name) values ('245', 'The Golden Basil');
insert into restaurant (Service_id, Name) values ('246', 'Bayer''s Kitchen');
insert into restaurant (Service_id, Name) values ('247', 'Gislason''s Kitchen');
insert into restaurant (Service_id, Name) values ('248', 'The Ruby Clove');
insert into restaurant (Service_id, Name) values ('249', 'The Cobalt Oregano');
insert into restaurant (Service_id, Name) values ('250', 'Cummerata''s Kitchen');
insert into restaurant (Service_id, Name) values ('251', 'The Azure Rosemary');
insert into restaurant (Service_id, Name) values ('252', 'Padberg''s Kitchen');
insert into restaurant (Service_id, Name) values ('253', 'Lesch''s Kitchen');
insert into restaurant (Service_id, Name) values ('254', 'The Ivory Mint');
insert into restaurant (Service_id, Name) values ('255', 'Sydney Bistro');
insert into restaurant (Service_id, Name) values ('256', 'The Cobalt Basil');
insert into restaurant (Service_id, Name) values ('257', 'Bayer''s Kitchen');
insert into restaurant (Service_id, Name) values ('258', 'Denver Bistro');
insert into restaurant (Service_id, Name) values ('259', 'The Copper Dill');
insert into restaurant (Service_id, Name) values ('260', 'Bayer''s Kitchen');
insert into restaurant (Service_id, Name) values ('261', 'The Scarlet Thyme');
insert into restaurant (Service_id, Name) values ('262', 'The Azure Oregano');
insert into restaurant (Service_id, Name) values ('263', 'The Maroon Clove');
insert into restaurant (Service_id, Name) values ('264', 'The Ruby Thyme');
insert into restaurant (Service_id, Name) values ('265', 'The Jade Rosemary');
insert into restaurant (Service_id, Name) values ('266', 'The Ruby Clove');
insert into restaurant (Service_id, Name) values ('267', 'The Saffron Clove');
insert into restaurant (Service_id, Name) values ('268', 'Austin Bistro');
insert into restaurant (Service_id, Name) values ('269', 'The Copper Chive');
insert into restaurant (Service_id, Name) values ('270', 'New York Bistro');
insert into restaurant (Service_id, Name) values ('271', 'The Maroon Fennel');
insert into restaurant (Service_id, Name) values ('272', 'The Cobalt Mint');
insert into restaurant (Service_id, Name) values ('273', 'The Jade Rosemary');
insert into restaurant (Service_id, Name) values ('274', 'Stroman''s Kitchen');
insert into restaurant (Service_id, Name) values ('275', 'The Saffron Fennel');
insert into restaurant (Service_id, Name) values ('276', 'The Scarlet Thyme');
insert into restaurant (Service_id, Name) values ('277', 'The Cobalt Oregano');
insert into restaurant (Service_id, Name) values ('278', 'Casper''s Kitchen');
insert into restaurant (Service_id, Name) values ('279', 'Milan Bistro');
insert into restaurant (Service_id, Name) values ('280', 'The Ivory Basil');
insert into restaurant (Service_id, Name) values ('281', 'Cole''s Kitchen');
insert into restaurant (Service_id, Name) values ('282', 'The Scarlet Saffron');
insert into restaurant (Service_id, Name) values ('283', 'Gislason''s Kitchen');
insert into restaurant (Service_id, Name) values ('284', 'Paris Bistro');
insert into restaurant (Service_id, Name) values ('285', 'Rogahn''s Kitchen');
insert into restaurant (Service_id, Name) values ('286', 'The Jade Mint');
insert into restaurant (Service_id, Name) values ('287', 'The Jade Tarragon');
insert into restaurant (Service_id, Name) values ('288', 'The Crimson Saffron');
insert into restaurant (Service_id, Name) values ('289', 'The Jade Chive');
insert into restaurant (Service_id, Name) values ('290', 'The Maroon Oregano');
insert into restaurant (Service_id, Name) values ('291', 'Chicago Bistro');
insert into restaurant (Service_id, Name) values ('292', 'The Ruby Mint');
insert into restaurant (Service_id, Name) values ('293', 'The Azure Oregano');
insert into restaurant (Service_id, Name) values ('294', 'Dach''s Kitchen');
insert into restaurant (Service_id, Name) values ('295', 'The Cobalt Saffron');
insert into restaurant (Service_id, Name) values ('296', 'Padberg''s Kitchen');
insert into restaurant (Service_id, Name) values ('297', 'The Copper Dill');
insert into restaurant (Service_id, Name) values ('298', 'Murray''s Kitchen');
insert into restaurant (Service_id, Name) values ('299', 'Johnston''s Kitchen');
insert into restaurant (Service_id, Name) values ('300', 'Dach''s Kitchen');
insert into restaurant (Service_id, Name) values ('301', 'The Scarlet Saffron');
insert into restaurant (Service_id, Name) values ('302', 'Halvorson''s Kitchen');
insert into restaurant (Service_id, Name) values ('303', 'The Scarlet Thyme');
insert into restaurant (Service_id, Name) values ('304', 'Williamson''s Kitchen');
insert into restaurant (Service_id, Name) values ('305', 'The Jade Fennel');
insert into restaurant (Service_id, Name) values ('306', 'Rogahn''s Kitchen');
insert into restaurant (Service_id, Name) values ('307', 'The Crimson Basil');
insert into restaurant (Service_id, Name) values ('308', 'The Ruby Clove');
insert into restaurant (Service_id, Name) values ('309', 'Dach''s Kitchen');
insert into restaurant (Service_id, Name) values ('310', 'Boston Bistro');
insert into restaurant (Service_id, Name) values ('311', 'The Golden Tarragon');
insert into restaurant (Service_id, Name) values ('312', 'Cummerata''s Kitchen');
insert into restaurant (Service_id, Name) values ('313', 'The Maroon Oregano');
insert into restaurant (Service_id, Name) values ('314', 'The Ruby Clove');
insert into restaurant (Service_id, Name) values ('315', 'Milan Bistro');
insert into restaurant (Service_id, Name) values ('316', 'Paris Bistro');
insert into restaurant (Service_id, Name) values ('317', 'The Jade Fennel');
insert into restaurant (Service_id, Name) values ('318', 'Barcelona Bistro');
insert into restaurant (Service_id, Name) values ('319', 'The Indigo Ginger');
insert into restaurant (Service_id, Name) values ('320', 'The Crimson Thyme');
insert into restaurant (Service_id, Name) values ('321', 'The Copper Basil');
insert into restaurant (Service_id, Name) values ('322', 'Wilkinson''s Kitchen');
insert into restaurant (Service_id, Name) values ('323', 'The Golden Fennel');
insert into restaurant (Service_id, Name) values ('324', 'The Saffron Mint');
insert into restaurant (Service_id, Name) values ('325', 'The Saffron Mint');
insert into restaurant (Service_id, Name) values ('326', 'Miller''s Kitchen');
insert into restaurant (Service_id, Name) values ('327', 'The Golden Fennel');
insert into restaurant (Service_id, Name) values ('328', 'Sydney Bistro');
insert into restaurant (Service_id, Name) values ('329', 'The Golden Basil');
insert into restaurant (Service_id, Name) values ('330', 'The Ruby Thyme');
insert into restaurant (Service_id, Name) values ('331', 'Denver Bistro');
insert into restaurant (Service_id, Name) values ('332', 'Austin Bistro');
insert into restaurant (Service_id, Name) values ('333', 'The Saffron Clove');
insert into restaurant (Service_id, Name) values ('334', 'The Jade Fennel');
insert into restaurant (Service_id, Name) values ('335', 'The Golden Tarragon');
insert into restaurant (Service_id, Name) values ('336', 'The Azure Oregano');
insert into restaurant (Service_id, Name) values ('337', 'The Cobalt Dill');
insert into restaurant (Service_id, Name) values ('338', 'The Teal Oregano');
insert into restaurant (Service_id, Name) values ('339', 'The Crimson Saffron');
insert into restaurant (Service_id, Name) values ('340', 'The Jade Rosemary');
insert into restaurant (Service_id, Name) values ('341', 'Cole''s Kitchen');
insert into restaurant (Service_id, Name) values ('342', 'The Amber Rosemary');
insert into restaurant (Service_id, Name) values ('343', 'Austin Bistro');
insert into restaurant (Service_id, Name) values ('344', 'The Cobalt Dill');
insert into restaurant (Service_id, Name) values ('345', 'Miami Bistro');
insert into restaurant (Service_id, Name) values ('346', 'The Onyx Fennel');
insert into restaurant (Service_id, Name) values ('347', 'The Jade Rosemary');
insert into restaurant (Service_id, Name) values ('348', 'The Amber Rosemary');
insert into restaurant (Service_id, Name) values ('349', 'Williamson''s Kitchen');
insert into restaurant (Service_id, Name) values ('350', 'Huel''s Kitchen');
insert into restaurant (Service_id, Name) values ('351', 'The Emerald Tarragon');
insert into restaurant (Service_id, Name) values ('352', 'Miller''s Kitchen');
insert into restaurant (Service_id, Name) values ('353', 'London Bistro');
insert into restaurant (Service_id, Name) values ('354', 'Heller''s Kitchen');
insert into restaurant (Service_id, Name) values ('355', 'The Copper Ginger');
insert into restaurant (Service_id, Name) values ('356', 'Blick''s Kitchen');
insert into restaurant (Service_id, Name) values ('357', 'The Scarlet Saffron');
insert into restaurant (Service_id, Name) values ('358', 'The Copper Basil');
insert into restaurant (Service_id, Name) values ('359', 'The Amber Ginger');
insert into restaurant (Service_id, Name) values ('360', 'The Golden Tarragon');
insert into restaurant (Service_id, Name) values ('361', 'The Jade Fennel');
insert into restaurant (Service_id, Name) values ('362', 'The Amber Ginger');
insert into restaurant (Service_id, Name) values ('363', 'Halvorson''s Kitchen');
insert into restaurant (Service_id, Name) values ('364', 'Miami Bistro');
insert into restaurant (Service_id, Name) values ('365', 'Tokyo Bistro');
insert into restaurant (Service_id, Name) values ('366', 'Huel''s Kitchen');
insert into restaurant (Service_id, Name) values ('367', 'The Copper Chive');
insert into restaurant (Service_id, Name) values ('368', 'The Cobalt Basil');
insert into restaurant (Service_id, Name) values ('369', 'The Copper Chive');
insert into restaurant (Service_id, Name) values ('370', 'Wilkinson''s Kitchen');
insert into restaurant (Service_id, Name) values ('371', 'The Saffron Clove');
insert into restaurant (Service_id, Name) values ('372', 'Breitenberg''s Kitchen');
insert into restaurant (Service_id, Name) values ('373', 'The Amber Ginger');
insert into restaurant (Service_id, Name) values ('374', 'Austin Bistro');
insert into restaurant (Service_id, Name) values ('375', 'The Copper Ginger');
insert into restaurant (Service_id, Name) values ('376', 'Gislason''s Kitchen');
insert into restaurant (Service_id, Name) values ('377', 'Breitenberg''s Kitchen');
insert into restaurant (Service_id, Name) values ('378', 'London Bistro');
insert into restaurant (Service_id, Name) values ('379', 'The Teal Ginger');
insert into restaurant (Service_id, Name) values ('380', 'The Saffron Clove');
insert into restaurant (Service_id, Name) values ('381', 'The Onyx Fennel');
insert into restaurant (Service_id, Name) values ('382', 'Denver Bistro');
insert into restaurant (Service_id, Name) values ('383', 'The Cobalt Dill');
insert into restaurant (Service_id, Name) values ('384', 'The Golden Chive');
insert into restaurant (Service_id, Name) values ('385', 'Cummerata''s Kitchen');
insert into restaurant (Service_id, Name) values ('386', 'Stroman''s Kitchen');
insert into restaurant (Service_id, Name) values ('387', 'Casper''s Kitchen');
insert into restaurant (Service_id, Name) values ('388', 'The Golden Fennel');
insert into restaurant (Service_id, Name) values ('389', 'The Emerald Clove');
insert into restaurant (Service_id, Name) values ('390', 'Roma Bistro');
insert into restaurant (Service_id, Name) values ('391', 'The Jade Rosemary');
insert into restaurant (Service_id, Name) values ('392', 'Zulauf''s Kitchen');
insert into restaurant (Service_id, Name) values ('393', 'Wilkinson''s Kitchen');
insert into restaurant (Service_id, Name) values ('394', 'The Indigo Oregano');
insert into restaurant (Service_id, Name) values ('395', 'Walter''s Kitchen');
insert into restaurant (Service_id, Name) values ('396', 'Williamson''s Kitchen');
insert into restaurant (Service_id, Name) values ('397', 'Sydney Bistro');
insert into restaurant (Service_id, Name) values ('398', 'Boston Bistro');
insert into restaurant (Service_id, Name) values ('399', 'Miller''s Kitchen');
insert into restaurant (Service_id, Name) values ('400', 'Dickens''s Kitchen');
insert into restaurant (Service_id, Name) values ('401', 'The Amber Ginger');
insert into restaurant (Service_id, Name) values ('402', 'The Cobalt Basil');
insert into restaurant (Service_id, Name) values ('403', 'The Saffron Thyme');
insert into restaurant (Service_id, Name) values ('404', 'The Indigo Ginger');
insert into restaurant (Service_id, Name) values ('405', 'Heller''s Kitchen');
insert into restaurant (Service_id, Name) values ('406', 'Dach''s Kitchen');
insert into restaurant (Service_id, Name) values ('407', 'The Crimson Thyme');
insert into restaurant (Service_id, Name) values ('408', 'The Jade Mint');
insert into restaurant (Service_id, Name) values ('409', 'The Saffron Thyme');
insert into restaurant (Service_id, Name) values ('410', 'The Teal Oregano');
insert into restaurant (Service_id, Name) values ('411', 'O''Keefe''s Kitchen');
insert into restaurant (Service_id, Name) values ('412', 'The Indigo Oregano');
insert into restaurant (Service_id, Name) values ('413', 'Dickens''s Kitchen');
insert into restaurant (Service_id, Name) values ('414', 'The Saffron Fennel');
insert into restaurant (Service_id, Name) values ('415', 'The Crimson Thyme');
insert into restaurant (Service_id, Name) values ('416', 'The Scarlet Thyme');
insert into restaurant (Service_id, Name) values ('417', 'The Ivory Basil');
insert into restaurant (Service_id, Name) values ('418', 'The Copper Fennel');
insert into restaurant (Service_id, Name) values ('419', 'The Saffron Mint');
insert into restaurant (Service_id, Name) values ('420', 'The Azure Rosemary');
insert into restaurant (Service_id, Name) values ('421', 'Cole''s Kitchen');
insert into restaurant (Service_id, Name) values ('422', 'Johnston''s Kitchen');
insert into restaurant (Service_id, Name) values ('423', 'The Cobalt Basil');
insert into restaurant (Service_id, Name) values ('424', 'Madrid Bistro');
insert into restaurant (Service_id, Name) values ('425', 'The Azure Rosemary');
insert into restaurant (Service_id, Name) values ('426', 'Zulauf''s Kitchen');
insert into restaurant (Service_id, Name) values ('427', 'The Copper Thyme');
insert into restaurant (Service_id, Name) values ('428', 'The Saffron Fennel');
insert into restaurant (Service_id, Name) values ('429', 'The Jade Chive');
insert into restaurant (Service_id, Name) values ('430', 'The Golden Tarragon');
insert into restaurant (Service_id, Name) values ('431', 'Paris Bistro');
insert into restaurant (Service_id, Name) values ('432', 'Johnston''s Kitchen');
insert into restaurant (Service_id, Name) values ('433', 'Bayer''s Kitchen');
insert into restaurant (Service_id, Name) values ('434', 'Murray''s Kitchen');
insert into restaurant (Service_id, Name) values ('435', 'Cole''s Kitchen');
insert into restaurant (Service_id, Name) values ('436', 'Roma Bistro');
insert into restaurant (Service_id, Name) values ('437', 'The Cobalt Dill');
insert into restaurant (Service_id, Name) values ('438', 'The Maroon Clove');
insert into restaurant (Service_id, Name) values ('439', 'The Jade Tarragon');
insert into restaurant (Service_id, Name) values ('440', 'Murray''s Kitchen');
insert into restaurant (Service_id, Name) values ('441', 'The Teal Oregano');
insert into restaurant (Service_id, Name) values ('442', 'The Emerald Clove');
insert into restaurant (Service_id, Name) values ('443', 'Denver Bistro');
insert into restaurant (Service_id, Name) values ('444', 'New York Bistro');
insert into restaurant (Service_id, Name) values ('445', 'New York Bistro');
insert into restaurant (Service_id, Name) values ('446', 'Paris Bistro');
insert into restaurant (Service_id, Name) values ('447', 'Vienna Bistro');
insert into restaurant (Service_id, Name) values ('448', 'The Copper Chive');
insert into restaurant (Service_id, Name) values ('449', 'The Indigo Oregano');
insert into restaurant (Service_id, Name) values ('450', 'The Jade Rosemary');
insert into restaurant (Service_id, Name) values ('451', 'The Teal Ginger');
insert into restaurant (Service_id, Name) values ('452', 'Dach''s Kitchen');
insert into restaurant (Service_id, Name) values ('453', 'Casper''s Kitchen');
insert into restaurant (Service_id, Name) values ('454', 'Halvorson''s Kitchen');
insert into restaurant (Service_id, Name) values ('455', 'Cole''s Kitchen');
insert into restaurant (Service_id, Name) values ('456', 'The Jade Rosemary');
insert into restaurant (Service_id, Name) values ('457', 'The Onyx Fennel');
insert into restaurant (Service_id, Name) values ('458', 'Halvorson''s Kitchen');
insert into restaurant (Service_id, Name) values ('459', 'Tokyo Bistro');
insert into restaurant (Service_id, Name) values ('460', 'Dach''s Kitchen');
insert into restaurant (Service_id, Name) values ('461', 'The Cobalt Mint');
insert into restaurant (Service_id, Name) values ('462', 'Walter''s Kitchen');
insert into restaurant (Service_id, Name) values ('463', 'The Copper Thyme');
insert into restaurant (Service_id, Name) values ('464', 'The Emerald Tarragon');
insert into restaurant (Service_id, Name) values ('465', 'Schmeler''s Kitchen');
insert into restaurant (Service_id, Name) values ('466', 'The Emerald Tarragon');
insert into restaurant (Service_id, Name) values ('467', 'The Amber Ginger');
insert into restaurant (Service_id, Name) values ('468', 'The Crimson Saffron');
insert into restaurant (Service_id, Name) values ('469', 'Miami Bistro');
insert into restaurant (Service_id, Name) values ('470', 'Huel''s Kitchen');
insert into restaurant (Service_id, Name) values ('471', 'Madrid Bistro');
insert into restaurant (Service_id, Name) values ('472', 'Zulauf''s Kitchen');
insert into restaurant (Service_id, Name) values ('473', 'The Emerald Thyme');
insert into restaurant (Service_id, Name) values ('474', 'The Ruby Mint');
insert into restaurant (Service_id, Name) values ('475', 'The Copper Tarragon');
insert into restaurant (Service_id, Name) values ('476', 'Sydney Bistro');
insert into restaurant (Service_id, Name) values ('477', 'The Saffron Fennel');
insert into restaurant (Service_id, Name) values ('478', 'The Saffron Fennel');
insert into restaurant (Service_id, Name) values ('479', 'Kyoto Bistro');
insert into restaurant (Service_id, Name) values ('480', 'The Teal Mint');
insert into restaurant (Service_id, Name) values ('481', 'The Crimson Thyme');
insert into restaurant (Service_id, Name) values ('482', 'The Emerald Clove');
insert into restaurant (Service_id, Name) values ('483', 'Heller''s Kitchen');
insert into restaurant (Service_id, Name) values ('484', 'New York Bistro');
insert into restaurant (Service_id, Name) values ('485', 'The Golden Basil');
insert into restaurant (Service_id, Name) values ('486', 'The Copper Basil');
insert into restaurant (Service_id, Name) values ('487', 'The Jade Chive');
insert into restaurant (Service_id, Name) values ('488', 'The Maroon Oregano');
insert into restaurant (Service_id, Name) values ('489', 'Miller''s Kitchen');
insert into restaurant (Service_id, Name) values ('490', 'Wilkinson''s Kitchen');
insert into restaurant (Service_id, Name) values ('491', 'Glover''s Kitchen');
insert into restaurant (Service_id, Name) values ('492', 'The Jade Mint');
insert into restaurant (Service_id, Name) values ('493', 'The Maroon Fennel');
insert into restaurant (Service_id, Name) values ('494', 'The Saffron Clove');
insert into restaurant (Service_id, Name) values ('495', 'Murray''s Kitchen');
insert into restaurant (Service_id, Name) values ('496', 'The Copper Tarragon');
insert into restaurant (Service_id, Name) values ('497', 'The Cobalt Saffron');
insert into restaurant (Service_id, Name) values ('498', 'The Cobalt Basil');
insert into restaurant (Service_id, Name) values ('499', 'Breitenberg''s Kitchen');
insert into restaurant (Service_id, Name) values ('500', 'Boston Bistro');
insert into restaurant (Service_id, Name) values ('501', 'The Copper Tarragon');
insert into restaurant (Service_id, Name) values ('502', 'Roma Bistro');
insert into restaurant (Service_id, Name) values ('503', 'Barcelona Bistro');
insert into restaurant (Service_id, Name) values ('504', 'The Crimson Basil');
insert into restaurant (Service_id, Name) values ('505', 'The Amber Rosemary');
insert into restaurant (Service_id, Name) values ('506', 'The Ruby Tarragon');
insert into restaurant (Service_id, Name) values ('507', 'The Ruby Chive');
insert into restaurant (Service_id, Name) values ('508', 'Bayer''s Kitchen');
insert into restaurant (Service_id, Name) values ('509', 'The Jade Tarragon');
insert into restaurant (Service_id, Name) values ('510', 'Murray''s Kitchen');
insert into restaurant (Service_id, Name) values ('511', 'Milan Bistro');
insert into restaurant (Service_id, Name) values ('512', 'Breitenberg''s Kitchen');
insert into restaurant (Service_id, Name) values ('513', 'The Cobalt Mint');
insert into restaurant (Service_id, Name) values ('514', 'The Crimson Basil');
insert into restaurant (Service_id, Name) values ('515', 'Stroman''s Kitchen');
insert into restaurant (Service_id, Name) values ('516', 'The Golden Basil');
insert into restaurant (Service_id, Name) values ('517', 'Heller''s Kitchen');
insert into restaurant (Service_id, Name) values ('518', 'The Indigo Oregano');
insert into restaurant (Service_id, Name) values ('519', 'The Scarlet Thyme');
insert into restaurant (Service_id, Name) values ('520', 'The Ivory Mint');
insert into restaurant (Service_id, Name) values ('521', 'Madrid Bistro');
insert into restaurant (Service_id, Name) values ('522', 'The Teal Saffron');
insert into restaurant (Service_id, Name) values ('523', 'Vienna Bistro');
insert into restaurant (Service_id, Name) values ('524', 'Chicago Bistro');
insert into restaurant (Service_id, Name) values ('525', 'The Crimson Basil');
insert into restaurant (Service_id, Name) values ('526', 'The Azure Oregano');
insert into restaurant (Service_id, Name) values ('527', 'The Ruby Tarragon');
insert into restaurant (Service_id, Name) values ('528', 'The Copper Fennel');
insert into restaurant (Service_id, Name) values ('529', 'Sydney Bistro');
insert into restaurant (Service_id, Name) values ('530', 'Paris Bistro');
insert into restaurant (Service_id, Name) values ('531', 'The Golden Basil');
insert into restaurant (Service_id, Name) values ('532', 'O''Keefe''s Kitchen');
insert into restaurant (Service_id, Name) values ('533', 'Boston Bistro');
insert into restaurant (Service_id, Name) values ('534', 'Dickens''s Kitchen');
insert into restaurant (Service_id, Name) values ('535', 'The Azure Rosemary');
insert into restaurant (Service_id, Name) values ('536', 'Padberg''s Kitchen');
insert into restaurant (Service_id, Name) values ('537', 'Cole''s Kitchen');
insert into restaurant (Service_id, Name) values ('538', 'Glover''s Kitchen');
insert into restaurant (Service_id, Name) values ('539', 'Dach''s Kitchen');
insert into restaurant (Service_id, Name) values ('540', 'Breitenberg''s Kitchen');
insert into restaurant (Service_id, Name) values ('541', 'The Crimson Thyme');
insert into restaurant (Service_id, Name) values ('542', 'Madrid Bistro');
insert into restaurant (Service_id, Name) values ('543', 'Barcelona Bistro');
insert into restaurant (Service_id, Name) values ('544', 'The Cobalt Dill');
insert into restaurant (Service_id, Name) values ('545', 'Austin Bistro');
insert into restaurant (Service_id, Name) values ('546', 'Cole''s Kitchen');
insert into restaurant (Service_id, Name) values ('547', 'Walter''s Kitchen');
insert into restaurant (Service_id, Name) values ('548', 'The Ruby Clove');
insert into restaurant (Service_id, Name) values ('549', 'Bayer''s Kitchen');
insert into restaurant (Service_id, Name) values ('550', 'The Scarlet Saffron');
insert into restaurant (Service_id, Name) values ('551', 'Tokyo Bistro');
insert into restaurant (Service_id, Name) values ('552', 'Boston Bistro');
insert into restaurant (Service_id, Name) values ('553', 'The Golden Basil');
insert into restaurant (Service_id, Name) values ('554', 'The Scarlet Saffron');
insert into restaurant (Service_id, Name) values ('555', 'The Golden Basil');
insert into restaurant (Service_id, Name) values ('556', 'The Indigo Oregano');
insert into restaurant (Service_id, Name) values ('557', 'The Golden Chive');
insert into restaurant (Service_id, Name) values ('558', 'The Jade Tarragon');
insert into restaurant (Service_id, Name) values ('559', 'The Emerald Tarragon');
insert into restaurant (Service_id, Name) values ('560', 'Sydney Bistro');
insert into restaurant (Service_id, Name) values ('561', 'The Cobalt Oregano');
insert into restaurant (Service_id, Name) values ('562', 'The Cobalt Saffron');
insert into restaurant (Service_id, Name) values ('563', 'Beier''s Kitchen');
insert into restaurant (Service_id, Name) values ('564', 'The Cobalt Saffron');
insert into restaurant (Service_id, Name) values ('565', 'The Copper Tarragon');
insert into restaurant (Service_id, Name) values ('566', 'Wilkinson''s Kitchen');
insert into restaurant (Service_id, Name) values ('567', 'The Copper Tarragon');
insert into restaurant (Service_id, Name) values ('568', 'The Teal Mint');
insert into restaurant (Service_id, Name) values ('569', 'The Golden Basil');
insert into restaurant (Service_id, Name) values ('570', 'The Onyx Lavender');
insert into restaurant (Service_id, Name) values ('571', 'The Maroon Fennel');
insert into restaurant (Service_id, Name) values ('572', 'The Copper Dill');
insert into restaurant (Service_id, Name) values ('573', 'The Indigo Lavender');
insert into restaurant (Service_id, Name) values ('574', 'Tokyo Bistro');
insert into restaurant (Service_id, Name) values ('575', 'The Cobalt Dill');
insert into restaurant (Service_id, Name) values ('576', 'The Emerald Thyme');
insert into restaurant (Service_id, Name) values ('577', 'The Ruby Chive');
insert into restaurant (Service_id, Name) values ('578', 'Breitenberg''s Kitchen');
insert into restaurant (Service_id, Name) values ('579', 'Schmeler''s Kitchen');
insert into restaurant (Service_id, Name) values ('580', 'The Ruby Chive');
insert into restaurant (Service_id, Name) values ('581', 'The Jade Rosemary');
insert into restaurant (Service_id, Name) values ('582', 'Wilkinson''s Kitchen');
insert into restaurant (Service_id, Name) values ('583', 'The Scarlet Thyme');
insert into restaurant (Service_id, Name) values ('584', 'The Cobalt Saffron');
insert into restaurant (Service_id, Name) values ('585', 'Beier''s Kitchen');
insert into restaurant (Service_id, Name) values ('586', 'Johnston''s Kitchen');
insert into restaurant (Service_id, Name) values ('587', 'Sydney Bistro');
insert into restaurant (Service_id, Name) values ('588', 'Kyoto Bistro');
insert into restaurant (Service_id, Name) values ('589', 'The Jade Fennel');
insert into restaurant (Service_id, Name) values ('590', 'The Jade Tarragon');
insert into restaurant (Service_id, Name) values ('591', 'Wilkinson''s Kitchen');
insert into restaurant (Service_id, Name) values ('592', 'Cole''s Kitchen');
insert into restaurant (Service_id, Name) values ('593', 'Williamson''s Kitchen');
insert into restaurant (Service_id, Name) values ('594', 'The Copper Ginger');
insert into restaurant (Service_id, Name) values ('595', 'Chicago Bistro');
insert into restaurant (Service_id, Name) values ('596', 'Chicago Bistro');
insert into restaurant (Service_id, Name) values ('597', 'Lesch''s Kitchen');
insert into restaurant (Service_id, Name) values ('598', 'Gislason''s Kitchen');
insert into restaurant (Service_id, Name) values ('599', 'The Copper Thyme');
insert into restaurant (Service_id, Name) values ('600', 'Williamson''s Kitchen');
insert into restaurant (Service_id, Name) values ('601', 'The Jade Mint');
insert into restaurant (Service_id, Name) values ('602', 'Austin Bistro');
insert into restaurant (Service_id, Name) values ('603', 'The Golden Tarragon');
insert into restaurant (Service_id, Name) values ('604', 'Sydney Bistro');
insert into restaurant (Service_id, Name) values ('605', 'The Indigo Lavender');
insert into restaurant (Service_id, Name) values ('606', 'The Maroon Clove');
insert into restaurant (Service_id, Name) values ('607', 'The Teal Mint');
insert into restaurant (Service_id, Name) values ('608', 'The Jade Rosemary');
insert into restaurant (Service_id, Name) values ('609', 'Murray''s Kitchen');
insert into restaurant (Service_id, Name) values ('610', 'Barcelona Bistro');
insert into restaurant (Service_id, Name) values ('611', 'The Scarlet Dill');
insert into restaurant (Service_id, Name) values ('612', 'The Scarlet Thyme');
insert into restaurant (Service_id, Name) values ('613', 'Halvorson''s Kitchen');
insert into restaurant (Service_id, Name) values ('614', 'The Ruby Clove');
insert into restaurant (Service_id, Name) values ('615', 'Wilkinson''s Kitchen');
insert into restaurant (Service_id, Name) values ('616', 'The Copper Dill');
insert into restaurant (Service_id, Name) values ('617', 'Murray''s Kitchen');
insert into restaurant (Service_id, Name) values ('618', 'Schmeler''s Kitchen');
insert into restaurant (Service_id, Name) values ('619', 'O''Keefe''s Kitchen');
insert into restaurant (Service_id, Name) values ('620', 'The Maroon Clove');
insert into restaurant (Service_id, Name) values ('621', 'The Copper Ginger');
insert into restaurant (Service_id, Name) values ('622', 'The Jade Mint');
insert into restaurant (Service_id, Name) values ('623', 'Kyoto Bistro');
insert into restaurant (Service_id, Name) values ('624', 'Cole''s Kitchen');
insert into restaurant (Service_id, Name) values ('625', 'Huel''s Kitchen');
insert into restaurant (Service_id, Name) values ('626', 'The Onyx Lavender');
insert into restaurant (Service_id, Name) values ('627', 'The Crimson Thyme');
insert into restaurant (Service_id, Name) values ('628', 'The Crimson Thyme');
insert into restaurant (Service_id, Name) values ('629', 'Rogahn''s Kitchen');
insert into restaurant (Service_id, Name) values ('630', 'The Azure Oregano');
insert into restaurant (Service_id, Name) values ('631', 'Madrid Bistro');
insert into restaurant (Service_id, Name) values ('632', 'Halvorson''s Kitchen');
insert into restaurant (Service_id, Name) values ('633', 'The Amber Rosemary');
insert into restaurant (Service_id, Name) values ('634', 'London Bistro');
insert into restaurant (Service_id, Name) values ('635', 'Huel''s Kitchen');
insert into restaurant (Service_id, Name) values ('636', 'The Crimson Thyme');
insert into restaurant (Service_id, Name) values ('637', 'The Indigo Lavender');
insert into restaurant (Service_id, Name) values ('638', 'Glover''s Kitchen');
insert into restaurant (Service_id, Name) values ('639', 'The Ruby Mint');
insert into restaurant (Service_id, Name) values ('640', 'The Copper Dill');
insert into restaurant (Service_id, Name) values ('641', 'The Amber Ginger');
insert into restaurant (Service_id, Name) values ('642', 'The Indigo Oregano');
insert into restaurant (Service_id, Name) values ('643', 'The Crimson Basil');
insert into restaurant (Service_id, Name) values ('644', 'The Onyx Lavender');
insert into restaurant (Service_id, Name) values ('645', 'The Maroon Fennel');
insert into restaurant (Service_id, Name) values ('646', 'The Teal Saffron');
insert into restaurant (Service_id, Name) values ('647', 'The Indigo Ginger');
insert into restaurant (Service_id, Name) values ('648', 'The Emerald Tarragon');
insert into restaurant (Service_id, Name) values ('649', 'Blick''s Kitchen');
insert into restaurant (Service_id, Name) values ('650', 'The Teal Saffron');
insert into restaurant (Service_id, Name) values ('651', 'Halvorson''s Kitchen');
insert into restaurant (Service_id, Name) values ('652', 'New York Bistro');
insert into restaurant (Service_id, Name) values ('653', 'The Golden Chive');
insert into restaurant (Service_id, Name) values ('654', 'The Teal Mint');
insert into restaurant (Service_id, Name) values ('655', 'The Cobalt Basil');
insert into restaurant (Service_id, Name) values ('656', 'The Scarlet Thyme');
insert into restaurant (Service_id, Name) values ('657', 'The Scarlet Thyme');
insert into restaurant (Service_id, Name) values ('658', 'Dickens''s Kitchen');
insert into restaurant (Service_id, Name) values ('659', 'The Cobalt Saffron');
insert into restaurant (Service_id, Name) values ('660', 'Austin Bistro');
insert into restaurant (Service_id, Name) values ('661', 'The Indigo Lavender');
insert into restaurant (Service_id, Name) values ('662', 'Wilkinson''s Kitchen');
insert into restaurant (Service_id, Name) values ('663', 'The Crimson Thyme');
insert into restaurant (Service_id, Name) values ('664', 'Miller''s Kitchen');
insert into restaurant (Service_id, Name) values ('665', 'The Ivory Basil');
insert into restaurant (Service_id, Name) values ('666', 'The Jade Rosemary');
insert into restaurant (Service_id, Name) values ('667', 'The Saffron Mint');
insert into restaurant (Service_id, Name) values ('668', 'Chicago Bistro');
insert into restaurant (Service_id, Name) values ('669', 'The Maroon Oregano');
insert into restaurant (Service_id, Name) values ('670', 'The Emerald Clove');
insert into restaurant (Service_id, Name) values ('671', 'Breitenberg''s Kitchen');
insert into restaurant (Service_id, Name) values ('672', 'Breitenberg''s Kitchen');
insert into restaurant (Service_id, Name) values ('673', 'The Emerald Tarragon');
insert into restaurant (Service_id, Name) values ('674', 'The Azure Oregano');
insert into restaurant (Service_id, Name) values ('675', 'Austin Bistro');
insert into restaurant (Service_id, Name) values ('676', 'The Copper Chive');
insert into restaurant (Service_id, Name) values ('677', 'The Cobalt Mint');
insert into restaurant (Service_id, Name) values ('678', 'Beier''s Kitchen');
insert into restaurant (Service_id, Name) values ('679', 'Chicago Bistro');
insert into restaurant (Service_id, Name) values ('680', 'The Cobalt Saffron');
insert into restaurant (Service_id, Name) values ('681', 'The Ruby Thyme');
insert into restaurant (Service_id, Name) values ('682', 'The Golden Tarragon');
insert into restaurant (Service_id, Name) values ('683', 'The Indigo Oregano');
insert into restaurant (Service_id, Name) values ('684', 'Gislason''s Kitchen');
insert into restaurant (Service_id, Name) values ('685', 'The Teal Saffron');
insert into restaurant (Service_id, Name) values ('686', 'Rogahn''s Kitchen');
insert into restaurant (Service_id, Name) values ('687', 'Schmeler''s Kitchen');
insert into restaurant (Service_id, Name) values ('688', 'The Cobalt Basil');
insert into restaurant (Service_id, Name) values ('689', 'Boston Bistro');
insert into restaurant (Service_id, Name) values ('690', 'Gislason''s Kitchen');
insert into restaurant (Service_id, Name) values ('691', 'The Teal Oregano');
insert into restaurant (Service_id, Name) values ('692', 'The Ruby Clove');
insert into restaurant (Service_id, Name) values ('693', 'Miller''s Kitchen');
insert into restaurant (Service_id, Name) values ('694', 'London Bistro');
insert into restaurant (Service_id, Name) values ('695', 'Gislason''s Kitchen');
insert into restaurant (Service_id, Name) values ('696', 'Austin Bistro');
insert into restaurant (Service_id, Name) values ('697', 'Sydney Bistro');
insert into restaurant (Service_id, Name) values ('698', 'The Ruby Mint');
insert into restaurant (Service_id, Name) values ('699', 'Denver Bistro');
insert into restaurant (Service_id, Name) values ('700', 'Halvorson''s Kitchen');
insert into restaurant (Service_id, Name) values ('701', 'Casper''s Kitchen');
insert into restaurant (Service_id, Name) values ('702', 'The Azure Oregano');
insert into restaurant (Service_id, Name) values ('703', 'Roma Bistro');
insert into restaurant (Service_id, Name) values ('704', 'The Jade Mint');
insert into restaurant (Service_id, Name) values ('705', 'Barcelona Bistro');
insert into restaurant (Service_id, Name) values ('706', 'The Jade Tarragon');
insert into restaurant (Service_id, Name) values ('707', 'Zulauf''s Kitchen');
insert into restaurant (Service_id, Name) values ('708', 'The Golden Tarragon');
insert into restaurant (Service_id, Name) values ('709', 'The Copper Dill');
insert into restaurant (Service_id, Name) values ('710', 'The Golden Basil');
insert into restaurant (Service_id, Name) values ('711', 'Wilkinson''s Kitchen');
insert into restaurant (Service_id, Name) values ('712', 'Halvorson''s Kitchen');
insert into restaurant (Service_id, Name) values ('713', 'The Scarlet Saffron');
insert into restaurant (Service_id, Name) values ('714', 'Roma Bistro');
insert into restaurant (Service_id, Name) values ('715', 'The Saffron Fennel');
insert into restaurant (Service_id, Name) values ('716', 'The Copper Dill');
insert into restaurant (Service_id, Name) values ('717', 'Madrid Bistro');
insert into restaurant (Service_id, Name) values ('718', 'The Amber Rosemary');
insert into restaurant (Service_id, Name) values ('719', 'The Amber Rosemary');
insert into restaurant (Service_id, Name) values ('720', 'The Ivory Mint');
insert into restaurant (Service_id, Name) values ('721', 'The Onyx Lavender');
insert into restaurant (Service_id, Name) values ('722', 'Boston Bistro');
insert into restaurant (Service_id, Name) values ('723', 'Williamson''s Kitchen');
insert into restaurant (Service_id, Name) values ('724', 'Cole''s Kitchen');
insert into restaurant (Service_id, Name) values ('725', 'The Maroon Fennel');
insert into restaurant (Service_id, Name) values ('726', 'The Crimson Basil');
insert into restaurant (Service_id, Name) values ('727', 'The Saffron Clove');
insert into restaurant (Service_id, Name) values ('728', 'Boston Bistro');
insert into restaurant (Service_id, Name) values ('729', 'The Teal Saffron');
insert into restaurant (Service_id, Name) values ('730', 'The Amber Ginger');
insert into restaurant (Service_id, Name) values ('731', 'The Scarlet Dill');
insert into restaurant (Service_id, Name) values ('732', 'The Ivory Basil');
insert into restaurant (Service_id, Name) values ('733', 'The Saffron Mint');
insert into restaurant (Service_id, Name) values ('734', 'The Cobalt Mint');
insert into restaurant (Service_id, Name) values ('735', 'The Indigo Lavender');
insert into restaurant (Service_id, Name) values ('736', 'The Cobalt Basil');
insert into restaurant (Service_id, Name) values ('737', 'The Teal Saffron');
insert into restaurant (Service_id, Name) values ('738', 'Barcelona Bistro');
insert into restaurant (Service_id, Name) values ('739', 'Kyoto Bistro');
insert into restaurant (Service_id, Name) values ('740', 'The Maroon Clove');
insert into restaurant (Service_id, Name) values ('741', 'The Cobalt Oregano');
insert into restaurant (Service_id, Name) values ('742', 'The Onyx Fennel');
insert into restaurant (Service_id, Name) values ('743', 'Denver Bistro');
insert into restaurant (Service_id, Name) values ('744', 'The Emerald Clove');
insert into restaurant (Service_id, Name) values ('745', 'Williamson''s Kitchen');
insert into restaurant (Service_id, Name) values ('746', 'Beier''s Kitchen');
insert into restaurant (Service_id, Name) values ('747', 'Johnston''s Kitchen');
insert into restaurant (Service_id, Name) values ('748', 'The Copper Dill');
insert into restaurant (Service_id, Name) values ('749', 'Wilkinson''s Kitchen');
insert into restaurant (Service_id, Name) values ('750', 'The Ruby Mint');
insert into restaurant (Service_id, Name) values ('751', 'Roma Bistro');
insert into restaurant (Service_id, Name) values ('752', 'The Golden Chive');
insert into restaurant (Service_id, Name) values ('753', 'The Emerald Clove');
insert into restaurant (Service_id, Name) values ('754', 'The Maroon Fennel');
insert into restaurant (Service_id, Name) values ('755', 'The Emerald Tarragon');
insert into restaurant (Service_id, Name) values ('756', 'The Ruby Thyme');
insert into restaurant (Service_id, Name) values ('757', 'The Cobalt Dill');
insert into restaurant (Service_id, Name) values ('758', 'The Crimson Thyme');
insert into restaurant (Service_id, Name) values ('759', 'The Scarlet Dill');
insert into restaurant (Service_id, Name) values ('760', 'Cole''s Kitchen');
insert into restaurant (Service_id, Name) values ('761', 'The Teal Mint');
insert into restaurant (Service_id, Name) values ('762', 'Blick''s Kitchen');
insert into restaurant (Service_id, Name) values ('763', 'The Emerald Thyme');
insert into restaurant (Service_id, Name) values ('764', 'Johnston''s Kitchen');
insert into restaurant (Service_id, Name) values ('765', 'Stroman''s Kitchen');
insert into restaurant (Service_id, Name) values ('766', 'The Emerald Clove');
insert into restaurant (Service_id, Name) values ('767', 'Austin Bistro');
insert into restaurant (Service_id, Name) values ('768', 'Bayer''s Kitchen');
insert into restaurant (Service_id, Name) values ('769', 'Williamson''s Kitchen');
insert into restaurant (Service_id, Name) values ('770', 'Milan Bistro');
insert into restaurant (Service_id, Name) values ('771', 'Gislason''s Kitchen');
insert into restaurant (Service_id, Name) values ('772', 'New York Bistro');
insert into restaurant (Service_id, Name) values ('773', 'Vienna Bistro');
insert into restaurant (Service_id, Name) values ('774', 'The Crimson Thyme');
insert into restaurant (Service_id, Name) values ('775', 'The Azure Rosemary');
insert into restaurant (Service_id, Name) values ('776', 'Paris Bistro');
insert into restaurant (Service_id, Name) values ('777', 'Cummerata''s Kitchen');
insert into restaurant (Service_id, Name) values ('778', 'Paris Bistro');
insert into restaurant (Service_id, Name) values ('779', 'The Jade Tarragon');
insert into restaurant (Service_id, Name) values ('780', 'Johnston''s Kitchen');
insert into restaurant (Service_id, Name) values ('781', 'The Copper Thyme');
insert into restaurant (Service_id, Name) values ('782', 'Miami Bistro');
insert into restaurant (Service_id, Name) values ('783', 'Cummerata''s Kitchen');
insert into restaurant (Service_id, Name) values ('784', 'Cummerata''s Kitchen');
insert into restaurant (Service_id, Name) values ('785', 'Williamson''s Kitchen');
insert into restaurant (Service_id, Name) values ('786', 'The Maroon Clove');
insert into restaurant (Service_id, Name) values ('787', 'The Ruby Clove');
insert into restaurant (Service_id, Name) values ('788', 'Dickens''s Kitchen');
insert into restaurant (Service_id, Name) values ('789', 'Schmeler''s Kitchen');
insert into restaurant (Service_id, Name) values ('790', 'The Azure Rosemary');
insert into restaurant (Service_id, Name) values ('791', 'The Jade Rosemary');
insert into restaurant (Service_id, Name) values ('792', 'The Ivory Mint');
insert into restaurant (Service_id, Name) values ('793', 'The Emerald Clove');
insert into restaurant (Service_id, Name) values ('794', 'The Azure Oregano');
insert into restaurant (Service_id, Name) values ('795', 'Milan Bistro');
insert into restaurant (Service_id, Name) values ('796', 'Cummerata''s Kitchen');
insert into restaurant (Service_id, Name) values ('797', 'Dickens''s Kitchen');
insert into restaurant (Service_id, Name) values ('798', 'Chicago Bistro');
insert into restaurant (Service_id, Name) values ('799', 'Padberg''s Kitchen');
insert into restaurant (Service_id, Name) values ('800', 'The Saffron Clove');
insert into restaurant (Service_id, Name) values ('801', 'The Maroon Fennel');
insert into restaurant (Service_id, Name) values ('802', 'Schmeler''s Kitchen');
insert into restaurant (Service_id, Name) values ('803', 'Glover''s Kitchen');
insert into restaurant (Service_id, Name) values ('804', 'The Copper Dill');
insert into restaurant (Service_id, Name) values ('805', 'Madrid Bistro');
insert into restaurant (Service_id, Name) values ('806', 'The Ruby Thyme');
insert into restaurant (Service_id, Name) values ('807', 'Austin Bistro');
insert into restaurant (Service_id, Name) values ('808', 'The Copper Thyme');
insert into restaurant (Service_id, Name) values ('809', 'Denver Bistro');
insert into restaurant (Service_id, Name) values ('810', 'Halvorson''s Kitchen');
insert into restaurant (Service_id, Name) values ('811', 'The Copper Basil');
insert into restaurant (Service_id, Name) values ('812', 'Murray''s Kitchen');
insert into restaurant (Service_id, Name) values ('813', 'Cole''s Kitchen');
insert into restaurant (Service_id, Name) values ('814', 'Wilkinson''s Kitchen');
insert into restaurant (Service_id, Name) values ('815', 'The Azure Oregano');
insert into restaurant (Service_id, Name) values ('816', 'The Maroon Oregano');
insert into restaurant (Service_id, Name) values ('817', 'The Teal Mint');
insert into restaurant (Service_id, Name) values ('818', 'Stroman''s Kitchen');
insert into restaurant (Service_id, Name) values ('819', 'The Copper Chive');
insert into restaurant (Service_id, Name) values ('820', 'The Ruby Clove');
insert into restaurant (Service_id, Name) values ('821', 'The Saffron Thyme');
insert into restaurant (Service_id, Name) values ('822', 'The Ruby Chive');
insert into restaurant (Service_id, Name) values ('823', 'Johnston''s Kitchen');
insert into restaurant (Service_id, Name) values ('824', 'The Saffron Fennel');
insert into restaurant (Service_id, Name) values ('825', 'Tokyo Bistro');
insert into restaurant (Service_id, Name) values ('826', 'Stroman''s Kitchen');
insert into restaurant (Service_id, Name) values ('827', 'The Crimson Basil');
insert into restaurant (Service_id, Name) values ('828', 'The Indigo Oregano');
insert into restaurant (Service_id, Name) values ('829', 'Miami Bistro');
insert into restaurant (Service_id, Name) values ('830', 'Blick''s Kitchen');
insert into restaurant (Service_id, Name) values ('831', 'The Golden Basil');
insert into restaurant (Service_id, Name) values ('832', 'The Crimson Basil');
insert into restaurant (Service_id, Name) values ('833', 'The Azure Oregano');
insert into restaurant (Service_id, Name) values ('834', 'The Ruby Clove');
insert into restaurant (Service_id, Name) values ('835', 'The Cobalt Mint');
insert into restaurant (Service_id, Name) values ('836', 'London Bistro');
insert into restaurant (Service_id, Name) values ('837', 'Blick''s Kitchen');
insert into restaurant (Service_id, Name) values ('838', 'The Jade Tarragon');
insert into restaurant (Service_id, Name) values ('839', 'The Amber Rosemary');
insert into restaurant (Service_id, Name) values ('840', 'Walter''s Kitchen');
insert into restaurant (Service_id, Name) values ('841', 'O''Keefe''s Kitchen');
insert into restaurant (Service_id, Name) values ('842', 'Denver Bistro');
insert into restaurant (Service_id, Name) values ('843', 'The Saffron Fennel');
insert into restaurant (Service_id, Name) values ('844', 'The Crimson Basil');
insert into restaurant (Service_id, Name) values ('845', 'Beier''s Kitchen');
insert into restaurant (Service_id, Name) values ('846', 'The Ruby Tarragon');
insert into restaurant (Service_id, Name) values ('847', 'Miami Bistro');
insert into restaurant (Service_id, Name) values ('848', 'The Jade Chive');
insert into restaurant (Service_id, Name) values ('849', 'The Teal Oregano');
insert into restaurant (Service_id, Name) values ('850', 'Roma Bistro');
insert into restaurant (Service_id, Name) values ('851', 'Dickens''s Kitchen');
insert into restaurant (Service_id, Name) values ('852', 'Walter''s Kitchen');
insert into restaurant (Service_id, Name) values ('853', 'The Azure Oregano');
insert into restaurant (Service_id, Name) values ('854', 'The Copper Dill');
insert into restaurant (Service_id, Name) values ('855', 'Casper''s Kitchen');
insert into restaurant (Service_id, Name) values ('856', 'The Crimson Thyme');
insert into restaurant (Service_id, Name) values ('857', 'The Golden Basil');
insert into restaurant (Service_id, Name) values ('858', 'Roma Bistro');
insert into restaurant (Service_id, Name) values ('859', 'The Onyx Lavender');
insert into restaurant (Service_id, Name) values ('860', 'The Copper Basil');
insert into restaurant (Service_id, Name) values ('861', 'The Cobalt Basil');
insert into restaurant (Service_id, Name) values ('862', 'Zulauf''s Kitchen');
insert into restaurant (Service_id, Name) values ('863', 'The Emerald Clove');
insert into restaurant (Service_id, Name) values ('864', 'The Indigo Oregano');
insert into restaurant (Service_id, Name) values ('865', 'Vienna Bistro');
insert into restaurant (Service_id, Name) values ('866', 'Rogahn''s Kitchen');
insert into restaurant (Service_id, Name) values ('867', 'The Ruby Clove');
insert into restaurant (Service_id, Name) values ('868', 'O''Keefe''s Kitchen');
insert into restaurant (Service_id, Name) values ('869', 'The Copper Ginger');
insert into restaurant (Service_id, Name) values ('870', 'Tokyo Bistro');
insert into restaurant (Service_id, Name) values ('871', 'Beier''s Kitchen');
insert into restaurant (Service_id, Name) values ('872', 'The Crimson Thyme');
insert into restaurant (Service_id, Name) values ('873', 'The Saffron Fennel');
insert into restaurant (Service_id, Name) values ('874', 'Stroman''s Kitchen');
insert into restaurant (Service_id, Name) values ('875', 'The Emerald Tarragon');
insert into restaurant (Service_id, Name) values ('876', 'Roma Bistro');
insert into restaurant (Service_id, Name) values ('877', 'The Cobalt Oregano');
insert into restaurant (Service_id, Name) values ('878', 'The Ruby Chive');
insert into restaurant (Service_id, Name) values ('879', 'Roma Bistro');
insert into restaurant (Service_id, Name) values ('880', 'The Copper Basil');
insert into restaurant (Service_id, Name) values ('881', 'Halvorson''s Kitchen');
insert into restaurant (Service_id, Name) values ('882', 'The Copper Ginger');
insert into restaurant (Service_id, Name) values ('883', 'The Copper Fennel');
insert into restaurant (Service_id, Name) values ('884', 'Beier''s Kitchen');
insert into restaurant (Service_id, Name) values ('885', 'The Copper Ginger');
insert into restaurant (Service_id, Name) values ('886', 'The Teal Saffron');
insert into restaurant (Service_id, Name) values ('887', 'The Teal Ginger');
insert into restaurant (Service_id, Name) values ('888', 'Williamson''s Kitchen');
insert into restaurant (Service_id, Name) values ('889', 'The Copper Tarragon');
insert into restaurant (Service_id, Name) values ('890', 'The Onyx Lavender');
insert into restaurant (Service_id, Name) values ('891', 'The Emerald Tarragon');
insert into restaurant (Service_id, Name) values ('892', 'O''Keefe''s Kitchen');
insert into restaurant (Service_id, Name) values ('893', 'The Teal Saffron');
insert into restaurant (Service_id, Name) values ('894', 'Halvorson''s Kitchen');
insert into restaurant (Service_id, Name) values ('895', 'The Copper Ginger');
insert into restaurant (Service_id, Name) values ('896', 'The Golden Basil');
insert into restaurant (Service_id, Name) values ('897', 'The Ruby Thyme');
insert into restaurant (Service_id, Name) values ('898', 'Blick''s Kitchen');
insert into restaurant (Service_id, Name) values ('899', 'The Indigo Oregano');
insert into restaurant (Service_id, Name) values ('900', 'Stroman''s Kitchen');
insert into restaurant (Service_id, Name) values ('901', 'Cole''s Kitchen');
insert into restaurant (Service_id, Name) values ('902', 'London Bistro');
insert into restaurant (Service_id, Name) values ('903', 'The Copper Chive');
insert into restaurant (Service_id, Name) values ('904', 'The Onyx Fennel');
insert into restaurant (Service_id, Name) values ('905', 'The Saffron Thyme');
insert into restaurant (Service_id, Name) values ('906', 'Blick''s Kitchen');
insert into restaurant (Service_id, Name) values ('907', 'The Ruby Mint');
insert into restaurant (Service_id, Name) values ('908', 'Denver Bistro');
insert into restaurant (Service_id, Name) values ('909', 'The Teal Oregano');
insert into restaurant (Service_id, Name) values ('910', 'Casper''s Kitchen');
insert into restaurant (Service_id, Name) values ('911', 'The Copper Dill');
insert into restaurant (Service_id, Name) values ('912', 'Boston Bistro');
insert into restaurant (Service_id, Name) values ('913', 'The Azure Rosemary');
insert into restaurant (Service_id, Name) values ('914', 'The Scarlet Saffron');
insert into restaurant (Service_id, Name) values ('915', 'The Golden Tarragon');
insert into restaurant (Service_id, Name) values ('916', 'The Ruby Tarragon');
insert into restaurant (Service_id, Name) values ('917', 'The Copper Fennel');
insert into restaurant (Service_id, Name) values ('918', 'Walter''s Kitchen');
insert into restaurant (Service_id, Name) values ('919', 'The Cobalt Basil');
insert into restaurant (Service_id, Name) values ('920', 'The Cobalt Basil');
insert into restaurant (Service_id, Name) values ('921', 'Milan Bistro');
insert into restaurant (Service_id, Name) values ('922', 'The Ruby Thyme');
insert into restaurant (Service_id, Name) values ('923', 'Stroman''s Kitchen');
insert into restaurant (Service_id, Name) values ('924', 'The Cobalt Basil');
insert into restaurant (Service_id, Name) values ('925', 'Vienna Bistro');
insert into restaurant (Service_id, Name) values ('926', 'The Teal Ginger');
insert into restaurant (Service_id, Name) values ('927', 'O''Keefe''s Kitchen');
insert into restaurant (Service_id, Name) values ('928', 'Lesch''s Kitchen');
insert into restaurant (Service_id, Name) values ('929', 'The Azure Rosemary');
insert into restaurant (Service_id, Name) values ('930', 'The Copper Thyme');
insert into restaurant (Service_id, Name) values ('931', 'Walter''s Kitchen');
insert into restaurant (Service_id, Name) values ('932', 'Kyoto Bistro');
insert into restaurant (Service_id, Name) values ('933', 'The Teal Oregano');
insert into restaurant (Service_id, Name) values ('934', 'The Saffron Clove');
insert into restaurant (Service_id, Name) values ('935', 'The Ivory Mint');
insert into restaurant (Service_id, Name) values ('936', 'The Azure Rosemary');
insert into restaurant (Service_id, Name) values ('937', 'The Jade Fennel');
insert into restaurant (Service_id, Name) values ('938', 'Austin Bistro');
insert into restaurant (Service_id, Name) values ('939', 'Cole''s Kitchen');
insert into restaurant (Service_id, Name) values ('940', 'The Onyx Fennel');
insert into restaurant (Service_id, Name) values ('941', 'The Jade Chive');
insert into restaurant (Service_id, Name) values ('942', 'The Copper Basil');
insert into restaurant (Service_id, Name) values ('943', 'The Copper Dill');
insert into restaurant (Service_id, Name) values ('944', 'Cummerata''s Kitchen');
insert into restaurant (Service_id, Name) values ('945', 'The Emerald Tarragon');
insert into restaurant (Service_id, Name) values ('946', 'The Cobalt Oregano');
insert into restaurant (Service_id, Name) values ('947', 'The Ivory Basil');
insert into restaurant (Service_id, Name) values ('948', 'The Copper Tarragon');
insert into restaurant (Service_id, Name) values ('949', 'Cummerata''s Kitchen');
insert into restaurant (Service_id, Name) values ('950', 'The Onyx Fennel');
insert into restaurant (Service_id, Name) values ('951', 'The Maroon Fennel');
insert into restaurant (Service_id, Name) values ('952', 'The Ruby Chive');
insert into restaurant (Service_id, Name) values ('953', 'Tokyo Bistro');
insert into restaurant (Service_id, Name) values ('954', 'Denver Bistro');
insert into restaurant (Service_id, Name) values ('955', 'Padberg''s Kitchen');
insert into restaurant (Service_id, Name) values ('956', 'Huel''s Kitchen');
insert into restaurant (Service_id, Name) values ('957', 'The Indigo Lavender');
insert into restaurant (Service_id, Name) values ('958', 'The Crimson Saffron');
insert into restaurant (Service_id, Name) values ('959', 'The Ivory Basil');
insert into restaurant (Service_id, Name) values ('960', 'The Emerald Thyme');
insert into restaurant (Service_id, Name) values ('961', 'The Copper Fennel');
insert into restaurant (Service_id, Name) values ('962', 'The Cobalt Oregano');
insert into restaurant (Service_id, Name) values ('963', 'Stroman''s Kitchen');
insert into restaurant (Service_id, Name) values ('964', 'Miami Bistro');
insert into restaurant (Service_id, Name) values ('965', 'Wilkinson''s Kitchen');
insert into restaurant (Service_id, Name) values ('966', 'The Emerald Clove');
insert into restaurant (Service_id, Name) values ('967', 'The Copper Basil');
insert into restaurant (Service_id, Name) values ('968', 'The Indigo Ginger');
insert into restaurant (Service_id, Name) values ('969', 'The Ivory Basil');
insert into restaurant (Service_id, Name) values ('970', 'The Ruby Tarragon');
insert into restaurant (Service_id, Name) values ('971', 'Barcelona Bistro');
insert into restaurant (Service_id, Name) values ('972', 'The Golden Fennel');
insert into restaurant (Service_id, Name) values ('973', 'Walter''s Kitchen');
insert into restaurant (Service_id, Name) values ('974', 'New York Bistro');
insert into restaurant (Service_id, Name) values ('975', 'The Saffron Mint');
insert into restaurant (Service_id, Name) values ('976', 'The Cobalt Oregano');
insert into restaurant (Service_id, Name) values ('977', 'The Copper Basil');
insert into restaurant (Service_id, Name) values ('978', 'The Emerald Tarragon');
insert into restaurant (Service_id, Name) values ('979', 'Paris Bistro');
insert into restaurant (Service_id, Name) values ('980', 'Milan Bistro');
insert into restaurant (Service_id, Name) values ('981', 'The Copper Ginger');
insert into restaurant (Service_id, Name) values ('982', 'The Azure Rosemary');
insert into restaurant (Service_id, Name) values ('983', 'The Jade Chive');
insert into restaurant (Service_id, Name) values ('984', 'The Cobalt Dill');
insert into restaurant (Service_id, Name) values ('985', 'The Maroon Oregano');
insert into restaurant (Service_id, Name) values ('986', 'The Amber Rosemary');
insert into restaurant (Service_id, Name) values ('987', 'Heller''s Kitchen');
insert into restaurant (Service_id, Name) values ('988', 'The Copper Dill');
insert into restaurant (Service_id, Name) values ('989', 'The Indigo Ginger');
insert into restaurant (Service_id, Name) values ('990', 'The Teal Mint');
insert into restaurant (Service_id, Name) values ('991', 'Paris Bistro');
insert into restaurant (Service_id, Name) values ('992', 'The Crimson Basil');
insert into restaurant (Service_id, Name) values ('993', 'The Maroon Clove');
insert into restaurant (Service_id, Name) values ('994', 'Milan Bistro');
insert into restaurant (Service_id, Name) values ('995', 'The Ivory Basil');
insert into restaurant (Service_id, Name) values ('996', 'Vienna Bistro');
insert into restaurant (Service_id, Name) values ('997', 'The Scarlet Dill');
insert into restaurant (Service_id, Name) values ('998', 'Schmeler''s Kitchen');
insert into restaurant (Service_id, Name) values ('999', 'The Cobalt Mint');
