insert into restaurant (Service_id, Name) values (6, 'The Saffron Fennel');
insert into restaurant (Service_id, Name) values (9, 'Wilkinson''s Kitchen');
insert into restaurant (Service_id, Name) values (11, 'Vienna Bistro');
insert into restaurant (Service_id, Name) values (17, 'The Ruby Clove');
insert into restaurant (Service_id, Name) values (18, 'Padberg''s Kitchen');
insert into restaurant (Service_id, Name) values (19, 'The Maroon Fennel');
insert into restaurant (Service_id, Name) values (20, 'The Jade Chive');
insert into restaurant (Service_id, Name) values (33, 'The Cobalt Saffron');
insert into restaurant (Service_id, Name) values (35, 'Boston Bistro');
insert into restaurant (Service_id, Name) values (37, 'The Amber Rosemary');
insert into restaurant (Service_id, Name) values (41, 'Paris Bistro');
insert into restaurant (Service_id, Name) values (54, 'The Copper Ginger');
insert into restaurant (Service_id, Name) values (60, 'Williamson''s Kitchen');
insert into restaurant (Service_id, Name) values (62, 'Roma Bistro');
insert into restaurant (Service_id, Name) values (66, 'The Golden Chive');
insert into restaurant (Service_id, Name) values (68, 'The Amber Ginger');
insert into restaurant (Service_id, Name) values (72, 'Schmeler''s Kitchen');
insert into restaurant (Service_id, Name) values (73, 'The Ruby Thyme');
insert into restaurant (Service_id, Name) values (83, 'The Saffron Mint');
insert into restaurant (Service_id, Name) values (84, 'London Bistro');
insert into restaurant (Service_id, Name) values (97, 'Wilkinson''s Kitchen');
insert into restaurant (Service_id, Name) values (98, 'Glover''s Kitchen');
insert into restaurant (Service_id, Name) values (114, 'Beier''s Kitchen');
insert into restaurant (Service_id, Name) values (120, 'Vienna Bistro');
insert into restaurant (Service_id, Name) values (121, 'The Emerald Clove');
insert into restaurant (Service_id, Name) values (122, 'Rogahn''s Kitchen');
insert into restaurant (Service_id, Name) values (124, 'The Indigo Ginger');
insert into restaurant (Service_id, Name) values (127, 'The Golden Chive');
insert into restaurant (Service_id, Name) values (128, 'Johnston''s Kitchen');
insert into restaurant (Service_id, Name) values (133, 'The Ivory Basil');
insert into restaurant (Service_id, Name) values (138, 'The Teal Saffron');
insert into restaurant (Service_id, Name) values (139, 'The Copper Fennel');
insert into restaurant (Service_id, Name) values (148, 'The Jade Mint');
insert into restaurant (Service_id, Name) values (161, 'Miami Bistro');
insert into restaurant (Service_id, Name) values (167, 'The Ruby Tarragon');
insert into restaurant (Service_id, Name) values (169, 'Halvorson''s Kitchen');
insert into restaurant (Service_id, Name) values (171, 'The Ruby Thyme');
insert into restaurant (Service_id, Name) values (183, 'Austin Bistro');
insert into restaurant (Service_id, Name) values (185, 'The Jade Rosemary');
insert into restaurant (Service_id, Name) values (188, 'The Ruby Chive');
insert into restaurant (Service_id, Name) values (192, 'The Golden Chive');
insert into restaurant (Service_id, Name) values (198, 'Dach''s Kitchen');
insert into restaurant (Service_id, Name) values (205, 'The Maroon Fennel');
insert into restaurant (Service_id, Name) values (217, 'Austin Bistro');
insert into restaurant (Service_id, Name) values (218, 'The Onyx Lavender');
insert into restaurant (Service_id, Name) values (219, 'Madrid Bistro');
insert into restaurant (Service_id, Name) values (220, 'London Bistro');
insert into restaurant (Service_id, Name) values (233, 'The Maroon Oregano');
insert into restaurant (Service_id, Name) values (238, 'Huel''s Kitchen');
insert into restaurant (Service_id, Name) values (243, 'The Ruby Clove');
insert into restaurant (Service_id, Name) values (251, 'The Copper Fennel');
insert into restaurant (Service_id, Name) values (257, 'O''Keefe''s Kitchen');
insert into restaurant (Service_id, Name) values (258, 'Johnston''s Kitchen');
insert into restaurant (Service_id, Name) values (261, 'Dickens''s Kitchen');
insert into restaurant (Service_id, Name) values (262, 'The Onyx Fennel');
insert into restaurant (Service_id, Name) values (263, 'The Indigo Lavender');
insert into restaurant (Service_id, Name) values (264, 'Beier''s Kitchen');
insert into restaurant (Service_id, Name) values (269, 'The Saffron Mint');
insert into restaurant (Service_id, Name) values (275, 'The Golden Basil');
insert into restaurant (Service_id, Name) values (276, 'The Cobalt Basil');
insert into restaurant (Service_id, Name) values (281, 'The Cobalt Saffron');
insert into restaurant (Service_id, Name) values (302, 'The Jade Tarragon');
insert into restaurant (Service_id, Name) values (303, 'Heller''s Kitchen');
insert into restaurant (Service_id, Name) values (305, 'The Copper Tarragon');
insert into restaurant (Service_id, Name) values (319, 'Breitenberg''s Kitchen');
insert into restaurant (Service_id, Name) values (327, 'Kyoto Bistro');
insert into restaurant (Service_id, Name) values (332, 'The Crimson Saffron');
insert into restaurant (Service_id, Name) values (333, 'The Cobalt Dill');
insert into restaurant (Service_id, Name) values (338, 'Glover''s Kitchen');
insert into restaurant (Service_id, Name) values (343, 'The Copper Basil');
insert into restaurant (Service_id, Name) values (344, 'The Maroon Clove');
insert into restaurant (Service_id, Name) values (352, 'The Copper Basil');
insert into restaurant (Service_id, Name) values (354, 'The Azure Oregano');
insert into restaurant (Service_id, Name) values (360, 'The Onyx Lavender');
insert into restaurant (Service_id, Name) values (362, 'Casper''s Kitchen');
insert into restaurant (Service_id, Name) values (367, 'Murray''s Kitchen');
insert into restaurant (Service_id, Name) values (383, 'The Azure Rosemary');
insert into restaurant (Service_id, Name) values (384, 'The Cobalt Oregano');
insert into restaurant (Service_id, Name) values (391, 'The Teal Mint');
insert into restaurant (Service_id, Name) values (398, 'The Maroon Oregano');
insert into restaurant (Service_id, Name) values (403, 'The Copper Basil');
insert into restaurant (Service_id, Name) values (409, 'The Jade Chive');
insert into restaurant (Service_id, Name) values (422, 'Tokyo Bistro');
insert into restaurant (Service_id, Name) values (430, 'The Saffron Mint');
insert into restaurant (Service_id, Name) values (444, 'The Scarlet Dill');
insert into restaurant (Service_id, Name) values (450, 'The Copper Tarragon');
insert into restaurant (Service_id, Name) values (451, 'The Onyx Fennel');
insert into restaurant (Service_id, Name) values (452, 'The Copper Chive');
insert into restaurant (Service_id, Name) values (454, 'Rogahn''s Kitchen');
insert into restaurant (Service_id, Name) values (459, 'Milan Bistro');
insert into restaurant (Service_id, Name) values (463, 'Austin Bistro');
insert into restaurant (Service_id, Name) values (478, 'The Azure Rosemary');
insert into restaurant (Service_id, Name) values (479, 'Dach''s Kitchen');
insert into restaurant (Service_id, Name) values (481, 'The Scarlet Dill');
insert into restaurant (Service_id, Name) values (488, 'Stroman''s Kitchen');
insert into restaurant (Service_id, Name) values (489, 'The Teal Mint');
insert into restaurant (Service_id, Name) values (492, 'The Ruby Clove');
insert into restaurant (Service_id, Name) values (494, 'The Azure Oregano');
insert into restaurant (Service_id, Name) values (496, 'Tokyo Bistro');
insert into restaurant (Service_id, Name) values (500, 'Murray''s Kitchen');
insert into restaurant (Service_id, Name) values (513, 'Dickens''s Kitchen');
insert into restaurant (Service_id, Name) values (523, 'Miller''s Kitchen');
insert into restaurant (Service_id, Name) values (528, 'The Copper Ginger');
insert into restaurant (Service_id, Name) values (538, 'The Copper Fennel');
insert into restaurant (Service_id, Name) values (544, 'Rogahn''s Kitchen');
insert into restaurant (Service_id, Name) values (545, 'Halvorson''s Kitchen');
insert into restaurant (Service_id, Name) values (551, 'The Maroon Clove');
insert into restaurant (Service_id, Name) values (556, 'The Scarlet Thyme');
insert into restaurant (Service_id, Name) values (557, 'Paris Bistro');
insert into restaurant (Service_id, Name) values (564, 'Stroman''s Kitchen');
insert into restaurant (Service_id, Name) values (567, 'The Amber Rosemary');
insert into restaurant (Service_id, Name) values (569, 'The Copper Basil');
insert into restaurant (Service_id, Name) values (571, 'Barcelona Bistro');
insert into restaurant (Service_id, Name) values (578, 'O''Keefe''s Kitchen');
insert into restaurant (Service_id, Name) values (581, 'The Copper Ginger');
insert into restaurant (Service_id, Name) values (585, 'The Copper Fennel');
insert into restaurant (Service_id, Name) values (587, 'The Azure Rosemary');
insert into restaurant (Service_id, Name) values (588, 'Cummerata''s Kitchen');
insert into restaurant (Service_id, Name) values (596, 'Lesch''s Kitchen');
insert into restaurant (Service_id, Name) values (597, 'Denver Bistro');
insert into restaurant (Service_id, Name) values (606, 'The Saffron Mint');
insert into restaurant (Service_id, Name) values (608, 'Austin Bistro');
insert into restaurant (Service_id, Name) values (624, 'Vienna Bistro');
insert into restaurant (Service_id, Name) values (625, 'Tokyo Bistro');
insert into restaurant (Service_id, Name) values (632, 'Glover''s Kitchen');
insert into restaurant (Service_id, Name) values (643, 'The Ruby Chive');
insert into restaurant (Service_id, Name) values (647, 'Bayer''s Kitchen');
insert into restaurant (Service_id, Name) values (648, 'Austin Bistro');
insert into restaurant (Service_id, Name) values (651, 'The Copper Chive');
insert into restaurant (Service_id, Name) values (656, 'The Copper Basil');
insert into restaurant (Service_id, Name) values (657, 'The Maroon Clove');
insert into restaurant (Service_id, Name) values (663, 'The Amber Rosemary');
insert into restaurant (Service_id, Name) values (664, 'The Teal Mint');
insert into restaurant (Service_id, Name) values (670, 'Chicago Bistro');
insert into restaurant (Service_id, Name) values (676, 'Casper''s Kitchen');
insert into restaurant (Service_id, Name) values (678, 'Roma Bistro');
insert into restaurant (Service_id, Name) values (681, 'The Saffron Mint');
insert into restaurant (Service_id, Name) values (683, 'The Onyx Lavender');
insert into restaurant (Service_id, Name) values (686, 'The Ruby Mint');
insert into restaurant (Service_id, Name) values (694, 'The Scarlet Thyme');
insert into restaurant (Service_id, Name) values (699, 'The Jade Chive');
insert into restaurant (Service_id, Name) values (703, 'The Teal Mint');
insert into restaurant (Service_id, Name) values (718, 'Vienna Bistro');
insert into restaurant (Service_id, Name) values (720, 'Zulauf''s Kitchen');
insert into restaurant (Service_id, Name) values (726, 'Murray''s Kitchen');
insert into restaurant (Service_id, Name) values (728, 'The Scarlet Saffron');
insert into restaurant (Service_id, Name) values (733, 'Dach''s Kitchen');
insert into restaurant (Service_id, Name) values (740, 'The Golden Basil');
insert into restaurant (Service_id, Name) values (743, 'Beier''s Kitchen');
insert into restaurant (Service_id, Name) values (752, 'Cummerata''s Kitchen');
insert into restaurant (Service_id, Name) values (755, 'The Cobalt Oregano');
insert into restaurant (Service_id, Name) values (779, 'The Saffron Clove');
insert into restaurant (Service_id, Name) values (781, 'Sydney Bistro');
insert into restaurant (Service_id, Name) values (783, 'Denver Bistro');
insert into restaurant (Service_id, Name) values (784, 'Bayer''s Kitchen');
insert into restaurant (Service_id, Name) values (788, 'O''Keefe''s Kitchen');
insert into restaurant (Service_id, Name) values (790, 'Sydney Bistro');
insert into restaurant (Service_id, Name) values (793, 'The Crimson Thyme');
insert into restaurant (Service_id, Name) values (804, 'The Ruby Mint');
insert into restaurant (Service_id, Name) values (807, 'The Ruby Tarragon');
insert into restaurant (Service_id, Name) values (811, 'Kyoto Bistro');
insert into restaurant (Service_id, Name) values (814, 'The Ruby Tarragon');
insert into restaurant (Service_id, Name) values (816, 'Miller''s Kitchen');
insert into restaurant (Service_id, Name) values (822, 'Barcelona Bistro');
insert into restaurant (Service_id, Name) values (833, 'The Copper Ginger');
insert into restaurant (Service_id, Name) values (840, 'Chicago Bistro');
insert into restaurant (Service_id, Name) values (847, 'The Cobalt Oregano');
insert into restaurant (Service_id, Name) values (852, 'The Onyx Fennel');
insert into restaurant (Service_id, Name) values (853, 'The Crimson Basil');
insert into restaurant (Service_id, Name) values (863, 'Rogahn''s Kitchen');
insert into restaurant (Service_id, Name) values (867, 'The Saffron Clove');
insert into restaurant (Service_id, Name) values (868, 'The Ivory Mint');
insert into restaurant (Service_id, Name) values (877, 'The Ivory Mint');
insert into restaurant (Service_id, Name) values (883, 'The Jade Fennel');
insert into restaurant (Service_id, Name) values (890, 'The Golden Fennel');
insert into restaurant (Service_id, Name) values (901, 'Huel''s Kitchen');
insert into restaurant (Service_id, Name) values (904, 'The Ruby Mint');
insert into restaurant (Service_id, Name) values (907, 'Madrid Bistro');
insert into restaurant (Service_id, Name) values (909, 'The Teal Saffron');
insert into restaurant (Service_id, Name) values (912, 'The Cobalt Mint');
insert into restaurant (Service_id, Name) values (913, 'The Azure Oregano');
insert into restaurant (Service_id, Name) values (917, 'London Bistro');
insert into restaurant (Service_id, Name) values (922, 'London Bistro');
insert into restaurant (Service_id, Name) values (929, 'Barcelona Bistro');
insert into restaurant (Service_id, Name) values (933, 'The Cobalt Saffron');
insert into restaurant (Service_id, Name) values (936, 'London Bistro');
insert into restaurant (Service_id, Name) values (944, 'The Emerald Tarragon');
insert into restaurant (Service_id, Name) values (946, 'The Ruby Clove');
insert into restaurant (Service_id, Name) values (948, 'Denver Bistro');
insert into restaurant (Service_id, Name) values (954, 'The Indigo Lavender');
insert into restaurant (Service_id, Name) values (955, 'The Ruby Chive');
insert into restaurant (Service_id, Name) values (959, 'Roma Bistro');
insert into restaurant (Service_id, Name) values (964, 'The Indigo Oregano');
insert into restaurant (Service_id, Name) values (969, 'The Scarlet Dill');
insert into restaurant (Service_id, Name) values (974, 'The Ruby Chive');
insert into restaurant (Service_id, Name) values (984, 'Dach''s Kitchen');
insert into restaurant (Service_id, Name) values (986, 'The Teal Mint');
insert into restaurant (Service_id, Name) values (990, 'The Teal Saffron');
insert into restaurant (Service_id, Name) values (997, 'The Copper Fennel');
insert into restaurant (Service_id, Name) values (998, 'The Jade Fennel');
