
insert into review_target (Target_id, Target_Type) values ('1', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('2', 'Package');
insert into review_target (Target_id, Target_Type) values ('3', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('4', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('5', 'Package');
insert into review_target (Target_id, Target_Type) values ('6', 'Package');
insert into review_target (Target_id, Target_Type) values ('7', 'Package');
insert into review_target (Target_id, Target_Type) values ('8', 'Package');
insert into review_target (Target_id, Target_Type) values ('9', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('10', 'Package');
insert into review_target (Target_id, Target_Type) values ('11', 'Package');
insert into review_target (Target_id, Target_Type) values ('12', 'Package');
insert into review_target (Target_id, Target_Type) values ('13', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('14', 'Package');
insert into review_target (Target_id, Target_Type) values ('15', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('16', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('17', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('18', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('19', 'Package');
insert into review_target (Target_id, Target_Type) values ('20', 'Package');
insert into review_target (Target_id, Target_Type) values ('21', 'Package');
insert into review_target (Target_id, Target_Type) values ('22', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('23', 'Package');
insert into review_target (Target_id, Target_Type) values ('24', 'Package');
insert into review_target (Target_id, Target_Type) values ('25', 'Package');
insert into review_target (Target_id, Target_Type) values ('26', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('27', 'Package');
insert into review_target (Target_id, Target_Type) values ('28', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('29', 'Package');
insert into review_target (Target_id, Target_Type) values ('30', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('31', 'Package');
insert into review_target (Target_id, Target_Type) values ('32', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('33', 'Package');
insert into review_target (Target_id, Target_Type) values ('34', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('35', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('36', 'Package');
insert into review_target (Target_id, Target_Type) values ('37', 'Package');
insert into review_target (Target_id, Target_Type) values ('38', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('39', 'Package');
insert into review_target (Target_id, Target_Type) values ('40', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('41', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('42', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('43', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('44', 'Package');
insert into review_target (Target_id, Target_Type) values ('45', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('46', 'Package');
insert into review_target (Target_id, Target_Type) values ('47', 'Package');
insert into review_target (Target_id, Target_Type) values ('48', 'Package');
insert into review_target (Target_id, Target_Type) values ('49', 'Package');
insert into review_target (Target_id, Target_Type) values ('50', 'Package');
insert into review_target (Target_id, Target_Type) values ('51', 'Package');
insert into review_target (Target_id, Target_Type) values ('52', 'Package');
insert into review_target (Target_id, Target_Type) values ('53', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('54', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('55', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('56', 'Package');
insert into review_target (Target_id, Target_Type) values ('57', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('58', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('59', 'Package');
insert into review_target (Target_id, Target_Type) values ('60', 'Package');
insert into review_target (Target_id, Target_Type) values ('61', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('62', 'Package');
insert into review_target (Target_id, Target_Type) values ('63', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('64', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('65', 'Package');
insert into review_target (Target_id, Target_Type) values ('66', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('67', 'Package');
insert into review_target (Target_id, Target_Type) values ('68', 'Package');
insert into review_target (Target_id, Target_Type) values ('69', 'Package');
insert into review_target (Target_id, Target_Type) values ('70', 'Package');
insert into review_target (Target_id, Target_Type) values ('71', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('72', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('73', 'Package');
insert into review_target (Target_id, Target_Type) values ('74', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('75', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('76', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('77', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('78', 'Package');
insert into review_target (Target_id, Target_Type) values ('79', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('80', 'Package');
insert into review_target (Target_id, Target_Type) values ('81', 'Package');
insert into review_target (Target_id, Target_Type) values ('82', 'Package');
insert into review_target (Target_id, Target_Type) values ('83', 'Package');
insert into review_target (Target_id, Target_Type) values ('84', 'Package');
insert into review_target (Target_id, Target_Type) values ('85', 'Package');
insert into review_target (Target_id, Target_Type) values ('86', 'Package');
insert into review_target (Target_id, Target_Type) values ('87', 'Package');
insert into review_target (Target_id, Target_Type) values ('88', 'Package');
insert into review_target (Target_id, Target_Type) values ('89', 'Package');
insert into review_target (Target_id, Target_Type) values ('90', 'Package');
insert into review_target (Target_id, Target_Type) values ('91', 'Package');
insert into review_target (Target_id, Target_Type) values ('92', 'Package');
insert into review_target (Target_id, Target_Type) values ('93', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('94', 'Package');
insert into review_target (Target_id, Target_Type) values ('95', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('96', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('97', 'Package');
insert into review_target (Target_id, Target_Type) values ('98', 'Package');
insert into review_target (Target_id, Target_Type) values ('99', 'Package');
insert into review_target (Target_id, Target_Type) values ('100', 'Package');
insert into review_target (Target_id, Target_Type) values ('101', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('102', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('103', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('104', 'Package');
insert into review_target (Target_id, Target_Type) values ('105', 'Package');
insert into review_target (Target_id, Target_Type) values ('106', 'Package');
insert into review_target (Target_id, Target_Type) values ('107', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('108', 'Package');
insert into review_target (Target_id, Target_Type) values ('109', 'Package');
insert into review_target (Target_id, Target_Type) values ('110', 'Package');
insert into review_target (Target_id, Target_Type) values ('111', 'Package');
insert into review_target (Target_id, Target_Type) values ('112', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('113', 'Package');
insert into review_target (Target_id, Target_Type) values ('114', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('115', 'Package');
insert into review_target (Target_id, Target_Type) values ('116', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('117', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('118', 'Package');
insert into review_target (Target_id, Target_Type) values ('119', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('120', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('121', 'Package');
insert into review_target (Target_id, Target_Type) values ('122', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('123', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('124', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('125', 'Package');
insert into review_target (Target_id, Target_Type) values ('126', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('127', 'Package');
insert into review_target (Target_id, Target_Type) values ('128', 'Package');
insert into review_target (Target_id, Target_Type) values ('129', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('130', 'Package');
insert into review_target (Target_id, Target_Type) values ('131', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('132', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('133', 'Package');
insert into review_target (Target_id, Target_Type) values ('134', 'Package');
insert into review_target (Target_id, Target_Type) values ('135', 'Package');
insert into review_target (Target_id, Target_Type) values ('136', 'Package');
insert into review_target (Target_id, Target_Type) values ('137', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('138', 'Package');
insert into review_target (Target_id, Target_Type) values ('139', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('140', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('141', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('142', 'Package');
insert into review_target (Target_id, Target_Type) values ('143', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('144', 'Package');
insert into review_target (Target_id, Target_Type) values ('145', 'Package');
insert into review_target (Target_id, Target_Type) values ('146', 'Package');
insert into review_target (Target_id, Target_Type) values ('147', 'Package');
insert into review_target (Target_id, Target_Type) values ('148', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('149', 'Package');
insert into review_target (Target_id, Target_Type) values ('150', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('151', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('152', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('153', 'Package');
insert into review_target (Target_id, Target_Type) values ('154', 'Package');
insert into review_target (Target_id, Target_Type) values ('155', 'Package');
insert into review_target (Target_id, Target_Type) values ('156', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('157', 'Package');
insert into review_target (Target_id, Target_Type) values ('158', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('159', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('160', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('161', 'Package');
insert into review_target (Target_id, Target_Type) values ('162', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('163', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('164', 'Package');
insert into review_target (Target_id, Target_Type) values ('165', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('166', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('167', 'Package');
insert into review_target (Target_id, Target_Type) values ('168', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('169', 'Package');
insert into review_target (Target_id, Target_Type) values ('170', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('171', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('172', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('173', 'Package');
insert into review_target (Target_id, Target_Type) values ('174', 'Package');
insert into review_target (Target_id, Target_Type) values ('175', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('176', 'Package');
insert into review_target (Target_id, Target_Type) values ('177', 'Package');
insert into review_target (Target_id, Target_Type) values ('178', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('179', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('180', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('181', 'Package');
insert into review_target (Target_id, Target_Type) values ('182', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('183', 'Package');
insert into review_target (Target_id, Target_Type) values ('184', 'Package');
insert into review_target (Target_id, Target_Type) values ('185', 'Package');
insert into review_target (Target_id, Target_Type) values ('186', 'Package');
insert into review_target (Target_id, Target_Type) values ('187', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('188', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('189', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('190', 'Package');
insert into review_target (Target_id, Target_Type) values ('191', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('192', 'Package');
insert into review_target (Target_id, Target_Type) values ('193', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('194', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('195', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('196', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('197', 'Package');
insert into review_target (Target_id, Target_Type) values ('198', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('199', 'Package');
insert into review_target (Target_id, Target_Type) values ('200', 'Package');
insert into review_target (Target_id, Target_Type) values ('201', 'Package');
insert into review_target (Target_id, Target_Type) values ('202', 'Package');
insert into review_target (Target_id, Target_Type) values ('203', 'Package');
insert into review_target (Target_id, Target_Type) values ('204', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('205', 'Package');
insert into review_target (Target_id, Target_Type) values ('206', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('207', 'Package');
insert into review_target (Target_id, Target_Type) values ('208', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('209', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('210', 'Package');
insert into review_target (Target_id, Target_Type) values ('211', 'Package');
insert into review_target (Target_id, Target_Type) values ('212', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('213', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('214', 'Package');
insert into review_target (Target_id, Target_Type) values ('215', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('216', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('217', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('218', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('219', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('220', 'Package');
insert into review_target (Target_id, Target_Type) values ('221', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('222', 'Package');
insert into review_target (Target_id, Target_Type) values ('223', 'Package');
insert into review_target (Target_id, Target_Type) values ('224', 'Package');
insert into review_target (Target_id, Target_Type) values ('225', 'Package');
insert into review_target (Target_id, Target_Type) values ('226', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('227', 'Package');
insert into review_target (Target_id, Target_Type) values ('228', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('229', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('230', 'Package');
insert into review_target (Target_id, Target_Type) values ('231', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('232', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('233', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('234', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('235', 'Package');
insert into review_target (Target_id, Target_Type) values ('236', 'Package');
insert into review_target (Target_id, Target_Type) values ('237', 'Package');
insert into review_target (Target_id, Target_Type) values ('238', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('239', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('240', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('241', 'Package');
insert into review_target (Target_id, Target_Type) values ('242', 'Package');
insert into review_target (Target_id, Target_Type) values ('243', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('244', 'Package');
insert into review_target (Target_id, Target_Type) values ('245', 'Package');
insert into review_target (Target_id, Target_Type) values ('246', 'Package');
insert into review_target (Target_id, Target_Type) values ('247', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('248', 'Package');
insert into review_target (Target_id, Target_Type) values ('249', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('250', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('251', 'Package');
insert into review_target (Target_id, Target_Type) values ('252', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('253', 'Package');
insert into review_target (Target_id, Target_Type) values ('254', 'Package');
insert into review_target (Target_id, Target_Type) values ('255', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('256', 'Package');
insert into review_target (Target_id, Target_Type) values ('257', 'Package');
insert into review_target (Target_id, Target_Type) values ('258', 'Package');
insert into review_target (Target_id, Target_Type) values ('259', 'Package');
insert into review_target (Target_id, Target_Type) values ('260', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('261', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('262', 'Package');
insert into review_target (Target_id, Target_Type) values ('263', 'Package');
insert into review_target (Target_id, Target_Type) values ('264', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('265', 'Package');
insert into review_target (Target_id, Target_Type) values ('266', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('267', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('268', 'Package');
insert into review_target (Target_id, Target_Type) values ('269', 'Package');
insert into review_target (Target_id, Target_Type) values ('270', 'Package');
insert into review_target (Target_id, Target_Type) values ('271', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('272', 'Package');
insert into review_target (Target_id, Target_Type) values ('273', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('274', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('275', 'Package');
insert into review_target (Target_id, Target_Type) values ('276', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('277', 'Package');
insert into review_target (Target_id, Target_Type) values ('278', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('279', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('280', 'Package');
insert into review_target (Target_id, Target_Type) values ('281', 'Package');
insert into review_target (Target_id, Target_Type) values ('282', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('283', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('284', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('285', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('286', 'Package');
insert into review_target (Target_id, Target_Type) values ('287', 'Package');
insert into review_target (Target_id, Target_Type) values ('288', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('289', 'Package');
insert into review_target (Target_id, Target_Type) values ('290', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('291', 'Package');
insert into review_target (Target_id, Target_Type) values ('292', 'Package');
insert into review_target (Target_id, Target_Type) values ('293', 'Package');
insert into review_target (Target_id, Target_Type) values ('294', 'Package');
insert into review_target (Target_id, Target_Type) values ('295', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('296', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('297', 'Package');
insert into review_target (Target_id, Target_Type) values ('298', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('299', 'Package');
insert into review_target (Target_id, Target_Type) values ('300', 'Package');
insert into review_target (Target_id, Target_Type) values ('301', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('302', 'Package');
insert into review_target (Target_id, Target_Type) values ('303', 'Package');
insert into review_target (Target_id, Target_Type) values ('304', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('305', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('306', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('307', 'Package');
insert into review_target (Target_id, Target_Type) values ('308', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('309', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('310', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('311', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('312', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('313', 'Package');
insert into review_target (Target_id, Target_Type) values ('314', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('315', 'Package');
insert into review_target (Target_id, Target_Type) values ('316', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('317', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('318', 'Package');
insert into review_target (Target_id, Target_Type) values ('319', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('320', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('321', 'Package');
insert into review_target (Target_id, Target_Type) values ('322', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('323', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('324', 'Package');
insert into review_target (Target_id, Target_Type) values ('325', 'Package');
insert into review_target (Target_id, Target_Type) values ('326', 'Package');
insert into review_target (Target_id, Target_Type) values ('327', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('328', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('329', 'Package');
insert into review_target (Target_id, Target_Type) values ('330', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('331', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('332', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('333', 'Package');
insert into review_target (Target_id, Target_Type) values ('334', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('335', 'Package');
insert into review_target (Target_id, Target_Type) values ('336', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('337', 'Package');
insert into review_target (Target_id, Target_Type) values ('338', 'Package');
insert into review_target (Target_id, Target_Type) values ('339', 'Package');
insert into review_target (Target_id, Target_Type) values ('340', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('341', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('342', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('343', 'Package');
insert into review_target (Target_id, Target_Type) values ('344', 'Package');
insert into review_target (Target_id, Target_Type) values ('345', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('346', 'Package');
insert into review_target (Target_id, Target_Type) values ('347', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('348', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('349', 'Package');
insert into review_target (Target_id, Target_Type) values ('350', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('351', 'Package');
insert into review_target (Target_id, Target_Type) values ('352', 'Package');
insert into review_target (Target_id, Target_Type) values ('353', 'Package');
insert into review_target (Target_id, Target_Type) values ('354', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('355', 'Package');
insert into review_target (Target_id, Target_Type) values ('356', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('357', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('358', 'Package');
insert into review_target (Target_id, Target_Type) values ('359', 'Package');
insert into review_target (Target_id, Target_Type) values ('360', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('361', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('362', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('363', 'Package');
insert into review_target (Target_id, Target_Type) values ('364', 'Package');
insert into review_target (Target_id, Target_Type) values ('365', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('366', 'Package');
insert into review_target (Target_id, Target_Type) values ('367', 'Package');
insert into review_target (Target_id, Target_Type) values ('368', 'Package');
insert into review_target (Target_id, Target_Type) values ('369', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('370', 'Package');
insert into review_target (Target_id, Target_Type) values ('371', 'Package');
insert into review_target (Target_id, Target_Type) values ('372', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('373', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('374', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('375', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('376', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('377', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('378', 'Package');
insert into review_target (Target_id, Target_Type) values ('379', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('380', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('381', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('382', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('383', 'Package');
insert into review_target (Target_id, Target_Type) values ('384', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('385', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('386', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('387', 'Package');
insert into review_target (Target_id, Target_Type) values ('388', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('389', 'Package');
insert into review_target (Target_id, Target_Type) values ('390', 'Package');
insert into review_target (Target_id, Target_Type) values ('391', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('392', 'Package');
insert into review_target (Target_id, Target_Type) values ('393', 'Package');
insert into review_target (Target_id, Target_Type) values ('394', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('395', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('396', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('397', 'Package');
insert into review_target (Target_id, Target_Type) values ('398', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('399', 'Package');
insert into review_target (Target_id, Target_Type) values ('400', 'Package');
insert into review_target (Target_id, Target_Type) values ('401', 'Package');
insert into review_target (Target_id, Target_Type) values ('402', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('403', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('404', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('405', 'Package');
insert into review_target (Target_id, Target_Type) values ('406', 'Package');
insert into review_target (Target_id, Target_Type) values ('407', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('408', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('409', 'Package');
insert into review_target (Target_id, Target_Type) values ('410', 'Package');
insert into review_target (Target_id, Target_Type) values ('411', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('412', 'Package');
insert into review_target (Target_id, Target_Type) values ('413', 'Package');
insert into review_target (Target_id, Target_Type) values ('414', 'Package');
insert into review_target (Target_id, Target_Type) values ('415', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('416', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('417', 'Package');
insert into review_target (Target_id, Target_Type) values ('418', 'Package');
insert into review_target (Target_id, Target_Type) values ('419', 'Package');
insert into review_target (Target_id, Target_Type) values ('420', 'Package');
insert into review_target (Target_id, Target_Type) values ('421', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('422', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('423', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('424', 'Package');
insert into review_target (Target_id, Target_Type) values ('425', 'Package');
insert into review_target (Target_id, Target_Type) values ('426', 'Package');
insert into review_target (Target_id, Target_Type) values ('427', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('428', 'Package');
insert into review_target (Target_id, Target_Type) values ('429', 'Package');
insert into review_target (Target_id, Target_Type) values ('430', 'Package');
insert into review_target (Target_id, Target_Type) values ('431', 'Package');
insert into review_target (Target_id, Target_Type) values ('432', 'Package');
insert into review_target (Target_id, Target_Type) values ('433', 'Package');
insert into review_target (Target_id, Target_Type) values ('434', 'Package');
insert into review_target (Target_id, Target_Type) values ('435', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('436', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('437', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('438', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('439', 'Package');
insert into review_target (Target_id, Target_Type) values ('440', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('441', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('442', 'Package');
insert into review_target (Target_id, Target_Type) values ('443', 'Package');
insert into review_target (Target_id, Target_Type) values ('444', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('445', 'Package');
insert into review_target (Target_id, Target_Type) values ('446', 'Package');
insert into review_target (Target_id, Target_Type) values ('447', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('448', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('449', 'Package');
insert into review_target (Target_id, Target_Type) values ('450', 'Package');
insert into review_target (Target_id, Target_Type) values ('451', 'Package');
insert into review_target (Target_id, Target_Type) values ('452', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('453', 'Package');
insert into review_target (Target_id, Target_Type) values ('454', 'Package');
insert into review_target (Target_id, Target_Type) values ('455', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('456', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('457', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('458', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('459', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('460', 'Package');
insert into review_target (Target_id, Target_Type) values ('461', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('462', 'Package');
insert into review_target (Target_id, Target_Type) values ('463', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('464', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('465', 'Package');
insert into review_target (Target_id, Target_Type) values ('466', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('467', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('468', 'Package');
insert into review_target (Target_id, Target_Type) values ('469', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('470', 'Package');
insert into review_target (Target_id, Target_Type) values ('471', 'Package');
insert into review_target (Target_id, Target_Type) values ('472', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('473', 'Package');
insert into review_target (Target_id, Target_Type) values ('474', 'Package');
insert into review_target (Target_id, Target_Type) values ('475', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('476', 'Package');
insert into review_target (Target_id, Target_Type) values ('477', 'Package');
insert into review_target (Target_id, Target_Type) values ('478', 'Package');
insert into review_target (Target_id, Target_Type) values ('479', 'Package');
insert into review_target (Target_id, Target_Type) values ('480', 'Package');
insert into review_target (Target_id, Target_Type) values ('481', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('482', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('483', 'Package');
insert into review_target (Target_id, Target_Type) values ('484', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('485', 'Package');
insert into review_target (Target_id, Target_Type) values ('486', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('487', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('488', 'Package');
insert into review_target (Target_id, Target_Type) values ('489', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('490', 'Package');
insert into review_target (Target_id, Target_Type) values ('491', 'Package');
insert into review_target (Target_id, Target_Type) values ('492', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('493', 'Package');
insert into review_target (Target_id, Target_Type) values ('494', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('495', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('496', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('497', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('498', 'Package');
insert into review_target (Target_id, Target_Type) values ('499', 'Package');
insert into review_target (Target_id, Target_Type) values ('500', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('501', 'Package');
insert into review_target (Target_id, Target_Type) values ('502', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('503', 'Package');
insert into review_target (Target_id, Target_Type) values ('504', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('505', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('506', 'Package');
insert into review_target (Target_id, Target_Type) values ('507', 'Package');
insert into review_target (Target_id, Target_Type) values ('508', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('509', 'Package');
insert into review_target (Target_id, Target_Type) values ('510', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('511', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('512', 'Package');
insert into review_target (Target_id, Target_Type) values ('513', 'Package');
insert into review_target (Target_id, Target_Type) values ('514', 'Package');
insert into review_target (Target_id, Target_Type) values ('515', 'Package');
insert into review_target (Target_id, Target_Type) values ('516', 'Package');
insert into review_target (Target_id, Target_Type) values ('517', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('518', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('519', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('520', 'Package');
insert into review_target (Target_id, Target_Type) values ('521', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('522', 'Package');
insert into review_target (Target_id, Target_Type) values ('523', 'Package');
insert into review_target (Target_id, Target_Type) values ('524', 'Package');
insert into review_target (Target_id, Target_Type) values ('525', 'Package');
insert into review_target (Target_id, Target_Type) values ('526', 'Package');
insert into review_target (Target_id, Target_Type) values ('527', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('528', 'Package');
insert into review_target (Target_id, Target_Type) values ('529', 'Package');
insert into review_target (Target_id, Target_Type) values ('530', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('531', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('532', 'Package');
insert into review_target (Target_id, Target_Type) values ('533', 'Package');
insert into review_target (Target_id, Target_Type) values ('534', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('535', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('536', 'Package');
insert into review_target (Target_id, Target_Type) values ('537', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('538', 'Package');
insert into review_target (Target_id, Target_Type) values ('539', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('540', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('541', 'Package');
insert into review_target (Target_id, Target_Type) values ('542', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('543', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('544', 'Package');
insert into review_target (Target_id, Target_Type) values ('545', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('546', 'Package');
insert into review_target (Target_id, Target_Type) values ('547', 'Package');
insert into review_target (Target_id, Target_Type) values ('548', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('549', 'Package');
insert into review_target (Target_id, Target_Type) values ('550', 'Package');
insert into review_target (Target_id, Target_Type) values ('551', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('552', 'Package');
insert into review_target (Target_id, Target_Type) values ('553', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('554', 'Package');
insert into review_target (Target_id, Target_Type) values ('555', 'Package');
insert into review_target (Target_id, Target_Type) values ('556', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('557', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('558', 'Package');
insert into review_target (Target_id, Target_Type) values ('559', 'Package');
insert into review_target (Target_id, Target_Type) values ('560', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('561', 'Package');
insert into review_target (Target_id, Target_Type) values ('562', 'Package');
insert into review_target (Target_id, Target_Type) values ('563', 'Package');
insert into review_target (Target_id, Target_Type) values ('564', 'Package');
insert into review_target (Target_id, Target_Type) values ('565', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('566', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('567', 'Package');
insert into review_target (Target_id, Target_Type) values ('568', 'Package');
insert into review_target (Target_id, Target_Type) values ('569', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('570', 'Package');
insert into review_target (Target_id, Target_Type) values ('571', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('572', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('573', 'Package');
insert into review_target (Target_id, Target_Type) values ('574', 'Package');
insert into review_target (Target_id, Target_Type) values ('575', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('576', 'Package');
insert into review_target (Target_id, Target_Type) values ('577', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('578', 'Package');
insert into review_target (Target_id, Target_Type) values ('579', 'Package');
insert into review_target (Target_id, Target_Type) values ('580', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('581', 'Package');
insert into review_target (Target_id, Target_Type) values ('582', 'Package');
insert into review_target (Target_id, Target_Type) values ('583', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('584', 'Package');
insert into review_target (Target_id, Target_Type) values ('585', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('586', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('587', 'Package');
insert into review_target (Target_id, Target_Type) values ('588', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('589', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('590', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('591', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('592', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('593', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('594', 'Package');
insert into review_target (Target_id, Target_Type) values ('595', 'Package');
insert into review_target (Target_id, Target_Type) values ('596', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('597', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('598', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('599', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('600', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('601', 'Package');
insert into review_target (Target_id, Target_Type) values ('602', 'Package');
insert into review_target (Target_id, Target_Type) values ('603', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('604', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('605', 'Package');
insert into review_target (Target_id, Target_Type) values ('606', 'Package');
insert into review_target (Target_id, Target_Type) values ('607', 'Package');
insert into review_target (Target_id, Target_Type) values ('608', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('609', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('610', 'Package');
insert into review_target (Target_id, Target_Type) values ('611', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('612', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('613', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('614', 'Package');
insert into review_target (Target_id, Target_Type) values ('615', 'Package');
insert into review_target (Target_id, Target_Type) values ('616', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('617', 'Package');
insert into review_target (Target_id, Target_Type) values ('618', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('619', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('620', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('621', 'Package');
insert into review_target (Target_id, Target_Type) values ('622', 'Package');
insert into review_target (Target_id, Target_Type) values ('623', 'Package');
insert into review_target (Target_id, Target_Type) values ('624', 'Package');
insert into review_target (Target_id, Target_Type) values ('625', 'Package');
insert into review_target (Target_id, Target_Type) values ('626', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('627', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('628', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('629', 'Package');
insert into review_target (Target_id, Target_Type) values ('630', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('631', 'Package');
insert into review_target (Target_id, Target_Type) values ('632', 'Package');
insert into review_target (Target_id, Target_Type) values ('633', 'Package');
insert into review_target (Target_id, Target_Type) values ('634', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('635', 'Package');
insert into review_target (Target_id, Target_Type) values ('636', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('637', 'Package');
insert into review_target (Target_id, Target_Type) values ('638', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('639', 'Package');
insert into review_target (Target_id, Target_Type) values ('640', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('641', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('642', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('643', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('644', 'Package');
insert into review_target (Target_id, Target_Type) values ('645', 'Package');
insert into review_target (Target_id, Target_Type) values ('646', 'Package');
insert into review_target (Target_id, Target_Type) values ('647', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('648', 'Package');
insert into review_target (Target_id, Target_Type) values ('649', 'Package');
insert into review_target (Target_id, Target_Type) values ('650', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('651', 'Package');
insert into review_target (Target_id, Target_Type) values ('652', 'Package');
insert into review_target (Target_id, Target_Type) values ('653', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('654', 'Package');
insert into review_target (Target_id, Target_Type) values ('655', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('656', 'Package');
insert into review_target (Target_id, Target_Type) values ('657', 'Package');
insert into review_target (Target_id, Target_Type) values ('658', 'Package');
insert into review_target (Target_id, Target_Type) values ('659', 'Package');
insert into review_target (Target_id, Target_Type) values ('660', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('661', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('662', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('663', 'Package');
insert into review_target (Target_id, Target_Type) values ('664', 'Package');
insert into review_target (Target_id, Target_Type) values ('665', 'Package');
insert into review_target (Target_id, Target_Type) values ('666', 'Package');
insert into review_target (Target_id, Target_Type) values ('667', 'Package');
insert into review_target (Target_id, Target_Type) values ('668', 'Package');
insert into review_target (Target_id, Target_Type) values ('669', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('670', 'Package');
insert into review_target (Target_id, Target_Type) values ('671', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('672', 'Package');
insert into review_target (Target_id, Target_Type) values ('673', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('674', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('675', 'Package');
insert into review_target (Target_id, Target_Type) values ('676', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('677', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('678', 'Package');
insert into review_target (Target_id, Target_Type) values ('679', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('680', 'Package');
insert into review_target (Target_id, Target_Type) values ('681', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('682', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('683', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('684', 'Package');
insert into review_target (Target_id, Target_Type) values ('685', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('686', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('687', 'Package');
insert into review_target (Target_id, Target_Type) values ('688', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('689', 'Package');
insert into review_target (Target_id, Target_Type) values ('690', 'Package');
insert into review_target (Target_id, Target_Type) values ('691', 'Package');
insert into review_target (Target_id, Target_Type) values ('692', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('693', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('694', 'Package');
insert into review_target (Target_id, Target_Type) values ('695', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('696', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('697', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('698', 'Package');
insert into review_target (Target_id, Target_Type) values ('699', 'Package');
insert into review_target (Target_id, Target_Type) values ('700', 'Package');
insert into review_target (Target_id, Target_Type) values ('701', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('702', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('703', 'Package');
insert into review_target (Target_id, Target_Type) values ('704', 'Package');
insert into review_target (Target_id, Target_Type) values ('705', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('706', 'Package');
insert into review_target (Target_id, Target_Type) values ('707', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('708', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('709', 'Package');
insert into review_target (Target_id, Target_Type) values ('710', 'Package');
insert into review_target (Target_id, Target_Type) values ('711', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('712', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('713', 'Package');
insert into review_target (Target_id, Target_Type) values ('714', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('715', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('716', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('717', 'Package');
insert into review_target (Target_id, Target_Type) values ('718', 'Package');
insert into review_target (Target_id, Target_Type) values ('719', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('720', 'Package');
insert into review_target (Target_id, Target_Type) values ('721', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('722', 'Package');
insert into review_target (Target_id, Target_Type) values ('723', 'Package');
insert into review_target (Target_id, Target_Type) values ('724', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('725', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('726', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('727', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('728', 'Package');
insert into review_target (Target_id, Target_Type) values ('729', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('730', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('731', 'Package');
insert into review_target (Target_id, Target_Type) values ('732', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('733', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('734', 'Package');
insert into review_target (Target_id, Target_Type) values ('735', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('736', 'Package');
insert into review_target (Target_id, Target_Type) values ('737', 'Package');
insert into review_target (Target_id, Target_Type) values ('738', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('739', 'Package');
insert into review_target (Target_id, Target_Type) values ('740', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('741', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('742', 'Package');
insert into review_target (Target_id, Target_Type) values ('743', 'Package');
insert into review_target (Target_id, Target_Type) values ('744', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('745', 'Package');
insert into review_target (Target_id, Target_Type) values ('746', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('747', 'Package');
insert into review_target (Target_id, Target_Type) values ('748', 'Package');
insert into review_target (Target_id, Target_Type) values ('749', 'Package');
insert into review_target (Target_id, Target_Type) values ('750', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('751', 'Package');
insert into review_target (Target_id, Target_Type) values ('752', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('753', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('754', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('755', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('756', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('757', 'Package');
insert into review_target (Target_id, Target_Type) values ('758', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('759', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('760', 'Package');
insert into review_target (Target_id, Target_Type) values ('761', 'Package');
insert into review_target (Target_id, Target_Type) values ('762', 'Package');
insert into review_target (Target_id, Target_Type) values ('763', 'Package');
insert into review_target (Target_id, Target_Type) values ('764', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('765', 'Package');
insert into review_target (Target_id, Target_Type) values ('766', 'Package');
insert into review_target (Target_id, Target_Type) values ('767', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('768', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('769', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('770', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('771', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('772', 'Package');
insert into review_target (Target_id, Target_Type) values ('773', 'Package');
insert into review_target (Target_id, Target_Type) values ('774', 'Package');
insert into review_target (Target_id, Target_Type) values ('775', 'Package');
insert into review_target (Target_id, Target_Type) values ('776', 'Package');
insert into review_target (Target_id, Target_Type) values ('777', 'Package');
insert into review_target (Target_id, Target_Type) values ('778', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('779', 'Package');
insert into review_target (Target_id, Target_Type) values ('780', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('781', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('782', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('783', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('784', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('785', 'Package');
insert into review_target (Target_id, Target_Type) values ('786', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('787', 'Package');
insert into review_target (Target_id, Target_Type) values ('788', 'Package');
insert into review_target (Target_id, Target_Type) values ('789', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('790', 'Package');
insert into review_target (Target_id, Target_Type) values ('791', 'Package');
insert into review_target (Target_id, Target_Type) values ('792', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('793', 'Package');
insert into review_target (Target_id, Target_Type) values ('794', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('795', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('796', 'Package');
insert into review_target (Target_id, Target_Type) values ('797', 'Package');
insert into review_target (Target_id, Target_Type) values ('798', 'Package');
insert into review_target (Target_id, Target_Type) values ('799', 'Package');
insert into review_target (Target_id, Target_Type) values ('800', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('801', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('802', 'Package');
insert into review_target (Target_id, Target_Type) values ('803', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('804', 'Package');
insert into review_target (Target_id, Target_Type) values ('805', 'Package');
insert into review_target (Target_id, Target_Type) values ('806', 'Package');
insert into review_target (Target_id, Target_Type) values ('807', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('808', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('809', 'Package');
insert into review_target (Target_id, Target_Type) values ('810', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('811', 'Package');
insert into review_target (Target_id, Target_Type) values ('812', 'Package');
insert into review_target (Target_id, Target_Type) values ('813', 'Package');
insert into review_target (Target_id, Target_Type) values ('814', 'Package');
insert into review_target (Target_id, Target_Type) values ('815', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('816', 'Package');
insert into review_target (Target_id, Target_Type) values ('817', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('818', 'Package');
insert into review_target (Target_id, Target_Type) values ('819', 'Package');
insert into review_target (Target_id, Target_Type) values ('820', 'Package');
insert into review_target (Target_id, Target_Type) values ('821', 'Package');
insert into review_target (Target_id, Target_Type) values ('822', 'Package');
insert into review_target (Target_id, Target_Type) values ('823', 'Package');
insert into review_target (Target_id, Target_Type) values ('824', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('825', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('826', 'Package');
insert into review_target (Target_id, Target_Type) values ('827', 'Package');
insert into review_target (Target_id, Target_Type) values ('828', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('829', 'Package');
insert into review_target (Target_id, Target_Type) values ('830', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('831', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('832', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('833', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('834', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('835', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('836', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('837', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('838', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('839', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('840', 'Package');
insert into review_target (Target_id, Target_Type) values ('841', 'Package');
insert into review_target (Target_id, Target_Type) values ('842', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('843', 'Package');
insert into review_target (Target_id, Target_Type) values ('844', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('845', 'Package');
insert into review_target (Target_id, Target_Type) values ('846', 'Package');
insert into review_target (Target_id, Target_Type) values ('847', 'Package');
insert into review_target (Target_id, Target_Type) values ('848', 'Package');
insert into review_target (Target_id, Target_Type) values ('849', 'Package');
insert into review_target (Target_id, Target_Type) values ('850', 'Package');
insert into review_target (Target_id, Target_Type) values ('851', 'Package');
insert into review_target (Target_id, Target_Type) values ('852', 'Package');
insert into review_target (Target_id, Target_Type) values ('853', 'Package');
insert into review_target (Target_id, Target_Type) values ('854', 'Package');
insert into review_target (Target_id, Target_Type) values ('855', 'Package');
insert into review_target (Target_id, Target_Type) values ('856', 'Package');
insert into review_target (Target_id, Target_Type) values ('857', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('858', 'Package');
insert into review_target (Target_id, Target_Type) values ('859', 'Package');
insert into review_target (Target_id, Target_Type) values ('860', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('861', 'Package');
insert into review_target (Target_id, Target_Type) values ('862', 'Package');
insert into review_target (Target_id, Target_Type) values ('863', 'Package');
insert into review_target (Target_id, Target_Type) values ('864', 'Package');
insert into review_target (Target_id, Target_Type) values ('865', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('866', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('867', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('868', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('869', 'Package');
insert into review_target (Target_id, Target_Type) values ('870', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('871', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('872', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('873', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('874', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('875', 'Package');
insert into review_target (Target_id, Target_Type) values ('876', 'Package');
insert into review_target (Target_id, Target_Type) values ('877', 'Package');
insert into review_target (Target_id, Target_Type) values ('878', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('879', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('880', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('881', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('882', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('883', 'Package');
insert into review_target (Target_id, Target_Type) values ('884', 'Package');
insert into review_target (Target_id, Target_Type) values ('885', 'Package');
insert into review_target (Target_id, Target_Type) values ('886', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('887', 'Package');
insert into review_target (Target_id, Target_Type) values ('888', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('889', 'Package');
insert into review_target (Target_id, Target_Type) values ('890', 'Package');
insert into review_target (Target_id, Target_Type) values ('891', 'Package');
insert into review_target (Target_id, Target_Type) values ('892', 'Package');
insert into review_target (Target_id, Target_Type) values ('893', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('894', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('895', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('896', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('897', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('898', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('899', 'Package');
insert into review_target (Target_id, Target_Type) values ('900', 'Package');
insert into review_target (Target_id, Target_Type) values ('901', 'Package');
insert into review_target (Target_id, Target_Type) values ('902', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('903', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('904', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('905', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('906', 'Package');
insert into review_target (Target_id, Target_Type) values ('907', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('908', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('909', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('910', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('911', 'Package');
insert into review_target (Target_id, Target_Type) values ('912', 'Package');
insert into review_target (Target_id, Target_Type) values ('913', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('914', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('915', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('916', 'Package');
insert into review_target (Target_id, Target_Type) values ('917', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('918', 'Package');
insert into review_target (Target_id, Target_Type) values ('919', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('920', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('921', 'Package');
insert into review_target (Target_id, Target_Type) values ('922', 'Package');
insert into review_target (Target_id, Target_Type) values ('923', 'Package');
insert into review_target (Target_id, Target_Type) values ('924', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('925', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('926', 'Package');
insert into review_target (Target_id, Target_Type) values ('927', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('928', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('929', 'Package');
insert into review_target (Target_id, Target_Type) values ('930', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('931', 'Package');
insert into review_target (Target_id, Target_Type) values ('932', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('933', 'Package');
insert into review_target (Target_id, Target_Type) values ('934', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('935', 'Package');
insert into review_target (Target_id, Target_Type) values ('936', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('937', 'Package');
insert into review_target (Target_id, Target_Type) values ('938', 'Package');
insert into review_target (Target_id, Target_Type) values ('939', 'Package');
insert into review_target (Target_id, Target_Type) values ('940', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('941', 'Package');
insert into review_target (Target_id, Target_Type) values ('942', 'Package');
insert into review_target (Target_id, Target_Type) values ('943', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('944', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('945', 'Package');
insert into review_target (Target_id, Target_Type) values ('946', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('947', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('948', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('949', 'Package');
insert into review_target (Target_id, Target_Type) values ('950', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('951', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('952', 'Package');
insert into review_target (Target_id, Target_Type) values ('953', 'Package');
insert into review_target (Target_id, Target_Type) values ('954', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('955', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('956', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('957', 'Package');
insert into review_target (Target_id, Target_Type) values ('958', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('959', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('960', 'Package');
insert into review_target (Target_id, Target_Type) values ('961', 'Package');
insert into review_target (Target_id, Target_Type) values ('962', 'Package');
insert into review_target (Target_id, Target_Type) values ('963', 'Package');
insert into review_target (Target_id, Target_Type) values ('964', 'Package');
insert into review_target (Target_id, Target_Type) values ('965', 'Package');
insert into review_target (Target_id, Target_Type) values ('966', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('967', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('968', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('969', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('970', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('971', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('972', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('973', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('974', 'Package');
insert into review_target (Target_id, Target_Type) values ('975', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('976', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('977', 'Package');
insert into review_target (Target_id, Target_Type) values ('978', 'Package');
insert into review_target (Target_id, Target_Type) values ('979', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('980', 'Package');
insert into review_target (Target_id, Target_Type) values ('981', 'Package');
insert into review_target (Target_id, Target_Type) values ('982', 'Package');
insert into review_target (Target_id, Target_Type) values ('983', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('984', 'Package');
insert into review_target (Target_id, Target_Type) values ('985', 'Package');
insert into review_target (Target_id, Target_Type) values ('986', 'Package');
insert into review_target (Target_id, Target_Type) values ('987', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('988', 'Package');
insert into review_target (Target_id, Target_Type) values ('989', 'Package');
insert into review_target (Target_id, Target_Type) values ('990', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('991', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('992', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('993', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('994', 'Package');
insert into review_target (Target_id, Target_Type) values ('995', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('996', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('997', 'Travel Agency');
insert into review_target (Target_id, Target_Type) values ('998', 'Package');
insert into review_target (Target_id, Target_Type) values ('999', 'Package');
